export type TFQuestion = {
  id: number;
  statement: string;
  answer: boolean;
  explanation: string;
  topic: string;
};

export const ethicsQuestions: TFQuestion[] = [
  // ── Ethics as a Discipline ──────────────────────────────────────────────
  { id: 1, statement: "Philosophy is defined as a comprehensive, fundamental, and insightful examination beginning in common human experience.", answer: true, explanation: "This is the exact definition of philosophy given in the course notes.", topic: "Ethics as a Discipline" },
  { id: 2, statement: "Philosophical ethics is posterior to (comes after) Moral Theology.", answer: false, explanation: "Philosophical ethics is PRIOR to Moral Theology — it comes before it.", topic: "Ethics as a Discipline" },
  { id: 3, statement: "Rousseau believed that children should have ethical expectations imposed on them for their development.", answer: false, explanation: "Rousseau believed children should follow their natural desires — the 'noble savage' view — rather than having ethical expectations imposed on them.", topic: "Ethics as a Discipline" },
  { id: 4, statement: "According to Hobbes, morality and ethics come from the state.", answer: true, explanation: "Hobbes holds that ethics arises from a desire to escape the misery of the state of nature. We hand over freedom to the state, and morality comes from that political arrangement.", topic: "Ethics as a Discipline" },
  { id: 5, statement: "Ethics only studies human behavior insofar as expectations are imposed from the more powerful to the weaker (Thrasymachus) or from the weaker to the more powerful (Nietzsche).", answer: false, explanation: "This is the rejected objection. The assertion is that ethics studies human conduct insofar as it is OBJECTIVELY right or wrong.", topic: "Ethics as a Discipline" },
  { id: 6, statement: "The emotive theory holds that ethical statements have genuine truth value.", answer: false, explanation: "The emotive theory holds that ethics is reduced to a FEELING elicited when we observe certain behavior — it denies that ethical statements have truth value.", topic: "Ethics as a Discipline" },
  { id: 7, statement: "Ethics guides us to true fulfillment, which is why it must be knowledge and not merely feelings.", answer: true, explanation: "This is the justification given in the notes: feelings cannot direct us to human flourishing, but ethics — as knowledge — can.", topic: "Ethics as a Discipline" },
  { id: 8, statement: "An ought cannot be derived from an is.", answer: true, explanation: "This is a key principle in the notes — the facts of social behavior (sociology, psychology, anthropology) are irrelevant to what OUGHT to be done.", topic: "Ethics as a Discipline" },
  { id: 9, statement: "The facts of social behavior from sociology and psychology are sufficient to determine what we ought to do.", answer: false, explanation: "Empirical sciences exclude the notion of 'ought.' A purely empirical approach cannot bring us to full human flourishing.", topic: "Ethics as a Discipline" },
  { id: 10, statement: "Ethics follows the Socratic dictum 'Know thyself!'", answer: true, explanation: "The notes state: 'Ethics follows the Socratic dictum: Know thyself! — Ethics is knowing ourselves as human beings.'", topic: "Ethics as a Discipline" },
  { id: 11, statement: "Moral skepticism holds that there is no way of objectively knowing what is right or wrong.", answer: true, explanation: "Moral skepticism: 'There are good reasons for and against particular beliefs about ethics, but there is no way of objectively knowing what is right or wrong.'", topic: "Ethics as a Discipline" },
  { id: 12, statement: "Moral particularism holds that there are true general moral rules that guide all situations.", answer: false, explanation: "Moral particularism holds the OPPOSITE — there are NO true general moral rules. We are just guided by our particular situations.", topic: "Ethics as a Discipline" },
  { id: 13, statement: "The definition of ethics is 'the practical normative science of the rightness and wrongness of human conduct as known by natural reason.'", answer: true, explanation: "This is the exact definition of ethics given at the conclusion of the foundational section.", topic: "Ethics as a Discipline" },
  { id: 14, statement: "Ethics is purely theoretical in nature with no practical application.", answer: false, explanation: "Ethics involves BOTH foundational knowledge AND the application of principles within particular contexts. It is a practical discipline, not purely theoretical.", topic: "Ethics as a Discipline" },

  // ── Socrates & Aristotle ─────────────────────────────────────────────────
  { id: 15, statement: "Socrates emphasized virtue over wealth, pleasure, and power.", answer: true, explanation: "The notes state: 'He emphasizes virtue over things like wealth, pleasure, and power.'", topic: "Socrates & Aristotle" },
  { id: 16, statement: "Sophists generally hold that there is no absolute truth, only truths dependent on context or circumstances.", answer: true, explanation: "Sophists are commonly relativists. Relativism is the view that there is no absolute truth, only truths dependent fully on certain contexts or circumstances.", topic: "Socrates & Aristotle" },
  { id: 17, statement: "Socrates was a relativist in ethics.", answer: false, explanation: "Socrates was NOT a relativist in ethics. Ethics teaches us what is true for ALL people.", topic: "Socrates & Aristotle" },
  { id: 18, statement: "Aristotle's 'Saving the Phenomena' method begins by setting out the various types of experiences and common beliefs across human experience.", answer: true, explanation: "Step 1 of Saving the Phenomena: 'First you set out the various types of experiences and beliefs that are common across the breadth of human experience.'", topic: "Socrates & Aristotle" },
  { id: 19, statement: "Aristotle believed that ethics is primarily a theoretical discipline.", answer: false, explanation: "Aristotle thinks ethics is a PRACTICAL discipline as opposed to a theoretical discipline. Context partially determines what a virtue is.", topic: "Socrates & Aristotle" },
  { id: 20, statement: "According to Aristotle, making progress in ethics involves observing and emulating virtuous people.", answer: true, explanation: "As a practical discipline, progress in ethics requires observing and emulating the actions and perspectives of those who already are virtuous.", topic: "Socrates & Aristotle" },
  { id: 21, statement: "Aristotle believed it is possible to know that something is wrong and still do it.", answer: true, explanation: "This is the phenomenon of the incontinent person — the person who wills the good in some way but is not strong enough to carry it out. Aristotle affirms this is possible.", topic: "Socrates & Aristotle" },
  { id: 22, statement: "Socrates believed that incontinence (knowing something is wrong but doing it anyway) is truly possible.", answer: false, explanation: "Socrates does NOT think that incontinence is truly possible. For Socrates, you either know a virtuous action is good, or you don't.", topic: "Socrates & Aristotle" },

  // ── The Good ─────────────────────────────────────────────────────────────
  { id: 23, statement: "Eliminativism is self-contradictory because asserting it is itself a goal-oriented act toward truth.", answer: true, explanation: "The notes state: 'Eliminativism is self-contradictory — asserting eliminativism is true is itself a goal-oriented act toward truth.'", topic: "The Good" },
  { id: 24, statement: "Whenever human beings act, they always have a purpose in mind.", answer: true, explanation: "This is the assertion in Fagothey Ch. 2: 'Whenever human beings act, they have a purpose in mind in carrying out that act.'", topic: "The Good" },
  { id: 25, statement: "Some human actions can seek evil purely for evil's sake, with no good being sought at all.", answer: false, explanation: "The assertion is that whenever one acts with a goal or end in mind, one is ALWAYS seeking to achieve some good — even if it is only an apparent good or a lesser good.", topic: "The Good" },
  { id: 26, statement: "Being and goodness are convertible with each other.", answer: true, explanation: "From metaphysics: 'Being and goodness are in fact convertible with each other. Whenever we act, we intend to bring something good into existence.'", topic: "The Good" },
  { id: 27, statement: "The view that all actions seek some good implies egoism.", answer: false, explanation: "The notes explicitly reject this: 'Although all actions are always motivated and oriented to some good, this view is NOT a form of egoism.'", topic: "The Good" },
  { id: 28, statement: "According to ethical relativism, there is no objective hierarchy or encompassing Good that all human beings are trying to achieve.", answer: true, explanation: "Ethical relativism holds that 'there is no objective hierarchy nor encompassing Good that we are trying to achieve. Whether a given action is good or evil is dependent on more particular circumstances.'", topic: "The Good" },
  { id: 29, statement: "The end is prior in execution to the means.", answer: false, explanation: "The MEANS is prior in execution to the end. The END is prior in existence/being. 'Although a means is prior in execution to the end, the end is prior to the means in the sense that the means cannot exist without there first existing an end.'", topic: "The Good" },
  { id: 30, statement: "There must be an ultimate end to justify any action, and there cannot be an infinite regress of ends.", answer: true, explanation: "Since the end is prior in existence to the means, there cannot be an infinite regress of ends. There must be an ultimate end to justify any action.", topic: "The Good" },
  { id: 31, statement: "Existentialism holds that existence precedes essence.", answer: true, explanation: "Sartre's existentialism: 'Our existence precedes our essence, which means that we have freedom without needing to conform to some pre-established essence.'", topic: "The Good" },
  { id: 32, statement: "According to existentialism, human beings have a fixed, pre-established essence they must conform to.", answer: false, explanation: "Existentialism holds the OPPOSITE — we make our own essence through our actions. We are 'condemned to be free.' There is no manual for what we are or how to act.", topic: "The Good" },
  { id: 33, statement: "The morally good human being is one who directs themselves to their last end by the performance of morally good acts.", answer: true, explanation: "This is the exact assertion from Fagothey: 'The morally good human is one who directs himself, or herself, to his or her last end by the performance of morally good acts.'", topic: "The Good" },

  // ── Happiness ────────────────────────────────────────────────────────────
  { id: 34, statement: "Happiness is defined as merely a feeling of elation or temporary contentment.", answer: false, explanation: "This is the rejected view. Happiness is properly defined as 'desire satisfied by conscious possession of the good' — it involves the complete satisfaction of all our desires as rational animals.", topic: "Happiness" },
  { id: 35, statement: "Perfect happiness involves the complete satisfaction of all our desires as rational animals.", answer: true, explanation: "'Happiness will involve the complete satisfaction of all our desires as rational animals and does not rest satisfied with those things that are only attainable in this life.'", topic: "Happiness" },
  { id: 36, statement: "Everyone seeks happiness, but people differ in what they judge will make them happy.", answer: true, explanation: "This is the assertion: 'Everyone seeks happiness in general but differs in what they judge will make them happy.'", topic: "Happiness" },
  { id: 37, statement: "Perfect happiness is attainable, since no natural deep-seated desires are universally frustrated in achieving their end.", answer: true, explanation: "'No natural desires are universally frustrated in achieving their end. If there is a natural, deep-seated desire, there must in principle be something that can satisfy that desire.'", topic: "Happiness" },
  { id: 38, statement: "The scope of human happiness, even known by natural reason alone, is limited to this present life.", answer: false, explanation: "The assertion states: 'the scope and range of human happiness transcends this present life.' The immortality of the soul expands the scope of happiness beyond this present life.", topic: "Happiness" },
  { id: 39, statement: "For Plato, the good is accessible through sensory experience.", answer: false, explanation: "For Plato, it is ONLY through an intellectual act APART from perception and matter that we are able to gaze upon the good itself. Sense distracts us from the good.", topic: "Happiness" },
  { id: 40, statement: "Aristotle's first criterion of happiness involves living according to one's overall purpose established by one's human nature.", answer: true, explanation: "'Happiness comes with living according to one's overall purpose, established by one's human nature.'", topic: "Happiness" },
  { id: 41, statement: "The soul has three components: nutritive, perceptive, and rational.", answer: true, explanation: "The notes list all three: Nutritive Part (growth and reproduction), Perceptive Part (consciousness and sensation), Rational Part (intellect, truth, reason).", topic: "Happiness" },
  { id: 42, statement: "A life seeking pleasure alone fulfills Aristotle's criteria for happiness.", answer: false, explanation: "'A life seeking pleasure won't make you happy.' Aristotle's second criterion is self-sufficiency, and virtue is a necessary path on the pursuit of happiness.", topic: "Happiness" },
  { id: 43, statement: "A life seeking honor fulfills Aristotle's criteria for happiness.", answer: false, explanation: "'A life seeking honor won't make you happy.' Aristotle holds that happiness requires virtue, not just honor.", topic: "Happiness" },
  { id: 44, statement: "Aristotle's definition of happiness requires moral virtue, intellectual pursuits, AND a degree of external goods.", answer: true, explanation: "'Happiness requires moral virtue... It involves intellectual pursuits of knowledge and prudence... However, it also requires a certain degree of extrinsic or external goods such as food, friends, money.'", topic: "Happiness" },

  // ── Pursuit of Happiness / Pleasure / Mill ──────────────────────────────
  { id: 45, statement: "Hedonism holds that happiness is obtained in the possession of pleasure.", answer: true, explanation: "Hedonism: 'Happiness is obtained in the possessions of pleasure. Chase pleasure, avoid pain.'", topic: "Pursuit of Happiness & Mill" },
  { id: 46, statement: "Utilitarianism seeks to maximize the greatest good for the greatest number.", answer: true, explanation: "Utilitarianism: 'Happiness consists in maximizing the greatest good for the greatest number.'", topic: "Pursuit of Happiness & Mill" },
  { id: 47, statement: "Stoicism holds that happiness consists in obtaining virtue and deep harmony with the laws of nature.", answer: true, explanation: "Stoicism: 'Happiness simply consists in obtaining virtue. Deep harmony with the laws of nature.'", topic: "Pursuit of Happiness & Mill" },
  { id: 48, statement: "Evolutionism holds that happiness consists in maximizing pleasure for the greatest number of people.", answer: false, explanation: "That is Utilitarianism. Evolutionism holds that happiness consists in SELF-REALIZATION and fulfilling one's evolutionary trajectory — unlocking one's latent capacities.", topic: "Pursuit of Happiness & Mill" },
  { id: 49, statement: "According to Fagothey, natural happiness knowable by philosophy consists in knowing and loving God analogically through His created order.", answer: true, explanation: "The assertion: 'Happiness, knowable from a natural perspective independent from Divine Revelation, consists in knowing and loving God known analogically through God's created order.'", topic: "Pursuit of Happiness & Mill" },
  { id: 50, statement: "Natural happiness and the Beatific Vision are completely independent of each other with no relationship.", answer: false, explanation: "The assertion rejects this: 'Because of the relationship God has to created persons, the Beatific Vision is the PERFECTION of even a naturally perfectly happy human being.' They are related — the Beatific Vision is a super-perfection of a natural perfection.", topic: "Pursuit of Happiness & Mill" },
  { id: 51, statement: "The Beatific Vision is a perfection that goes beyond the natural capacities of the intellect and will.", answer: true, explanation: "'The Beatific vision is happiness in the sense that it is the perfection of that which is beyond one's own natural capacities of their intellect and will. God reveals Himself directly to the blessed and enhances their capacities.'", topic: "Pursuit of Happiness & Mill" },
  { id: 52, statement: "For Aristotle, pleasure is a genuine good to be directly pursued.", answer: false, explanation: "'Pleasure is NOT a genuine good itself to be directly pursued, but rather something that only accompanies in a secondary way a proper activity and good-oriented behavior.'", topic: "Pursuit of Happiness & Mill" },
  { id: 53, statement: "Pleasure is experienced in stages across time, similar to how a process unfolds.", answer: false, explanation: "'Pleasure is experienced as a whole and NOT realized in stages across time.' It is immediate and complete — one either is in a state of pleasure, or one is not.", topic: "Pursuit of Happiness & Mill" },
  { id: 54, statement: "Mill's General Happiness Principle states that actions are right insofar as they tend to promote happiness.", answer: true, explanation: "'The General Happiness Principle: Actions are right in proportion as they tend to promote happiness, wrong as they tend to produce the reverse of happiness.'", topic: "Pursuit of Happiness & Mill" },
  { id: 55, statement: "Mill believes that all pleasures are equal in quality.", answer: false, explanation: "Mill explicitly argues for a HIERARCHY of pleasures. Higher pleasures (intellectual) are of greater quality than lower pleasures (bodily), even if they come with more discontent.", topic: "Pursuit of Happiness & Mill" },
  { id: 56, statement: "According to Mill, the intention behind an action determines its moral status.", answer: false, explanation: "'The intention or motivation for doing the action is actually IRRELEVANT for determining the action as moral or immoral. Only the consequence matters: maximizing pleasure for the greatest number.'", topic: "Pursuit of Happiness & Mill" },
  { id: 57, statement: "Mill holds that duty is an objective and universally mandated obligation.", answer: false, explanation: "Mill says: 'Duty is a pain, more or less intense, attendant on violation.' For Mill, duty is merely a certain feeling or attitude one has to certain actions — not an objective obligation.", topic: "Pursuit of Happiness & Mill" },
  { id: 58, statement: "Mill argues that conscience is a complex of feelings, self-estimations, fear, guilt, loves, and religious sentiments.", answer: true, explanation: "This is Mill's own description of conscience — he reduces it to a complex of subjective feelings rather than an objective moral sense.", topic: "Pursuit of Happiness & Mill" },

  // ── Human Action & Will ─────────────────────────────────────────────────
  { id: 59, statement: "The purpose of this life is to conduct ourselves in a way worthy of the possibility of happiness in the life to come.", answer: true, explanation: "This is the assertion in Fagothey's Human Act Part 1: 'The purpose of this life is to conduct ourselves in a way worthy of the possibility of happiness in the life to come.'", topic: "Human Action & Will" },
  { id: 60, statement: "Human acts are those that are consciously controlled and deliberately willed.", answer: true, explanation: "'Human acts are those that are consciously controlled and deliberately willed. They are the only actions relevant to the conduct ordered to the possession of one's ultimate end.'", topic: "Human Action & Will" },
  { id: 61, statement: "Acts of a human (e.g., eating while sleepwalking) are just as morally relevant as human acts for achieving one's last end.", answer: false, explanation: "'An act of a human — acts a person happens to perform but is not master of — is NOT relevant in an active sense to achieving the ultimate end.' Only deliberate human acts matter.", topic: "Human Action & Will" },
  { id: 62, statement: "We deliberate about both ends and means.", answer: false, explanation: "We deliberate about MEANS, not ends. 'Do not deliberate about ends, just about means.' The ultimate end (happiness) is fixed.", topic: "Human Action & Will" },
  { id: 63, statement: "A wish involves an expectation that the goal might possibly be achieved.", answer: false, explanation: "A wish is 'an extremely broad desire of the will where there is NO expectation of possibility of fulfillment.' That expectation belongs to INTENTION.", topic: "Human Action & Will" },
  { id: 64, statement: "Choice involves opting for a specific means among many alternatives.", answer: true, explanation: "Choice is 'the last practical judgement of the deliberation process at which point one opts for a particular means among many.'", topic: "Human Action & Will" },
  { id: 65, statement: "Aquinas holds that the will is completely independent of the intellect.", answer: false, explanation: "'The will is DEPENDENT on the intellect. The will only cares about the intellectual good. All choices are a result of rational deliberation.'", topic: "Human Action & Will" },
  { id: 66, statement: "Free will applies to the choice of means, even when the ultimate end (happiness) is fixed.", answer: true, explanation: "'Free will is related to choosing among means even when the end is fixed. This is true even when the end is happiness itself.'", topic: "Human Action & Will" },
  { id: 67, statement: "When God makes Himself known in the Beatific Vision, the blessed retain the ability to choose things contrary to knowing and loving God.", answer: false, explanation: "'When God makes Himself known in the Beatific Vision, they will no longer be able to choose anything contrary to knowing and loving God — it will be seen as necessary for maintaining and achieving happiness.'", topic: "Human Action & Will" },
  { id: 68, statement: "Free will is possible because some goods are only contingently related to our happiness.", answer: true, explanation: "'Free will is possible because some things are understood to be only contingently related to our happiness' — we can still be happy even if we miss out on them, so we have freedom to choose.", topic: "Human Action & Will" },

  // ── Voluntariness ────────────────────────────────────────────────────────
  { id: 69, statement: "Both acting (positive) and not acting (negative) can be voluntary.", answer: true, explanation: "'Both acting and not acting can be voluntary. Sometimes, one can be better by not doing a thing.' Not doing something involves choice and contributes to objective happiness or unhappiness.", topic: "Voluntariness" },
  { id: 70, statement: "A virtual intention is consciously present at the moment the act is performed.", answer: false, explanation: "A virtual intention 'was made once and continues to influence the act now being done but is NOT present to the person's consciousness at the moment of performing the act.'", topic: "Voluntariness" },
  { id: 71, statement: "A foreseen but unintended consequence of a voluntary act is called indirectly voluntary.", answer: true, explanation: "'A consequence of an act can be indirectly voluntary (voluntary in cause) when it is unintended but a foreseen consequence of something that is voluntary in itself.'", topic: "Voluntariness" },
  { id: 72, statement: "Foreseen consequences that fall outside our intention are directly voluntary.", answer: false, explanation: "'Since such consequences are brought about OUTSIDE our intention and end for doing the action, it will only be INDIRECTLY voluntary instead of directly voluntary.'", topic: "Voluntariness" },
  { id: 73, statement: "Physical force can change another person's will.", answer: false, explanation: "'One cannot force another to change his or her will through that act of physical force.' Force can compel external action but cannot directly change the internal will.", topic: "Voluntariness" },
  { id: 74, statement: "Voluntariness can be modified by ignorance, passion, fear, force, or habit.", answer: true, explanation: "'Voluntariness of an action admits of degrees and is possibly modified by ignorance, passion, fear, force, or habit.'", topic: "Voluntariness" },
  { id: 75, statement: "Invincible ignorance removes culpability for the wrongness of an action.", answer: true, explanation: "'Invincible ignorance is placed in no fault of their own due to the difficulty of removing such ignorance.' Not having relevant info when making a decision can remove voluntariness to the point that the badness of the action is not imputed to the agent.", topic: "Voluntariness" },
  { id: 76, statement: "Antecedent passions are those we intentionally stir up by brooding on objects that arouse them.", answer: false, explanation: "Those are CONSEQUENT passions. Antecedent passions 'come before our will immediately and spontaneously' — they arise without deliberate stirring.", topic: "Voluntariness" },
  { id: 77, statement: "Consequent passions come before our will immediately and spontaneously.", answer: false, explanation: "Those are ANTECEDENT passions. Consequent passions are 'when we intentionally stir up our passions by brooding on the objects that arouse them.'", topic: "Voluntariness" },
  { id: 78, statement: "Just because an action is done through habit, it is automatically involuntary.", answer: false, explanation: "'Just because an action is done through habit doesn't make it involuntary. Habits are a helpful part because they help us do complex actions in a natural way.'", topic: "Voluntariness" },

  // ── Morality ──────────────────────────────────────────────────────────────
  { id: 79, statement: "Only subjective intentions matter in moral assessment — objective conditions are irrelevant.", answer: false, explanation: "'When assessing a moral action, both the SUBJECTIVE and OBJECTIVE conditions of the act are determinative to the morality of the action.' Both work together.", topic: "Morality" },
  { id: 80, statement: "According to Hobbes, objective morality exists in the state of nature prior to any political arrangement.", answer: false, explanation: "For Hobbes, life in the state of nature is 'nasty, brutish, and short' with NO objective morality. Standards of right and wrong only arise when we live together in a political arrangement.", topic: "Morality" },
  { id: 81, statement: "According to Rousseau, the political arrangement generates problems and then imposes objective morality to address these ills.", answer: true, explanation: "Rousseau: 'In the state of nature man is naturally altruistic... The political arrangement generates problems and then imposes objective morality in order to address these ills.'", topic: "Morality" },
  { id: 82, statement: "According to Nietzsche, morality empowers the strong over the weak.", answer: false, explanation: "Nietzsche says the OPPOSITE: morality is 'a kind of hack that SHIFTS POWER FROM THE POWERFUL TO THE WEAK.' It is a form of brainwashing to suppress the natural abilities of the powerful.", topic: "Morality" },
  { id: 83, statement: "According to Marx, morality is a strategy to preserve a particular economic system and keep the proletariat from revolting.", answer: true, explanation: "'Rightness and wrongness are those rules through which a particular economic system is preserved. Morality is a way of brainwashing [the proletariat] to keep the exploitative capitalist system going.'", topic: "Morality" },
  { id: 84, statement: "Some actions are right or wrong by nature (intrinsically), not just through political laws (extrinsically).", answer: true, explanation: "The assertion: 'Although it is recognized that there are some objectively moral actions determined extrinsically (through political laws), there are some things that are right or wrong by nature — intrinsically.' Murder is an example.", topic: "Morality" },
  { id: 85, statement: "Murder is an example of an action that could potentially be made customary and morally acceptable.", answer: false, explanation: "'Some actions should NEVER be made customary, such as murder. This is because some actions are intrinsically and necessarily ordered to our human happiness' — murder intrinsically contradicts it.", topic: "Morality" },
];

export const ethicsTopics = [
  "Ethics as a Discipline",
  "Socrates & Aristotle",
  "The Good",
  "Happiness",
  "Pursuit of Happiness & Mill",
  "Human Action & Will",
  "Voluntariness",
  "Morality",
];
