export type GlossaryTerm = {
  term: string;
  definition: string;
  category: string;
};

export const glossary: GlossaryTerm[] = [
  // Plato
  { term: "Eikasia", definition: "The state of illusion — the lowest section of Plato's Divided Line. The realm of shadows, reflections, and images; the furthest state from truth.", category: "Plato" },
  { term: "Pistis", definition: "The state of belief — the second section of the Divided Line. The realm of physical objects, animals, and man-made items perceived through the senses.", category: "Plato" },
  { term: "Dianoia", definition: "The state of mathematical reasoning — the third section of the Divided Line. The realm of mathematical forms and geometry; second closest to truth.", category: "Plato" },
  { term: "Noesis", definition: "The state of pure intelligence — the highest section of the Divided Line. The realm of pure ideas, the Forms (eidos), and philosophy; closest to truth.", category: "Plato" },
  { term: "Doxa", definition: "Opinion — the result of the visible realm (eikasia + pistis). Not true knowledge, but belief based on appearances.", category: "Plato" },
  { term: "Episteme", definition: "Knowledge — the result of the intelligible realm (dianoia + noesis). True, justified understanding reached through reason.", category: "Plato" },
  { term: "Divided Line", definition: "Plato's model from Republic Book 6 dividing reality into four levels: illusion, belief, mathematical reasoning, and pure intelligence — moving from appearances to truth.", category: "Plato" },
  { term: "Allegory of the Cave", definition: "Plato's parable from Republic Book 7 illustrating the journey from ignorance (shadows on a cave wall) to enlightenment (seeing the sun/Form of the Good).", category: "Plato" },
  { term: "Forms (Eidos)", definition: "For Plato, the eternal, unchanging, perfect archetypes of which physical things are imperfect copies. Accessible through the mind, not the senses.", category: "Plato" },
  { term: "Realm of Forms", definition: "The intelligible world of perfect, eternal realities that exist independently of the physical world. The source of all truth and knowledge for Plato.", category: "Plato" },
  { term: "Realm of Copies", definition: "The visible, material world of imperfect, changing things that participate in or imitate the Forms.", category: "Plato" },
  { term: "Participation", definition: "Plato's doctrine that physical things share in or participate in the Forms, which is why they have the properties they do.", category: "Plato" },

  // Aristotle
  { term: "Saving the Appearances", definition: "Aristotle's methodology: verifying philosophical claims by checking them against common beliefs and observable experience. A theory must account for what we actually observe.", category: "Aristotle" },
  { term: "Syllogism", definition: "A form of deductive reasoning consisting of two premises and a conclusion, each containing a subject, copula, and predicate. Aristotle's primary logical tool.", category: "Aristotle" },
  { term: "Major Term", definition: "The first premise of a syllogism. It contains both the middle term and the major term of the conclusion. The major term is the predicate of the conclusion.", category: "Aristotle" },
  { term: "Minor Term", definition: "The second premise of a syllogism. It contains both the middle term and the minor term of the conclusion. The minor term is the subject of the conclusion.", category: "Aristotle" },
  { term: "Middle Term", definition: "The term that appears in both the major and minor premises of a syllogism but not in the conclusion. It is the link that connects the major and minor terms, making the conclusion possible.", category: "Aristotle" },
  { term: "Subject", definition: "In a proposition, what the belief is about (e.g., 'Socrates' in 'Socrates is philosophical').", category: "Aristotle" },
  { term: "Copula", definition: "The 'is' in a proposition that links subject to predicate, expressing that the predicate is true of the subject.", category: "Aristotle" },
  { term: "Predicate", definition: "In a proposition, the property or attribute ascribed to the subject (e.g., 'philosophical' in 'Socrates is philosophical').", category: "Aristotle" },
  { term: "Categories of Being", definition: "Aristotle's classification of the basic kinds of being: substance, quantity, quality, relation, place, time, position, state, action, and passion.", category: "Aristotle" },
  { term: "Being as Being", definition: "Aristotle's definition of metaphysics: the study of being insofar as it is being — examining what is common to all things that exist, not just particular kinds.", category: "Aristotle" },
  { term: "Cause to Effect", definition: "Reasoning from a known cause to its effect (a priori reasoning). Starts with what is more knowable in itself.", category: "Aristotle" },
  { term: "Effect to Cause", definition: "Reasoning from an observed effect back to its cause (a posteriori reasoning). Especially valuable in metaphysics because we often encounter effects before their causes.", category: "Aristotle" },

  // Thomistic Metaphysics — Properties & Principles of Being
  { term: "Being (Ens)", definition: "That which is, or that which has existence. Being is the subject of metaphysics — the most fundamental and universal concept. It is not univocal (applied in exactly the same sense to everything) but analogous: substance is the primary and central meaning of being, and everything else (accidents, relations, etc.) is understood in relation to it. To understand any real thing fully is to understand it as a being — as possessing existence, essence, unity, intelligibility, and goodness.", category: "Thomism" },
  { term: "Hylomorphism", definition: "The Aristotelian-Thomistic doctrine that all material beings are composed of two co-principles: form (morphe) and matter (hyle). Neither can exist alone — form without matter is a pure spirit; matter without form is pure potentiality (prime matter). Together they constitute the full being of a material substance. Hylomorphism explains both what a being IS (form) and that it is THIS particular individual (matter).", category: "Thomism" },
  { term: "Substantial Form", definition: "The intrinsic, active co-principle of a material being that makes it to be THIS kind of being and not another. Form is the principle of intelligibility — it is what two individuals of the same species share, and what allows us to understand a thing under a universal concept. Without substantial form, a being would have no determinate nature and could not be known. Form is an act: it actualizes matter and gives the being its essential identity.", category: "Thomism" },
  { term: "Prime Matter", definition: "The pure passive co-principle of material being — potentiality with no form or determination of its own. Prime matter cannot exist by itself; it is always united to form. As the principle of individuation, it is what distinguishes two beings of the same species (e.g., Socrates and Plato are both human, but are distinct individuals because of their matter). Prime matter is the 'this-ness' of a being; form is the 'what-ness.'", category: "Thomism" },
  { term: "Act (Actus)", definition: "The actuality or perfection of a being — that which a thing IS. Act is the very mode of being a thing possesses right now. Being itself, at its deepest level, is an act: the act of existing (esse). Every being has act as its core: the substantial form is an act that makes the being a certain kind of thing, and existence is the ultimate act that makes the being real at all. Without act, there is simply nothing — potency alone is not yet being.", category: "Thomism" },
  { term: "Potency (Potentia)", definition: "The real capacity within a being for a new mode of being. Potency is always defined in relation to a specific act — it is the openness of a being for further actualization. Potency explains both a being's openness (what it can become) and its closedness (it cannot become just anything — a cat cannot become a dog). Two types: passive potency (capacity to receive determination from outside) and active potency (capacity to act from within). Without potency, change is impossible; without act, potency is nothing.", category: "Thomism" },
  { term: "Passive Potency", definition: "The capacity within a being to receive a new determination from an external agent. The being is acted upon and perfected from without. Ex: Socrates has the passive potency to get a suntan — the sun acts on him. Passive potency is the being's openness to receiving a new act it does not yet possess.", category: "Thomism" },
  { term: "Active Potency", definition: "The capacity within a being to act and produce change from within itself. The being acts outward from its own nature. Ex: Socrates has the active potency to throw a baseball. Active potency flows from what a being already IS — from its act — and is the source of its characteristic operations.", category: "Thomism" },
  { term: "Change", definition: "The transition from one real mode of being to another. Every change requires three elements: (1) a prior terminal state — what the being was; (2) a subsequent terminal state — what the being becomes; and (3) a principle of continuity — the being that persists through the transition, ensuring it is the same being that changed. Change is only intelligible because beings have both act (what they are) and potency (what they can become). Without potency, change is impossible; without act, there is nothing to change.", category: "Thomism" },
  { term: "Principle of Continuity", definition: "In any change, that which persists through the transition from one state to another — the subject that undergoes the change. Without a principle of continuity, there is no real change, only replacement: two disconnected beings rather than one being that has been transformed. The principle of continuity in change is the being's potentiality — it is what remains throughout and connects the before and after.", category: "Thomism" },
  { term: "Substance", definition: "The primary and central meaning of being — a being that exists in itself and not in another. Aristotle called substance the 'focal meaning of being': everything else (accidents, relations, quantities) is understood by reference to substance. A substance is what we mean when we say something truly EXISTS. Substance has the most fundamental existence and identity: it is what underlies all change and supports all properties.", category: "Thomism" },
  { term: "Accident", definition: "A being that exists in another (in a substance) — a qualification or determination of a substance. Accidents are understood entirely in relation to the substance they modify. A substance can exist without any particular accident; no accident can exist without a substance. The nine categories of accident (quantity, quality, relation, place, time, etc.) are the nine ways a substance can be further determined beyond its essential nature.", category: "Thomism" },
  { term: "Real Being", definition: "That which exists independently of the mind — it has actual existence in the world (e.g., a tree, a person, an electron). Real being is the primary subject of metaphysics. Key criterion: real being has causal power — it can act upon and be acted upon by other things. Contrasted with mental being, which exists only in thought.", category: "Thomism" },
  { term: "Mental Being (Ens Rationis)", definition: "That which exists only in the mind — it has no existence outside of thought (e.g., a unicorn, a logical relation, negation). Mental beings are real as objects of thought, but they do not have causal power in the world. Key criterion distinguishing it from real being: it cannot act or be acted upon.", category: "Thomism" },
  { term: "Principle of Non-Contradiction", definition: "A thing cannot both be and not be in the same respect at the same time. This is the first and most fundamental principle of all metaphysics — it is grounded in being itself. To deny it is to destroy the very concept of being: if a thing could both be and not be, there would be no determinate beings at all.", category: "Thomism" },
  { term: "Principle of Intelligibility", definition: "All being is intelligible — capable of being known by the intellect. This principle is grounded in being itself: because a being has a determinate nature (essence and form), it can be grasped by the mind. The drive to know demands this principle as its complement: if being were not inherently intelligible, the drive to know would be futile.", category: "Thomism" },
  { term: "Drive to Know", definition: "The innate human orientation toward understanding reality. This drive is not merely psychological — it makes a metaphysical claim: that reality is knowable. It demands the complementary principle of the intelligibility of being. If being were not intelligible, the drive to know would be a fundamental absurdity.", category: "Thomism" },
  { term: "Intrinsic Unity", definition: "A necessary property of every real being — unity that belongs to a being by its very nature. To be real IS to be one: a being is an undivided whole. Unity is convertible with being: every substantially existing thing has substantial unity, and everything with substantial unity substantially exists. Intrinsic unity arises from form unifying matter into a single 'this.' If a thing had no unity at any level, it could not be a being at all.", category: "Thomism" },
  { term: "Extrinsic Unity", definition: "Unity imposed from outside by an observer or external force — the parts do not form a genuine whole. Ex: a pile of rocks, an army, a library. Extrinsic unity is NOT the unity of a real being, because it does not arise from the being's own nature or form. This distinction is crucial: only intrinsic unity constitutes real being.", category: "Thomism" },
  { term: "Transcendentals", definition: "Properties co-extensive with being itself, transcending every category: one, true, and good. They are not additions to being but being understood from different angles. 'One' (unum) — every being is undivided in itself; 'True' (verum) — every being is intelligible to a mind; 'Good' (bonum) — every being is ordered toward its own fulfillment and is desirable. Because they are convertible with being, wherever there is being, there are these properties.", category: "Thomism" },
  { term: "Principle of Individuation", definition: "What makes one individual distinct from another of the same species. In Thomism, this is designated (signate) matter — the particular portion of matter that belongs to this being. Form alone cannot individuate (two identical forms would be numerically the same thing), so matter is required to make Socrates THIS man and not Plato. This is why purely immaterial beings (angels) are each their own species.", category: "Thomism" },
  { term: "Essence (Essentia)", definition: "What a thing is — its quiddity or 'whatness.' Essence is the intelligible structure of a being: what makes it this KIND of being and what allows it to be defined. In material beings, essence is composed of form and matter together. Essence limits and determines existence: it is the 'receptacle' that receives the act of being. In creatures, essence and existence are really distinct — the essence does not contain its own existence.", category: "Thomism" },
  { term: "Existence / Act of Being (Esse)", definition: "That a thing IS — the deepest and most fundamental act of a being. For Aquinas, existence (esse) is the actus essendi, the act of acts: it is what makes a being real rather than merely possible. Essence determines WHAT a being is; existence makes it actually BE. All other acts (form, accidental determinations) presuppose existence. In God alone are essence and existence identical — God does not receive existence but IS existence itself.", category: "Thomism" },
  { term: "Real Distinction of Essence and Existence", definition: "In all creatures, essence (what a thing is) and existence (that it is) are really — not merely conceptually — distinct. A creature's essence does not include existence: a dog's nature does not guarantee that any dog exists. Existence must be received from outside the essence, ultimately from God who IS existence. This real distinction is why creatures are contingent (they could not-be) and why only God is necessary being. It is a cornerstone of Thomistic metaphysics and the basis of the cosmological argument.", category: "Thomism" },
  { term: "Action / Operation (Actio)", definition: "The activity that flows necessarily from a being's nature — an essential property of being. Action reveals what a being IS: by observing how something acts, we know what it is. This is grounded in the principle 'agere sequitur esse' (operation follows being). Action is not merely something a being does — it is an expression of its being. A being that performs no action at all would be wholly inert and effectively non-being. Action is therefore a principle by which being is known and manifested.", category: "Thomism" },
  { term: "Agere Sequitur Esse", definition: "'Operation follows being' — a being acts in accordance with what it is. The way a thing acts is proportioned to the kind of being it is: a plant grows and reproduces; an animal senses and moves; a human reasons and wills. Action is not accidental to a being but flows from its essence and act. This principle allows us to reason from effect to cause: by observing a being's characteristic operations, we can infer its nature.", category: "Thomism" },

  // First Principles & Laws of Logic
  { term: "Principle of Identity", definition: "A being is what it is: A is A. Every being is identical with itself. The most fundamental logical law, presupposed by all thought and predication.", category: "First Principles" },
  { term: "Principle of Non-Contradiction (Logic)", definition: "A proposition cannot be both true and false at the same time and in the same respect. The logical formulation of the metaphysical principle that a thing cannot both be and not-be.", category: "First Principles" },
  { term: "Principle of Excluded Middle", definition: "Between being and non-being there is no middle ground — a thing either is or it is not. Every proposition is either true or false; there is no third option.", category: "First Principles" },
  { term: "Principle of Sufficient Reason", definition: "Everything that exists has a sufficient reason or explanation for its existence and for being what it is. Nothing exists without a reason. Grounding for all causal and metaphysical inquiry.", category: "First Principles" },
  { term: "Principle of Causality", definition: "Every effect has a cause. Nothing comes from nothing (ex nihilo nihil fit). A being that does not have existence of itself must receive it from another — foundational to the cosmological argument.", category: "First Principles" },

  // Concepts & Logic
  { term: "Univocal Concept", definition: "A concept applied to different things in exactly the same sense (e.g., 'animal' applied to a dog and a cat).", category: "Concepts" },
  { term: "Equivocal Concept", definition: "A word applied to different things in completely different senses (e.g., 'bank' as riverbank vs. financial bank).", category: "Concepts" },
  { term: "Analogous Concept", definition: "A concept applied to different things in partly the same and partly different senses (e.g., 'healthy' applied to a person, food, and complexion).", category: "Concepts" },
  { term: "Extrinsic Attribution", definition: "A type of analogy where one primary meaning is associated with the analogous term and all other meanings are derived from that primary analogate through an extrinsic causal relation. The derivative uses of the word don't intrinsically possess the quality — they gain their meaning by being causally related to the primary analogate. Ex: 'Socrates is healthy' vs. 'Socrates' food is healthy' — the food is not intrinsically healthy, but is called healthy because of its causal relation to Socrates' health.", category: "Concepts" },
  { term: "Analogy of Proportionality", definition: "An intrinsic type of analogy where a term is predicated of several subjects to demonstrate a proportional similarity between them. Each subject properly and intrinsically possesses the analogous quality, but in its own way. Ex: 'The fox knows' and 'The man knows' — both intrinsically know, but they know differently. The similarity is captured in the context of the activities associated with each subject.", category: "Concepts" },
  { term: "Analogy of Proper Proportionality", definition: "A refined form of the analogy of proportionality that rules out metaphorical predications — only literally true predications qualify. Ex: 'God is a rock' is metaphorical and does not count; 'the man knows' and 'the fox knows' are both literally true. Unlike univocal concepts, you cannot abstract a single common notion — you can only grasp the proportional relationship between how each subject possesses the quality.", category: "Concepts" },
  { term: "Intentional Definition", definition: "Defines what all things called by a term have in common — captures the essence (e.g., 'virtue is a stable disposition toward the good').", category: "Concepts" },
  { term: "Extensional Definition", definition: "Defines by listing examples of things the term applies to (e.g., 'virtues include courage, temperance, justice').", category: "Concepts" },
  { term: "Genus and Specific Difference", definition: "A method of definition: start with a broad category (genus) and narrow it with distinguishing features (specific difference).", category: "Concepts" },

  // Philosophical Positions
  { term: "Radical Monism", definition: "The view that reality is fundamentally one — all apparent plurality is illusion (e.g., Parmenides).", category: "Positions" },
  { term: "Mitigated Monism", definition: "The view that reality is fundamentally one but allows for some genuine plurality within that unity.", category: "Positions" },
  { term: "Radical Pluralism", definition: "The view that reality consists entirely of many separate, independent things with no underlying unity.", category: "Positions" },
  { term: "Materialistic Reductionism", definition: "The view that all reality can be reduced to material components. Overlooks formal causality, intrinsic unity, and the immaterial aspects of real beings.", category: "Positions" },
  { term: "Eliminativism", definition: "The view that certain common-sense entities (like minds or consciousness) don't really exist. Aristotle would say this fails to 'save the appearances.'", category: "Positions" },
  { term: "Sphere Land", definition: "A thought experiment showing that identical forms (spheres) require something besides form to be distinct individuals — pointing to the need for prime matter as principle of individuation.", category: "Positions" },
];

export const categories = [...new Set(glossary.map((g) => g.category))];
