export const keyPoints: Record<number, string[]> = {
  1: [
    "Identify all four divisions: Eikasia (illusion), Pistis (belief), Dianoia (mathematical reasoning), Noesis (pure intelligence)",
    "Explain the visible realm (eikasia + pistis) produces opinion (doxa)",
    "Explain the intelligible realm (dianoia + noesis) produces knowledge (episteme)",
    "Show the relationship: each section is progressively closer to truth/reality",
    "Map Cave stages to Divided Line: shadows = eikasia, physical objects = pistis, mathematical forms = dianoia, the Good/sun = noesis",
    "Explain the freed slave's journey as ascending the Divided Line",
  ],
  2: [
    "Define the realm of Forms: eternal, unchanging, perfect archetypes",
    "Define the realm of copies: material world of imperfect, changing things",
    "Explain Forms are accessible through mind/reason, not senses",
    "Physical things participate in or imitate the Forms",
    "The Cave shows prisoners mistaking copies (shadows) for reality",
    "True understanding requires turning toward the Forms (leaving the cave)",
  ],
  3: [
    "Choose a compelling reason for metaphysics' importance (e.g., provides consistency of language/concepts, inescapable worldview, intrinsic value of rational pursuit)",
    "Present a genuine critique of that reason",
    "Strengthen the original argument to deflect the critique",
    "Engage with Hume's objection and its self-refuting nature",
    "Address the abstract/impractical objection",
  ],
  4: [
    "Plato's approach: doctrine-focused, positing the Forms as separate realities",
    "Aristotle's approach: method-focused, saving the appearances, grounded in experience",
    "Plato reasons from abstract Forms down to particulars",
    "Aristotle reasons from observable experience up to principles",
    "Contrast doctrine (what they believed) vs. method (how they investigated)",
    "Note Aristotle's three major criticisms of Plato",
  ],
  5: [
    "Define syllogism: two premises and a conclusion",
    "Identify subject, copula, predicate in each proposition",
    "Show understanding of quantity (universal/particular/singular) and quality (affirmative/negative)",
    "Present a valid syllogistic form (e.g., Barbara: All M is P, All S is M, Therefore All S is P)",
    "Demonstrate the argument is valid by its form",
  ],
  6: [
    "Criticism 1: The Third Man argument — if Forms explain similarity, what explains similarity between a thing and its Form?",
    "Criticism 2: Forms are explanatorily unnecessary — they don't help explain change in the physical world",
    "Criticism 3: The separation problem — how do separated Forms interact with physical things?",
    "Offer Plato's possible defense for at least one criticism",
    "Show engagement with the philosophical reasoning on both sides",
  ],
  7: [
    "Define cause-to-effect reasoning (a priori): starting from known cause, deducing what follows",
    "Define effect-to-cause reasoning (a posteriori): starting from observed effects, reasoning back to cause",
    "Explain in accessible, non-technical language",
    "Give a concrete example of each type",
    "Explain why effect-to-cause is special in metaphysics: we encounter effects first in experience",
  ],
  8: [
    "Being as being: studying what is common to all things that exist, not just particular kinds",
    "Metaphysics as wisdom: the highest form of knowledge, dealing with ultimate causes and principles",
    "Connect to Aristotle's view that this is the most universal and fundamental science",
    "Relate to Catholic theology: both seek ultimate truths about reality",
    "Note differences: metaphysics uses reason alone, theology also draws on revelation",
  ],
  9: [
    "Principle 1: Law of Non-Contradiction — a thing cannot be and not be in the same respect at the same time",
    "Principle 2: Principle of Sufficient Reason / Intelligibility of Being",
    "Explain how all metaphysical reasoning depends on these",
    "Discuss their relationship to each other (metaphysical, not theological response)",
    "Non-contradiction is the foundation of all rational thought",
  ],
  10: [
    "The drive to know is an innate human orientation toward understanding",
    "If being were not intelligible, the drive to know would be in vain",
    "This must be true of all being — otherwise some reality is permanently unknowable",
    "Evidence: the success of science, philosophy, everyday reasoning",
    "Can be proven by showing the self-defeating nature of denying intelligibility",
  ],
  11: [
    "Real being: exists independently of the mind (trees, persons, atoms)",
    "Mental being (ens rationis): exists only in the mind (unicorns, logical relations, negations)",
    "Provide clear examples of each",
    "The key criterion: real being has existence outside thought; mental being depends entirely on being thought",
  ],
  12: [
    "Key criterion: independence from the mind",
    "Real being exists whether or not anyone thinks about it",
    "Mental being ceases to exist without a mind thinking it",
    "Explain how this criterion applies to borderline cases",
  ],
  13: [
    "Reflective awareness of 'is': turning attention to the act of existence itself in any being",
    "This requires moving beyond what a thing is to that it is",
    "Not all metaphysical systems agree — some focus on essence over existence",
    "Thomistic metaphysics uniquely emphasizes actual existence (esse) as the core of real being",
    "Contrast with systems that prioritize essence, form, or consciousness",
  ],
  14: [
    "Univocal: same meaning applied to different things (e.g., 'animal' for dog and cat)",
    "Equivocal: completely different meanings for the same word (e.g., 'bank')",
    "Analogous: partly same, partly different meaning (e.g., 'healthy' for person, food, complexion)",
    "Metaphysics must use analogous concepts because being is said of many things in related but different ways",
    "Analogy of proper proportionality: each thing has being in its own intrinsic proportion",
  ],
  15: [
    "Every being must be one (unified) because a being that is not one is not a being at all",
    "To be is to be one — division destroys the being",
    "Unity is a transcendental property convertible with being",
    "A being divided into parts is no longer that being but becomes many beings",
  ],
  16: [
    "Intrinsic unity: parts form a genuine whole by nature (e.g., a living organism)",
    "Extrinsic unity: parts grouped together externally (e.g., a pile of rocks, an army)",
    "Criterion: whether the unity comes from within the being's nature or is imposed from outside",
    "The universe: argue whether it is intrinsic or extrinsic unity with reasoning",
    "Provide clear examples of each type",
  ],
  17: [
    "Materialistic reductionism: all reality reduces to material components",
    "Overlooks formal causality — what makes a thing the kind of thing it is",
    "Overlooks intrinsic unity — a whole is more than the sum of its parts",
    "Overlooks immaterial aspects of real beings (form, act, intelligibility)",
    "Fails to account for qualities like consciousness, meaning, purpose",
  ],
  18: [
    "Radical Monism: reality is fundamentally one, all plurality is illusion",
    "Mitigated Monism: reality is fundamentally one but allows some genuine plurality",
    "Radical Pluralism: reality is only many, no underlying unity",
    "Participation doctrines: things share in being to different degrees",
    "Thomistic view: real distinction of essence and existence, participation in being",
    "Explain why Thomism draws its specific conclusions",
  ],
  19: [
    "The one and many are both evident in experience",
    "Denying unity leads to incoherence — you can't even make a claim without unity",
    "Denying plurality contradicts obvious experience of distinct things",
    "Both are needed for an adequate account of reality",
    "Show philosophical consequences of dropping either one",
  ],
  20: [
    "Neither essential form nor prime matter can exist by itself",
    "They are co-principles — each requires the other to constitute a material being",
    "Science discovers formed matter, not pure form or pure matter separately",
    "Prime matter has no properties of its own — it cannot be isolated",
    "Form without matter would be a separate substance (angelic, not material)",
  ],
  21: [
    "Sphere Land: imagine a world of identical spheres — same form, same properties",
    "What makes one sphere distinct from another if they share the same form?",
    "There must be something besides form that individuates — this is prime matter",
    "Prime matter as the principle of individuation: what makes two things of the same kind numerically distinct",
  ],
  22: [
    "Lower elements (atoms, molecules, etc.) are virtually present in higher beings",
    "The substantial form of the whole (e.g., a dog) organizes all lower levels",
    "Lower elements don't exist as independent substances within the whole",
    "They are present in potency, able to be released if the whole is destroyed",
    "Thomistic view preserves the unity of the organism while acknowledging material composition",
  ],
  23: [
    "Potency explains openness: a being can receive new perfections it doesn't yet have",
    "Potency explains closedness: a being can only change in ways its nature allows",
    "A dog can grow but cannot become a rock — its potency has limits",
    "The specific potencies of a thing are determined by its nature/form",
    "Potency is both receptive (open) and limited (closed)",
  ],
  24: [
    "Empiricism limits knowledge to what is directly observable/measurable",
    "Potency is not directly observable — it is a real but non-actual feature of being",
    "Without potency, empiricists cannot adequately explain change or possibility",
    "Negative consequences: cannot explain why things change, develop, or have capacities",
    "Contemporary science implicitly relies on potency (quantum states, chemical bonds, etc.)",
  ],
  25: [
    "Act relates to substance: substance is the primary act of a being",
    "Potency relates to accident: accidents actualize potencies of a substance",
    "Substance is act in the order of essence; accidents are further actualizations",
    "A substance has the potency to receive various accidents",
    "Act/potency is the more fundamental pair; substance/accident is one application of it",
  ],
  26: [
    "List Aristotle's categories: substance, quantity, quality, relation, place, time, position, state, action, passion",
    "Substance is the primary category — all others depend on it",
    "Categories organize our understanding of what kinds of being there are",
    "Important for metaphysics: provides a systematic framework for analyzing reality",
    "Without categories, metaphysical analysis would be vague and disorganized",
  ],
};
