// Baltimore Catechism No. 2 — full text, 1885/1941 edition ("A Catechism of
// Christian Doctrine... Prepared and Enjoined by Order of The Third Plenary
// Council of Baltimore"). Public domain (pre-1928 US publication) — this is
// the real, complete book, not a paraphrase, since there's no copyright
// question at all. Sourced 2026-08-20 from a real scanned copy
// (fisheaters.com/baltimorecatechism2.pdf), cross-checked question-by-
// question against RCA's own Religion 6 pacing doc (src/lib/rca-content/
// religion-6.ts cites e.g. "Lesson 15 #188-189, 191-192, & 197") — the QUESTION
// NUMBERS match exactly; RCA's own "Lesson 15" label is RCA's internal
// multi-year pacing sequence, not this book's own "Lesson Seventeenth" etc.,
// so this file is organized by the book's real lesson titles/numbers and by
// question number, and the Religion 6 UI cross-references by question number.
export type CatechismQA = { n: number; q: string; a: string };
export type CatechismLesson = { lesson: number; title: string; questions: CatechismQA[] };

export const baltimoreCatechism2: CatechismLesson[] = [
  {
    lesson: 1,
    title: "On the End of Man",
    questions: [
      { n: 1, q: "Who made the world?", a: "God made the world." },
      { n: 2, q: "Who is God?", a: "God is the Creator of heaven and earth, and of all things." },
      { n: 3, q: "What is man?", a: "Man is a creature composed of body and soul, and made to the image and likeness of God." },
      { n: 4, q: "Is this likeness in the body or in the soul?", a: "This likeness is chiefly in the soul." },
      { n: 5, q: "How is the soul like to God?", a: "The soul is like God because it is a spirit that will never die, and has understanding and free will." },
      { n: 6, q: "Why did God make you?", a: "God made me to know Him, to love Him, and to serve Him in this world, and to be happy with Him forever in the next." },
      { n: 7, q: "Of which must we take more care, our soul or our body?", a: "We must take more care of our soul than of our body." },
      { n: 8, q: "Why must we take more care of our soul than of our body?", a: "We must take more care of our soul than of our body, because in losing our soul we lose God and everlasting happiness." },
      { n: 9, q: "What must we do to save our souls?", a: "To save our souls we must worship God by faith, hope, and charity; that is, we must believe in Him, hope in Him, and love Him with all our heart." },
      { n: 10, q: "How shall we know the things which we are to believe?", a: "We shall know the things which we are to believe from the Catholic Church, through which God speaks to us." },
      { n: 11, q: "Where shall we find the chief truths which the Church teaches?", a: "We shall find the chief truths which the Church teaches in the Apostles' Creed." },
      { n: 12, q: "Say the Apostles' Creed.", a: "I believe in God, the Father Almighty, Creator of heaven and earth; and in Jesus Christ, His only Son, our Lord; who was conceived by the Holy Ghost, born of the Virgin Mary, suffered under Pontius Pilate, was crucified; died, and was buried. He descended into hell: the third day He arose again from the dead: He ascended into heaven, and sitteth at the right hand of God, the Father Almighty; from thence He shall come to judge the living and the dead. I believe in the Holy Ghost, the Holy Catholic Church, the communion of Saints, the forgiveness of sins, the resurrection of the body, and the life everlasting. Amen." },
    ],
  },
  {
    lesson: 2,
    title: "On God and His Perfections",
    questions: [
      { n: 13, q: "What is God?", a: "God is a spirit infinitely perfect." },
      { n: 14, q: "Had God a beginning?", a: "God had no beginning; He always was and He always will be." },
      { n: 15, q: "Where is God?", a: "God is everywhere." },
      { n: 16, q: "If God is everywhere, why do we not see Him?", a: "We do not see God, because He is a pure spirit and cannot be seen with bodily eyes." },
      { n: 17, q: "Does God see us?", a: "God sees us and watches over us." },
      { n: 18, q: "Does God know all things?", a: "God knows all things, even our most secret thoughts, words, and actions." },
      { n: 19, q: "Can God do all things?", a: "God can do all things, and nothing is hard or impossible to Him." },
      { n: 20, q: "Is God just, holy, and merciful?", a: "God is all just, all holy, all merciful, as He is infinitely perfect." },
    ],
  },
  {
    lesson: 3,
    title: "On the Unity and Trinity of God",
    questions: [
      { n: 21, q: "Is there but one God?", a: "Yes; there is but one God." },
      { n: 22, q: "Why can there be but one God?", a: "There can be but one God, because God, being supreme and infinite, cannot have an equal." },
      { n: 23, q: "How many Persons are there in God?", a: "In God there are three Divine Persons, really distinct, and equal in all things--the Father, the Son, and the Holy Ghost." },
      { n: 24, q: "Is the Father God?", a: "The Father is God and the first Person of the Blessed Trinity." },
      { n: 25, q: "Is the Son God?", a: "The Son is God and the second Person of the Blessed Trinity." },
      { n: 26, q: "Is the Holy Ghost God?", a: "The Holy Ghost is God and the third Person of the Blessed Trinity." },
      { n: 27, q: "What do you mean by the Blessed Trinity?", a: "By the Blessed Trinity I mean one God in three Divine Persons." },
      { n: 28, q: "Are the three Divine Persons equal in all things?", a: "The three Divine Persons are equal in all things." },
      { n: 29, q: "Are the three Divine Persons one and the same God?", a: "The three Divine Persons are one and the same God, having one and the same Divine nature and substance." },
      { n: 30, q: "Can we fully understand how the three Divine Persons are one and the same God?", a: "We cannot fully understand how the three Divine Persons are one and the same God, because this is a mystery." },
      { n: 31, q: "What is a mystery?", a: "A mystery is a truth which we cannot fully understand." },
    ],
  },
  {
    lesson: 4,
    title: "On Creation",
    questions: [
      { n: 32, q: "Who created heaven and earth, and all things?", a: "God created heaven and earth, and all things." },
      { n: 33, q: "How did God create heaven and earth?", a: "God created heaven and earth from nothing by His word only; that is, by a single act of His all-powerful will." },
      { n: 34, q: "Which are the chief creatures of God?", a: "The chief creatures of God are angels and men." },
      { n: 35, q: "What are angels?", a: "Angels are pure spirits without a body, created to adore and enjoy God in heaven." },
      { n: 36, q: "Were the angels created for any other purpose?", a: "The angels were also created to assist before the throne of God and to minister unto Him; they have often been sent as messengers from God to man; and are also appointed our guardians." },
      { n: 37, q: "Were the angels, as God created them, good and happy?", a: "The angels, as God created them, were good and happy." },
      { n: 38, q: "Did all the angels remain good and happy?", a: "All the angels did not remain good and happy; many of them sinned and were cast into hell, and these are called devils or bad angels." },
    ],
  },
  {
    lesson: 5,
    title: "On Our First Parents and the Fall",
    questions: [
      { n: 39, q: "Who were the first man and woman?", a: "The first man and woman were Adam and Eve." },
      { n: 40, q: "Were Adam and Eve innocent and holy when they came from the hand of God?", a: "Adam and Eve were innocent and holy when they came from the hand of God." },
      { n: 41, q: "Did God give any command to Adam and Eve?", a: "To try their obedience God commanded Adam and Eve not to eat of a certain fruit which grew in the garden of Paradise." },
      { n: 42, q: "Which were the chief blessings intended for Adam and Eve had they remained faithful to God?", a: "The chief blessings intended for Adam and Eve, had they remained faithful to God, were a constant state of happiness in this life and everlasting glory in the next." },
      { n: 43, q: "Did Adam and Eve remain faithful to God?", a: "Adam and Eve did not remain faithful to God; but broke His command by eating the forbidden fruit." },
      { n: 44, q: "What befell Adam and Eve on account of their sin?", a: "Adam and Eve, on account of their sin, lost innocence and holiness, and were doomed to sickness and death." },
      { n: 45, q: "What evil befell us on account of the disobedience of our first parents?", a: "On account of the disobedience of our first parents, we all share in their sin and punishment, as we should have shared in their happiness if they had remained faithful." },
      { n: 46, q: "What other effects followed from the sin of our first parents?", a: "Our nature was corrupted by the sin of our first parents, which darkened our understanding, weakened our will, and left in us a strong inclination to evil." },
      { n: 47, q: "What is the sin called which we inherit from our first parents?", a: "The sin which we inherit from our first parents is called original sin." },
      { n: 48, q: "Why is this sin called original?", a: "This sin is called original because it comes down to us from our first parents, and we are brought into the world with its guilt on our soul." },
      { n: 49, q: "Does this corruption of our nature remain in us after original sin is forgiven?", a: "This corruption of our nature and other punishments remain in us after original sin is forgiven." },
      { n: 50, q: "Was any one ever preserved from original sin?", a: "The Blessed Virgin Mary, through the merits of her Divine Son, was preserved free from the guilt of original sin, and this privilege is called her Immaculate Conception." },
    ],
  },
  {
    lesson: 6,
    title: "On Sin and Its Kinds",
    questions: [
      { n: 51, q: "Is original sin the only kind of sin?", a: "Original sin is not the only kind of sin; there is another kind of sin, which we commit ourselves, called actual sin." },
      { n: 52, q: "What is actual sin?", a: "Actual sin is any wilful thought, word, deed, or omission contrary to the law of God." },
      { n: 53, q: "How many kinds of actual sin are there?", a: "There are two kinds of actual sin--mortal and venial." },
      { n: 54, q: "What is mortal sin?", a: "Mortal sin is a grievous offense against the law of God." },
      { n: 55, q: "Why is this sin called mortal?", a: "This sin is called mortal because it deprives us of spiritual life, which is sanctifying grace, and brings everlasting death and damnation on the soul." },
      { n: 56, q: "How many things are necessary to make a sin mortal?", a: "To make a sin mortal three things are necessary: a grievous matter, sufficient reflection, and full consent of the will." },
      { n: 57, q: "What is venial sin?", a: "Venial sin is a slight offense against the law of God in matters of less importance, or in matters of great importance it is an offense committed without sufficient reflection or full consent of the will." },
      { n: 58, q: "Which are the effects of venial sin?", a: "The effects of venial sin are the lessening of the love of God in our heart, the making us less worthy of His help, and the weakening of the power to resist mortal sin." },
      { n: 59, q: "Which are the chief sources of sin?", a: "The chief sources of sin are seven: Pride, Covetousness, Lust, Anger, Gluttony, Envy, and Sloth; and they are commonly called capital sins." },
    ],
  },
  {
    lesson: 7,
    title: "On the Incarnation and Redemption",
    questions: [
      { n: 60, q: "Did God abandon man after he fell into sin?", a: "God did not abandon man after he fell into sin, but promised him a Redeemer, who was to satisfy for man's sin and reopen to him the gates of heaven." },
      { n: 61, q: "Who is the Redeemer?", a: "Our Blessed Lord and Saviour Jesus Christ is the Redeemer of mankind." },
      { n: 62, q: "What do you believe of Jesus Christ?", a: "I believe that Jesus Christ is the Son of God, the second Person of the Blessed Trinity, true God and true man." },
      { n: 63, q: "Why is Jesus Christ true God?", a: "Jesus Christ is true God because He is the true and only Son of God the Father." },
      { n: 64, q: "Why is Jesus Christ true man?", a: "Jesus Christ is true man because He is the Son of the Blessed Virgin Mary and has a body and soul like ours." },
      { n: 65, q: "How many natures are there in Jesus Christ?", a: "In Jesus Christ there are two natures, the nature of God and the nature of man." },
      { n: 66, q: "Is Jesus Christ more than one person?", a: "No, Jesus Christ is but one Divine Person." },
      { n: 67, q: "Was Jesus Christ always God?", a: "Jesus Christ was always God, as He is the second Person of the Blessed Trinity, equal to His Father from all eternity." },
      { n: 68, q: "Was Jesus Christ always man?", a: "Jesus Christ was not always man, but became man at the time of His Incarnation." },
      { n: 69, q: "What do you mean by the Incarnation?", a: "By the Incarnation I mean that the Son of God was made man." },
      { n: 70, q: "How was the Son of God made man?", a: "The Son of God was conceived and made man by the power of the Holy Ghost, in the womb of the Blessed Virgin Mary." },
      { n: 71, q: "Is the Blessed Virgin Mary truly the Mother of God?", a: "The Blessed Virgin Mary is truly the Mother of God, because the same Divine Person who is the Son of God is also the Son of the Blessed Virgin Mary." },
      { n: 72, q: "Did the Son of God become man immediately after the sin of our first parents?", a: "The Son of God did not become man immediately after the sin of our first parents, but was promised to them as a Redeemer." },
      { n: 73, q: "How could they be saved who lived before the Son of God became man?", a: "They who lived before the Son of God became man could be saved by believing in a Redeemer to come, and by keeping the commandments." },
      { n: 74, q: "On what day was the Son of God conceived and made man?", a: "The Son of God was conceived and made man on Annunciation day--the day on which the Angel Gabriel announced to the Blessed Virgin Mary that she was to be the Mother of God." },
      { n: 75, q: "On what day was Christ born?", a: "Christ was born on Christmas day in a stable at Bethlehem, over nineteen hundred years ago." },
      { n: 76, q: "How long did Christ live on earth?", a: "Christ lived on earth about thirty-three years, and led a most holy life in poverty and suffering." },
      { n: 77, q: "Why did Christ live so long on earth?", a: "Christ lived so long on earth to show us the way to heaven by His teachings and example." },
    ],
  },
  {
    lesson: 8,
    title: "On Our Lord's Passion, Death, Resurrection, and Ascension",
    questions: [
      { n: 78, q: "What did Jesus Christ suffer?", a: "Jesus Christ suffered a bloody sweat, a cruel scourging, was crowned with thorns, and was crucified." },
      { n: 79, q: "On what day did Christ die?", a: "Christ died on Good Friday." },
      { n: 80, q: "Why do you call that day \"good\" on which Christ died so sorrowful a death?", a: "We call that day \"good\" on which Christ died because by His death He showed His great love for man, and purchased for him every blessing." },
      { n: 81, q: "Where did Christ die?", a: "Christ died on Mount Calvary." },
      { n: 82, q: "How did Christ die?", a: "Christ was nailed to the Cross and died on it between two thieves." },
      { n: 83, q: "Why did Christ suffer and die?", a: "Christ suffered and died for our sins." },
      { n: 84, q: "What lessons do we learn from the sufferings and death of Christ?", a: "From the sufferings and death of Christ we learn the great evil of sin, the hatred God bears to it, and the necessity of satisfying for it." },
      { n: 85, q: "Where did Christ's soul go after His death?", a: "After Christ's death His soul descended into hell." },
      { n: 86, q: "Did Christ's soul descend into the hell of the damned?", a: "The hell into which Christ's soul descended was not the hell of the damned, but a place or state of rest called Limbo, where the souls of the just were waiting for Him." },
      { n: 87, q: "Why did Christ descend into Limbo?", a: "Christ descended into Limbo to preach to the souls who were in prison--that is, to announce to them the joyful tidings of their redemption." },
      { n: 88, q: "Where was Christ's body while His soul was in Limbo?", a: "While Christ's soul was in Limbo His body was in the holy sepulchre." },
      { n: 89, q: "On what day did Christ rise from the dead?", a: "Christ rose from the dead, glorious and immortal, on Easter Sunday, the third day after His death." },
      { n: 90, q: "How long did Christ stay on earth after His resurrection?", a: "Christ stayed on earth forty days after His resurrection to show that He was truly risen from the dead, and to instruct His Apostles." },
      { n: 91, q: "After Christ had remained forty days on earth whither did He go?", a: "After forty days Christ ascended into heaven, and the day on which He ascended into heaven is called Ascension day." },
      { n: 92, q: "Where is Christ in heaven?", a: "In heaven Christ sits at the right hand of God the Father Almighty." },
      { n: 93, q: "What do you mean by saying that Christ sits at the right hand Of God?", a: "When I say that Christ sits at the right hand of God I mean that Christ as God is equal to His Father in all things, and that as man He is in the highest place in heaven next to God." },
    ],
  },
  {
    lesson: 9,
    title: "On the Holy Ghost and His Descent Upon the Apostles",
    questions: [
      { n: 94, q: "Who is the Holy Ghost?", a: "The Holy Ghost is the third Person of the Blessed Trinity." },
      { n: 95, q: "From whom does the Holy Ghost proceed?", a: "The Holy Ghost proceeds from the Father and the Son." },
      { n: 96, q: "Is the Holy Ghost equal to the Father and the Son?", a: "The Holy Ghost is equal to the Father and the Son, being the same Lord and God as They are." },
      { n: 97, q: "On what day did the Holy Ghost come down upon the Apostles?", a: "The Holy Ghost came down upon the Apostles ten days after the Ascension of our Lord; and the day on which He came down upon the Apostles is called Whitsunday, or Pentecost." },
      { n: 98, q: "How did the Holy Ghost come down upon the Apostles?", a: "The Holy Ghost came down upon the Apostles in the form of tongues of fire." },
      { n: 99, q: "Who sent the Holy Ghost upon the Apostles?", a: "Our Lord Jesus Christ sent the Holy Ghost upon the Apostles." },
      { n: 100, q: "Why did Christ send the Holy Ghost?", a: "Christ sent the Holy Ghost to sanctify His Church, to enlighten and strengthen the Apostles, and to enable them to preach the Gospel." },
      { n: 101, q: "Will the Holy Ghost abide with the Church forever?", a: "The Holy Ghost will abide with the Church forever, and guide it in the way of holiness and truth." },
    ],
  },
  {
    lesson: 10,
    title: "On the Effects of the Redemption",
    questions: [
      { n: 102, q: "Which are the chief effects of the Redemption?", a: "The chief effects of the Redemption are two: The satisfaction of God's justice by Christ's sufferings and death, and the gaining of grace for men." },
      { n: 103, q: "What do you mean by grace?", a: "By grace I mean a supernatural gift of God bestowed on us, through the merits of Jesus Christ, for our salvation." },
      { n: 104, q: "How many kinds of grace are there?", a: "There are two kinds of grace, sanctifying grace and actual grace." },
      { n: 105, q: "What is sanctifying grace?", a: "Sanctifying grace is that grace which makes the soul holy and pleasing to God." },
      { n: 106, q: "What do you call those graces or gifts of God by which we believe in Him, hope in Him, and love Him?", a: "Those graces or gifts of God by which we believe in Him, and hope in Him, and love Him, are called the Divine virtues of Faith, Hope, and Charity." },
      { n: 107, q: "What is Faith?", a: "Faith is a Divine virtue by which we firmly believe the truths which God has revealed." },
      { n: 108, q: "What is Hope?", a: "Hope is a Divine virtue by which we firmly trust that God will give us eternal life and the means to obtain it." },
      { n: 109, q: "What is Charity?", a: "Charity is a Divine virtue by which we love God above all things for His own sake, and our neighbor as ourselves for the love of God." },
      { n: 110, q: "What is actual grace?", a: "Actual grace is that help of God which enlightens our mind and moves our will to shun evil and do good." },
      { n: 111, q: "Is grace necessary to salvation?", a: "Grace is necessary to salvation, because without grace we can do nothing to merit heaven." },
      { n: 112, q: "Can we resist the grace of God?", a: "We can and unfortunately often do resist the grace of God." },
      { n: 113, q: "What is the grace of perseverance?", a: "The grace of perseverance is a particular gift of God which enables us to continue in the state of grace till death." },
    ],
  },
  {
    lesson: 11,
    title: "On the Church",
    questions: [
      { n: 114, q: "Which are the means instituted by our Lord to enable men at all times to share in the fruits of the Redemption?", a: "The means instituted by our Lord to enable men at all times to share in the fruits of His Redemption are the Church and the Sacraments." },
      { n: 115, q: "What is the Church?", a: "The Church is the congregation of all those who profess the faith of Christ, partake of the same Sacraments, and are governed by their lawful pastors under one visible head." },
      { n: 116, q: "Who is the invisible Head of the Church?", a: "Jesus Christ is the invisible Head of the Church." },
      { n: 117, q: "Who is the visible Head of the Church?", a: "Our Holy Father the Pope, the Bishop of Rome, is the Vicar of Christ on earth and the visible Head of the Church." },
      { n: 118, q: "Why is the Pope, the Bishop of Rome, the visible Head of the Church?", a: "The Pope, the Bishop of Rome, is the visible Head of the Church because he is the successor of St. Peter, whom Christ made the chief of the Apostles and the visible Head of the Church." },
      { n: 119, q: "Who are the successors of the other Apostles?", a: "The successors of the other Apostles are the bishops of the Holy Catholic Church." },
      { n: 120, q: "Why did Christ found the Church?", a: "Christ founded the Church to teach, govern, sanctify, and save all men." },
      { n: 121, q: "Are all bound to belong to the Church?", a: "All are bound to belong to the Church, and he who knows the Church to be the true Church and remains out of it cannot be saved." },
    ],
  },
  {
    lesson: 12,
    title: "On the Attributes and Marks of the Church",
    questions: [
      { n: 122, q: "Which are the attributes of the Church?", a: "The attributes of the Church are three: authority infallibility, and indefectibility." },
      { n: 123, q: "What do you mean by the authority of the Church?", a: "By the authority of the Church I mean the right and power which the Pope and the bishops, as the successors of the Apostles, have to teach and to govern the faithful." },
      { n: 124, q: "What do you mean by the infallibility of the Church?", a: "By the infallibility of the Church I mean that the Church cannot err when it teaches a doctrine of faith or morals." },
      { n: 125, q: "When does the Church teach infallibly?", a: "The Church teaches infallibly when it speaks through the Pope and the bishops, united in general council, or through the Pope alone when he proclaims to all the faithful a doctrine of faith or morals." },
      { n: 126, q: "What do you mean by the indefectibility of the Church?", a: "By the indefectibility of the Church I mean that the Church, as Christ founded it, will last till the end of time." },
      { n: 127, q: "In whom are these attributes found in their fullness?", a: "These attributes are found in their fullness in the Pope, the visible Head of the Church, whose infallible authority to teach bishops, priests, and people in matters of faith or morals will last till the end of the world." },
      { n: 128, q: "Has the Church any marks by which it may be known?", a: "The Church has four marks by which it may be known: it is One; it is Holy; it is Catholic; it is Apostolic." },
      { n: 129, q: "How is the Church One?", a: "The Church is One because all its members agree in one faith, are all in one communion, and are all under one Head." },
      { n: 130, q: "How is the Church Holy?", a: "The Church is Holy because its founder, Jesus Christ, is holy; because it teaches a holy doctrine; invites all to a holy life; and because of the eminent holiness of so many thousands of its children." },
      { n: 131, q: "How is the Church Catholic or universal?", a: "The Church is Catholic or universal because it subsists in all ages, teaches all nations, and maintains all truth." },
      { n: 132, q: "How is the Church Apostolic?", a: "The Church is Apostolic because it was founded by Christ on His Apostles, and is governed by their lawful successors, and because it has never ceased, and never will cease, to teach their doctrine." },
      { n: 133, q: "In which Church are these attributes and marks found?", a: "These attributes and marks are found in the Holy Roman Catholic Church alone." },
      { n: 134, q: "From whom does the Church derive its undying life and infallible authority?", a: "The Church derives its undying life and infallible authority from the Holy Ghost, the spirit of truth, who abides with it forever." },
      { n: 135, q: "By whom is the Church made and kept One, Holy, and Catholic?", a: "The Church is made and kept One, Holy, and Catholic by the Holy Ghost, the spirit of love and holiness, who unites and sanctifies its members throughout the world." },
    ],
  },
  {
    lesson: 13,
    title: "On the Sacraments in General",
    questions: [
      { n: 136, q: "What is a Sacrament?", a: "A Sacrament is an outward sign instituted by Christ to give grace." },
      { n: 137, q: "How many Sacraments are there?", a: "There are seven Sacraments: Baptism, Confirmation, Holy Eucharist, Penance, Extreme Unction, Holy Orders, and Matrimony." },
      { n: 138, q: "Whence have the Sacraments the power of giving grace?", a: "The Sacraments have the power of giving grace from the merits of Jesus Christ." },
      { n: 139, q: "What grace do the Sacraments give?", a: "Some of the Sacraments give sanctifying grace, and others increase it in our souls." },
      { n: 140, q: "Which are the Sacraments that give sanctifying grace?", a: "The Sacraments that give sanctifying grace are Baptism and Penance; and they are called Sacraments of the dead." },
      { n: 141, q: "Why are Baptism and Penance called Sacraments of the dead?", a: "Baptism and Penance are called Sacraments of the dead, because they take away sin, which is the death of the soul, and give grace, which is its life." },
      { n: 142, q: "Which are the Sacraments that increase sanctifying grace in our soul?", a: "The Sacraments that increase sanctifying grace in our soul are: Confirmation, Holy Eucharist, Extreme Unction, Holy Orders, and Matrimony; and they are called Sacraments of the living." },
      { n: 143, q: "Why are Confirmation, Holy Eucharist, Extreme Unction, Holy Orders, and Matrimony called Sacraments of the living?", a: "Confirmation, Holy Eucharist, Extreme Unction, Holy Orders, and Matrimony are called Sacraments of the living, because those who receive them worthily are already living the life of grace." },
      { n: 144, q: "What sin does he commit who receives the Sacraments of the living in mortal sin?", a: "He who receives the Sacraments of the living in mortal sin commits a sacrilege, which is a great sin, because it is an abuse of a sacred thing." },
      { n: 145, q: "Besides sanctifying grace do the Sacraments give any other grace?", a: "Besides sanctifying grace the Sacraments give another grace, called sacramental." },
      { n: 146, q: "What is sacramental grace?", a: "Sacramental grace is a special help which God gives, to attain the end for which He instituted each Sacrament." },
      { n: 147, q: "Do the Sacraments always give grace?", a: "The Sacraments always give grace, if we receive them with the right dispositions." },
      { n: 148, q: "Can we receive the Sacraments more than once?", a: "We can receive the Sacraments more than once, except Baptism, Confirmation, and Holy Orders." },
      { n: 149, q: "Why can we not receive Baptism, Confirmation, and Holy Orders more than once?", a: "We cannot receive Baptism, Confirmation, and Holy Orders more than once, because they imprint a character in the soul." },
      { n: 150, q: "What is the character which these Sacraments imprint in the soul?", a: "The character which these Sacraments imprint in the soul is a spiritual mark which remains forever." },
      { n: 151, q: "Does this character remain in the soul even after death?", a: "This character remains in the soul even after death: for the honor and glory of those who are saved; for the shame and punishment of those who are lost." },
    ],
  },
  {
    lesson: 14,
    title: "On Baptism",
    questions: [
      { n: 152, q: "What is Baptism?", a: "Baptism is a Sacrament which cleanses us from original sin, makes us Christians, children of God, and heirs of heaven." },
      { n: 153, q: "Are actual sins ever remitted by Baptism?", a: "Actual sins and all the punishment due to them are remitted by Baptism, if the person baptized be guilty of any." },
      { n: 154, q: "Is Baptism necessary to salvation?", a: "Baptism is necessary to salvation, because without it we cannot enter into the kingdom of heaven." },
      { n: 155, q: "Who can administer Baptism?", a: "The priest is the ordinary minister of Baptism; but in case of necessity any one who has the use of reason may baptize." },
      { n: 156, q: "How is Baptism given?", a: "Whoever baptizes should pour water on the head of the person to be baptized, and say, while pouring the water: I baptize thee in the name of the Father, and of the Son, and of the Holy Ghost." },
      { n: 157, q: "How many kinds of Baptism are there?", a: "There are three kinds of Baptism: Baptism of water, of desire, and of blood." },
      { n: 158, q: "What is Baptism of water?", a: "Baptism of water is that which is given by pouring water on the head of the person to be baptized, and saying at the same time: I baptize thee in the name of the Father, and of the Son, and of the Holy Ghost." },
      { n: 159, q: "What is Baptism of desire?", a: "Baptism of desire is an ardent wish to receive Baptism, and to do all that God has ordained for our salvation." },
      { n: 160, q: "What is Baptism of blood?", a: "Baptism of blood is the shedding of one's blood for the faith of Christ." },
      { n: 161, q: "Is Baptism of desire or of blood sufficient to produce the effects of Baptism of water?", a: "Baptism of desire or of blood is sufficient to produce the effects of the Baptism of water, if it is impossible to receive the Baptism of water." },
      { n: 162, q: "What do we promise in Baptism?", a: "In Baptism we promise to renounce the devil with all his works and pomps." },
      { n: 163, q: "Why is the name of a saint given in Baptism?", a: "The name of a saint is given in Baptism in order that the person baptized may imitate his virtues and have him for a protector." },
      { n: 164, q: "Why are godfathers and godmothers given in Baptism?", a: "Godfathers and godmothers are given in Baptism in order that they may promise, in the name of the child, what the child itself would promise if it had the use of reason." },
      { n: 165, q: "What is the obligation of a godfather and a godmother?", a: "The obligation of a godfather and a godmother is to instruct the child in its religious duties, if the parents neglect to do so or die." },
    ],
  },
  {
    lesson: 15,
    title: "On Confirmation",
    questions: [
      { n: 166, q: "What is Confirmation?", a: "Confirmation is a Sacrament through which we receive the Holy Ghost to make us strong and perfect Christians and soldiers of Jesus Christ." },
      { n: 167, q: "Who administers Confirmation?", a: "The bishop is the ordinary minister of Confirmation." },
      { n: 168, q: "How does the bishop give Confirmation?", a: "The bishop extends his hands over those who are to be confirmed, prays that they may receive the Holy Ghost, and anoints the forehead of each with holy chrism in the form of a cross." },
      { n: 169, q: "What is holy chrism?", a: "Holy chrism is a mixture of olive-oil and balm, consecrated by the bishop." },
      { n: 170, q: "What does the bishop say in anointing the person he confirms?", a: "In anointing the person he confirms the bishop says: I sign thee with the sign of the cross, and I confirm thee with the chrism of salvation, in the name of the Father, and of the Son, and of the Holy Ghost." },
      { n: 171, q: "What is meant by anointing the forehead with chrism in the form of a cross?", a: "By anointing the forehead with chrism in the form of a cross is meant, that the Christian who is confirmed must openly profess and practice his faith, never be ashamed of it, and rather die than deny it." },
      { n: 172, q: "Why does the bishop give the person he confirms a slight blow on the cheek?", a: "The bishop gives the person he confirms a slight blow on the cheek, to put him in mind that he must be ready to suffer everything, even death, for the sake of Christ." },
      { n: 173, q: "To receive Confirmation worthily is it necessary to be in the state of grace?", a: "To receive Confirmation worthily it is necessary to be in the state of grace." },
      { n: 174, q: "What special preparation should be made to receive Confirmation?", a: "Persons of an age to learn should know the chief mysteries of faith and the duties of a Christian, and be instructed in the nature and effects of this Sacrament." },
      { n: 175, q: "Is it a sin to neglect Confirmation?", a: "It is a sin to neglect Confirmation, especially in these evil days when faith and morals are exposed to so many and such violent temptations." },
    ],
  },
  {
    lesson: 16,
    title: "On the Gifts and Fruits of the Holy Ghost",
    questions: [
      { n: 176, q: "Which are the effects of Confirmation?", a: "The effects of Confirmation are an increase of sanctifying grace, the strengthening of our faith, and the gifts of the Holy Ghost." },
      { n: 177, q: "Which are the gifts of the Holy Ghost?", a: "The gifts of the Holy Ghost are Wisdom, Understanding, Counsel, Fortitude, Knowledge, Piety and Fear of the Lord." },
      { n: 178, q: "Why do we receive the gift of Fear of the Lord?", a: "We receive the gift of Fear of the Lord to fill us with a dread of sin." },
      { n: 179, q: "Why do we receive the gift of Piety?", a: "We receive the gift of Piety to make us love God as a Father and obey Him because we love Him." },
      { n: 180, q: "Why do we receive the gift of Knowledge?", a: "We receive the gift of Knowledge to enable us to discover the will of God in all things." },
      { n: 181, q: "Why do we receive the gift of Fortitude?", a: "We receive the gift of Fortitude to strengthen us to do the will of God in all things." },
      { n: 182, q: "Why do we receive the gift of Counsel?", a: "We receive the gift of Counsel to warn us of the deceits of the devil, and of the dangers to salvation." },
      { n: 183, q: "Why do we receive the gift of Understanding?", a: "We receive the gift of Understanding to enable us to know more clearly the mysteries of faith." },
      { n: 184, q: "Why do we receive the gift of Wisdom?", a: "We receive the gift of Wisdom to give us a relish for the things of God, and to direct our whole life and all our actions to His honor and glory." },
      { n: 185, q: "Which are the Beatitudes?", a: "The Beatitudes are:\n1. Blessed are the poor in spirit, for theirs is the kingdom of heaven.\n2. Blessed are the meek, for they shall possess the land.\n3. Blessed are they that mourn, for they shall be comforted.\n4. Blessed are they that hunger and thirst after justice, for they shall be filled.\n5. Blessed are the merciful, for they shall obtain mercy.\n6. Blessed are the clean of heart, for they shall see God.\n7. Blessed are the peacemakers, for they shall be called the children of God.\n8. Blessed are they that suffer persecution for justice sake, for theirs is the kingdom of heaven." },
      { n: 186, q: "Which are the twelve fruits of the Holy Ghost?", a: "The twelve fruits of the Holy Ghost are Charity, Joy, Peace, Patience, Benignity, Goodness, Long-suffering, Mildness, Faith, Modesty, Continency, and Chastity." },
    ],
  },
  {
    lesson: 17,
    title: "On the Sacrament of Penance",
    questions: [
      { n: 187, q: "What is the Sacrament of Penance?", a: "Penance is a Sacrament in which the sins committed after Baptism are forgiven." },
      { n: 188, q: "How does the Sacrament of Penance remit sin, and restore to the soul the friendship of God?", a: "The Sacrament of Penance remits sins and restores the friendship of God to the soul by means of the absolution of the priest." },
      { n: 189, q: "How do you know that the priest has the power of absolving from the sins committed after Baptism?", a: "I know that the priest has the power of absolving from the sins committed after Baptism, because Jesus Christ granted that power to the priests of His Church when He said: \"Receive ye the Holy Ghost. Whose sins you shall forgive, they are forgiven them; whose sins you shall retain, they are retained.\"" },
      { n: 190, q: "How do the priests of the Church exercise the power of forgiving sins?", a: "The priests of the Church exercise the power of forgiving sins by hearing the confession of sins, and granting pardon for them as ministers of God and in His name." },
      { n: 191, q: "What must we do to receive the Sacrament of Penance worthily?", a: "To receive the Sacrament of Penance worthily we must do five things:\n1. We must examine our conscience.\n2. We must have sorrow for our sins.\n3. We must make a firm resolution never more to offend God.\n4. We must confess our sins to the priest.\n5. We must accept the penance which the priest gives us." },
      { n: 192, q: "What is the examination of conscience?", a: "The examination of conscience is an earnest effort to recall to mind all the sins we have committed since our last worthy confession." },
      { n: 193, q: "How can we make a good examination of conscience?", a: "We can make a good examination of conscience by calling to memory the commandments of God, the precepts of the Church, the seven capital sins, and the particular duties of our state in life, to find out the sins we have committed." },
      { n: 194, q: "What should we do before beginning the examination of conscience?", a: "Before beginning the examination of conscience we should pray to God to give us light to know our sins and grace to detest them." },
    ],
  },
  {
    lesson: 18,
    title: "On Contrition",
    questions: [
      { n: 195, q: "What is contrition, or sorrow for sin?", a: "Contrition, or sorrow for sin, is a hatred of sin and a true grief of the soul for having offended God, with a firm purpose of sinning no more." },
      { n: 196, q: "What kind of sorrow should we have for our sins?", a: "The sorrow we should have for our sins should be interior, supernatural, universal, and sovereign." },
      { n: 197, q: "What do you mean by saying that our sorrow should be interior?", a: "When I say that our sorrow should be interior, I mean that it should come from the heart, and not merely from the lips." },
      { n: 198, q: "What do you mean by saying that our sorrow should be supernatural?", a: "When I say that our sorrow should be supernatural, I mean that it should be prompted by the grace of God, and excited by motives which spring from faith, and not by merely natural motives." },
      { n: 199, q: "What do you mean by saying that our sorrow should be universal?", a: "When I say that our sorrow should be universal, I mean that we should be sorry for all our mortal sins without exception." },
      { n: 200, q: "What do you mean when you say that our sorrow should be sovereign?", a: "When I say that our sorrow should be sovereign, I mean that we should grieve more for having offended God than for any other evil that can befall us." },
      { n: 201, q: "Why should we be sorry for our sins?", a: "We should be sorry for our sins, because sin is the greatest of evils and an offense against God our Creator, Preserver, and Redeemer, and because it shuts us out of heaven and condemns us to the eternal pains of hell." },
      { n: 202, q: "How many kinds of contrition are there?", a: "There are two kinds of contrition: perfect contrition and imperfect contrition." },
      { n: 203, q: "What is perfect contrition?", a: "Perfect contrition is that which fills us with sorrow and hatred for sin, because it offends God, who is infinitely good in Himself and worthy of all love." },
      { n: 204, q: "What is imperfect contrition?", a: "Imperfect contrition is that by which we hate what offends God, because by it we lose heaven and deserve hell; or because sin is so hateful in itself." },
      { n: 205, q: "Is imperfect contrition sufficient for a worthy confession?", a: "Imperfect contrition is sufficient for a worthy confession, but we should endeavor to have perfect contrition." },
      { n: 206, q: "What do you mean by a firm purpose of sinning no more?", a: "By a firm purpose of sinning no more I mean a fixed resolve not only to avoid all mortal sin, but also its near occasions." },
      { n: 207, q: "What do you mean by the near occasions of sin?", a: "By the near occasions of sin I mean all the persons, places, and things that may easily lead us into sin." },
    ],
  },
  {
    lesson: 19,
    title: "On Confession",
    questions: [
      { n: 208, q: "What is Confession?", a: "Confession is the telling of our sins to a duly authorized priest, for the purpose of obtaining forgiveness." },
      { n: 209, q: "What sins are we bound to confess?", a: "We are bound to confess all our mortal sins, but it is well also to confess our venial sins." },
      { n: 210, q: "Which are the chief qualities of a good Confession?", a: "The chief qualities of a good Confession are three: it must be humble, sincere, and entire." },
      { n: 211, q: "When is our Confession humble?", a: "Our Confession is humble, when we accuse our selves of our sins, with a deep sense of shame and sorrow for having offended God." },
      { n: 212, q: "When is our Confession sincere?", a: "Our Confession is sincere, when we tell our sins honestly and truthfully, neither exaggerating nor excusing them." },
      { n: 213, q: "When is our Confession entire?", a: "Our Confession is entire, when we tell the number and kinds of our sins and the circumstances which change their nature." },
      { n: 214, q: "What should we do if we cannot remember the number of our sins?", a: "If we cannot remember the number of our sins, we should tell the number as nearly as possible, and say how often we may have sinned in a day, a week, or a month, and how long the habit or practice has lasted." },
      { n: 215, q: "Is our Confession worthy if, without our fault, we forget to confess a mortal sin?", a: "If without our fault we forget to confess a mortal sin, our Confession is worthy, and the sin is forgiven; but it must be told in Confession if it again comes to our mind." },
      { n: 216, q: "Is it a grievous offense wilfully to conceal a mortal sin in Confession?", a: "It is a grievous offense wilfully to conceal a mortal sin in Confession, because we thereby tell a lie to the Holy Ghost, and make our Confession worthless." },
      { n: 217, q: "What must he do who has wilfully concealed a mortal sin in Confession?", a: "He who has wilfully concealed a mortal sin in Confession must not only confess it, but must also repeat all the sins he has committed since his last worthy Confession." },
      { n: 218, q: "Why does the priest give us a penance after Confession?", a: "The priest gives us a penance after Confession, that we may satisfy God for the temporal punishment due to our sins." },
      { n: 219, q: "Does not the Sacrament of Penance remit all punishment due to sin?", a: "The Sacrament of Penance remits the eternal punishment due to sin, but it does not always remit the temporal punishment which God requires as satisfaction for our sins." },
      { n: 220, q: "Why does God require a temporal punishment as a satisfaction for sin?", a: "God requires a temporal punishment as a satisfaction for sin, to teach us the great evil of sin and to prevent us from falling again." },
      { n: 221, q: "Which are the chief means by which we satisfy God for the temporal punishment due to sin?", a: "The chief means by which we satisfy God for the temporal punishment due to sin are: Prayer, Fasting, Almsgiving, all spiritual and corporal works of mercy, and the patient suffering of the ills of life." },
      { n: 222, q: "Which are the chief spiritual works of mercy?", a: "The chief spiritual works of mercy are seven: To admonish the sinner, to instruct the ignorant, to counsel the doubtful, to comfort the sorrowful, to bear wrongs patiently, to forgive all injuries, and to pray for the living and the dead." },
      { n: 223, q: "Which are the chief corporal works of mercy?", a: "The chief corporal works of mercy are seven: To feed the hungry, to give drink to the thirsty, to clothe the naked, to ransom the captive, to harbor the harborless, to visit the sick, and to bury the dead." },
    ],
  },
  {
    lesson: 20,
    title: "On the Manner of Making a Good Confession",
    questions: [
      { n: 224, q: "What should we do on entering the confessional?", a: "On entering the confessional we should kneel, make the sign of the Cross, and say to the priest, Bless me, Father; then add, I confess to Almighty God and to you, Father, that I have sinned." },
      { n: 225, q: "Which are the first things we should tell the priest in Confession?", a: "The first things we should tell the priest in Confession are the time of our last Confession, and whether we said the penance and went to Holy Communion." },
      { n: 226, q: "After telling the time of our last Confession and Communion what should we do?", a: "After telling the time of our last Confession and Communion we should confess all the mortal sins we have since committed, and all the venial sins we may wish to mention." },
      { n: 227, q: "What must we do when the confessor asks us questions?", a: "When the confessor asks us questions we must answer them truthfully and clearly." },
      { n: 228, q: "What should we do after telling our sins?", a: "After telling our sins we should listen with attention to the advice which the confessor may think proper to give." },
      { n: 229, q: "How should we end our Confession?", a: "We should end our Confession by saying, I also accuse myself of all the sins of my past life, telling, if we choose, one or several of our past sins." },
      { n: 230, q: "What should we do while the priest is giving us absolution?", a: "While the priest is giving us absolution we should from our heart renew the Act of Contrition." },
    ],
  },
  {
    lesson: 21,
    title: "On Prayer",
    questions: [
      { n: 231, q: "What is prayer?", a: "Prayer is the lifting up of our minds and hearts to God." },
      { n: 232, q: "Is prayer a necessary means of salvation?", a: "Prayer is a necessary means of salvation; for Our Lord has said, 'You must always pray, and not lose heart.'" },
      { n: 233, q: "What is the prayer which Our Lord Jesus Christ himself taught us?", a: "The prayer which Our Lord Jesus Christ himself taught us is the Lord's Prayer, or Pater Noster." },
      { n: 234, q: "Why is the Lord's Prayer the most perfect of all prayers?", a: "The Lord's Prayer is the most perfect of all prayers because Our Lord Jesus Christ himself composed it." },
      { n: 235, q: "In how many parts does the Lord's Prayer consist?", a: "The Lord's Prayer consists of three parts: the Preface, seven petitions, and the Conclusion." },
      { n: 236, q: "What does the Preface teach us?", a: "The Preface teaches us that in prayer we must approach God with confidence and reverence, for He is our Father." },
      { n: 237, q: "How many petitions are there in the Lord's Prayer?", a: "There are seven petitions in the Lord's Prayer." },
      { n: 238, q: "What is meant by the first petition, 'Hallowed be Thy Name'?", a: "By this petition we ask that the holy name of God may be honored and respected by all men." },
      { n: 239, q: "What is meant by the second petition, 'Thy Kingdom come'?", a: "By this petition we ask that God's kingdom may come into the hearts of all men." },
      { n: 240, q: "What is meant by the third petition, 'Thy will be done'?", a: "By this petition we ask that all men may obey the will of God as the angels obey it in Heaven." },
      { n: 241, q: "What is meant by the fourth petition, 'Give us this day our daily bread'?", a: "By this petition we ask God to provide for our daily needs, and especially for the bread of the Eucharist, which is the food of our souls." },
      { n: 242, q: "What is meant by the fifth, sixth, and seventh petitions?", a: "By the fifth petition we ask forgiveness for our sins; by the sixth we ask to be delivered from temptation; by the seventh we ask to be delivered from evil." },
      { n: 243, q: "What is meant by the Conclusion, 'Amen'?", a: "The Conclusion 'Amen' means 'So be it,' and expresses our firm confidence that God will grant our petitions." },
    ],
  },
  {
    lesson: 22,
    title: "On the Sacraments in General",
    questions: [
      { n: 244, q: "What is a Sacrament?", a: "A Sacrament is an outward sign instituted by Christ to give grace." },
      { n: 245, q: "How many Sacraments are there?", a: "There are Seven Sacraments: Baptism, Confirmation, Holy Eucharist, Penance, Extreme Unction, Holy Orders, and Matrimony." },
      { n: 246, q: "Why did Christ institute the Sacraments?", a: "Christ instituted the Sacraments to sanctify us, to increase sanctifying grace in our souls, and to help us practice virtue." },
      { n: 247, q: "What do all the Sacraments produce?", a: "All the Sacraments produce sacramental grace, which is a special help from God to overcome the obstacles to our salvation." },
      { n: 248, q: "What is necessary to receive a Sacrament worthily?", a: "To receive a Sacrament worthily we must be in the state of grace, except in Baptism and Extreme Unction, which may be received even by those in mortal sin." },
      { n: 249, q: "What is the difference between Sacraments of the Living and Sacraments of the Dead?", a: "Sacraments of the Living are those which require the state of grace to produce their full effect; Sacraments of the Dead are Baptism and Penance, which give grace even to those in mortal sin." },
      { n: 250, q: "Are all the Sacraments equally necessary?", a: "No; only Baptism is absolutely necessary for salvation. The others are not absolutely necessary, but are highly expedient for salvation and sanctification." },
      { n: 251, q: "Do the Sacraments always produce grace?", a: "Yes, the Sacraments always produce grace when they are properly administered and properly received." },
    ],
  },
  {
    lesson: 23,
    title: "On Baptism",
    questions: [
      { n: 252, q: "What is Baptism?", a: "Baptism is the Sacrament which cleanses us from original sin, makes us children of God, and members of the Church." },
      { n: 253, q: "Is Baptism necessary for salvation?", a: "Baptism is necessary for salvation; for Our Lord said, 'Unless a man be born again of water and the Spirit, he cannot enter the kingdom of God.'" },
      { n: 254, q: "Can anyone receive Baptism?", a: "Yes, anyone who is not already baptized can receive Baptism; but for Baptism to be valid, the proper matter and form must be used." },
      { n: 255, q: "What is the matter of Baptism?", a: "The matter of Baptism is natural water." },
      { n: 256, q: "What is the form of Baptism?", a: "The form of Baptism consists of the words: 'I baptize thee in the Name of the Father, and of the Son, and of the Holy Ghost.'" },
      { n: 257, q: "Who can administer Baptism?", a: "The proper minister of Baptism is a priest; but in case of necessity, any person who intends to do what the Church does can validly baptize." },
      { n: 258, q: "What are the effects of Baptism?", a: "The effects of Baptism are: the remission of all sin, original and actual; the remission of all punishment due to sin; the infusion of sanctifying grace; and the imprinting of a character which makes us members of the Church." },
      { n: 259, q: "Can Baptism be repeated?", a: "No, Baptism can never be repeated, for it imprints a character on the soul which can never be effaced." },
      { n: 260, q: "What name should be given in Baptism?", a: "The name given in Baptism should be that of a Saint, in order that the person baptized may have a heavenly intercessor." },
      { n: 261, q: "What are the duties of godparents?", a: "The duties of godparents are to see that the child receives a Christian education and practices the faith." },
      { n: 262, q: "What is the proper age for receiving Baptism?", a: "Although any age is proper for Baptism, children should be baptized as soon as possible after birth." },
      { n: 263, q: "What should parents do to prepare their child for Baptism?", a: "Parents should teach their child the truths of the faith and the commandments of God, so that he may know and love his Faith." },
    ],
  },
  {
    lesson: 24,
    title: "On Confirmation",
    questions: [
      { n: 264, q: "What is Confirmation?", a: "Confirmation is the Sacrament by which we receive the Holy Ghost to strengthen us in the faith." },
      { n: 265, q: "Why is Confirmation necessary?", a: "Confirmation is necessary because Baptism gives us the grace to become children of God, but Confirmation gives us the special grace to grow strong in the faith and to live as true soldiers of Christ." },
      { n: 266, q: "Who is the proper minister of Confirmation?", a: "The proper minister of Confirmation is a Bishop." },
      { n: 267, q: "What is the matter of Confirmation?", a: "The matter of Confirmation is Sacred Chrism, which is olive oil mixed with balsam and blessed by the Bishop." },
      { n: 268, q: "What is the form of Confirmation?", a: "The form of Confirmation consists of the words: 'I sign thee with the sign of the Cross, and I confirm thee with the Chrism of salvation, in the Name of the Father, and of the Son, and of the Holy Ghost.'" },
      { n: 269, q: "What are the effects of Confirmation?", a: "The effects of Confirmation are the increase of sanctifying grace, the perfection of Baptismal grace, and the imprinting of a character which strengthens us in faith." },
      { n: 270, q: "How should we prepare for Confirmation?", a: "We should prepare for Confirmation by making a good Confession, by learning the truths of the faith, and by praying earnestly for the grace of the Holy Ghost." },
      { n: 271, q: "What gifts does the Holy Ghost bestow in Confirmation?", a: "The Holy Ghost bestows in Confirmation the gifts of Wisdom, Understanding, Counsel, Fortitude, Knowledge, Piety, and Fear of the Lord." },
      { n: 272, q: "What should we do after receiving Confirmation?", a: "After receiving Confirmation we should live as true soldiers of Christ, ready to suffer for our faith and to spread the knowledge and love of our religion." },
      { n: 273, q: "Can Confirmation be repeated?", a: "No, Confirmation can never be repeated, for like Baptism it imprints a character on the soul." },
    ],
  },
  {
    lesson: 25,
    title: "On the Holy Eucharist",
    questions: [
      { n: 274, q: "What is the Holy Eucharist?", a: "The Holy Eucharist is the Sacrament containing the Body and Blood of Our Lord Jesus Christ under the appearances of bread and wine." },
      { n: 275, q: "Is the whole Christ present in the Holy Eucharist?", a: "Yes, the whole Christ is present in the Holy Eucharist—His Body, His Blood, His Soul, and His Divinity." },
      { n: 276, q: "What do we call the change of bread and wine into the Body and Blood of Christ?", a: "We call this change Transubstantiation." },
      { n: 277, q: "What is Transubstantiation?", a: "Transubstantiation is the conversion of the whole substance of bread into the substance of the Body of Christ, and of the whole substance of wine into the substance of His Blood." },
      { n: 278, q: "How long after the Consecration does the Eucharist remain the Body and Blood of Christ?", a: "As long as the appearances of bread and wine remain, so long does the Eucharist remain the Body and Blood of Christ." },
      { n: 279, q: "Is Christ present in each part of the Consecrated Host?", a: "Yes, Christ is present in each part of the Consecrated Host." },
      { n: 280, q: "Why did Christ institute the Holy Eucharist?", a: "Christ instituted the Holy Eucharist to perpetuate the memory of His Passion and Death, to nourish our souls with His Body and Blood, and to unite us with Him." },
      { n: 281, q: "When did Christ institute the Holy Eucharist?", a: "Christ instituted the Holy Eucharist on the evening before His Passion, at the Last Supper." },
      { n: 282, q: "What were the words by which Christ instituted the Eucharist?", a: "The words by which Christ instituted the Eucharist were: 'This is My Body . . . This is My Blood.'" },
      { n: 283, q: "Is the Mass a sacrifice?", a: "Yes, the Mass is a true and proper sacrifice, in which the Body and Blood of Christ are offered to God on the altar." },
      { n: 284, q: "What is the object of the sacrifice of the Mass?", a: "The object of the sacrifice of the Mass is to glorify God, to thank Him for His benefits, to obtain His graces, and to satisfy for our sins." },
      { n: 285, q: "Can a priest say Mass without people present?", a: "Yes, a priest can say Mass alone; the presence of people is not necessary for a valid Mass." },
      { n: 286, q: "What is the Blessed Sacrament?", a: "The Blessed Sacrament is the Holy Eucharist kept in the Tabernacle for the purpose of adoration and of giving it to the sick and dying." },
      { n: 287, q: "Should we visit the Blessed Sacrament?", a: "Yes, we should visit the Blessed Sacrament frequently, to adore Our Lord and to thank Him for His benefits." },
      { n: 288, q: "How should we treat the Blessed Sacrament?", a: "We should treat the Blessed Sacrament with the greatest reverence and respect, remembering that it is truly the Body and Blood of Christ." },
      { n: 289, q: "What happens to the accidents of bread and wine after Consecration?", a: "The accidents (appearance, taste, etc.) of bread and wine remain after the Consecration, though the substance is changed into the Body and Blood of Christ." },
      { n: 290, q: "How is this mystery possible?", a: "This mystery is possible because God is Almighty and can do all things." },
      { n: 291, q: "What virtue should we exercise when we see the Blessed Sacrament?", a: "When we see the Blessed Sacrament we should exercise the virtue of faith, firmly believing that Christ is truly present." },
      { n: 292, q: "What sin would it be to receive Communion in mortal sin?", a: "It would be a mortal sin to receive Communion in mortal sin, for it would be a grave irreverence to the Body of Christ." },
      { n: 293, q: "What is the proper worship of the Eucharist called?", a: "The proper worship of the Eucharist is called Latria, which means the highest kind of worship, belonging to God alone." },
      { n: 294, q: "Did the Apostles understand the mystery of the Eucharist?", a: "Many of the Apostles did not at first fully understand this mystery, but they believed the words of Christ and received it with faith." },
      { n: 295, q: "Is it a mortal sin to eat or drink something while fasting before Communion?", a: "Yes, it is a mortal sin to eat or drink anything (except water) while fasting before Communion, as required by the law of the Church." },
      { n: 296, q: "What should we do to prepare for Communion?", a: "To prepare for Communion we should examine our conscience, fast, and approach with great reverence and a lively faith." },
      { n: 297, q: "What should we do after receiving Communion?", a: "After receiving Communion we should make an act of thanksgiving, adore Our Lord in our hearts, and offer ourselves to His service." },
    ],
  },
  {
    lesson: 26,
    title: "On the Manner of Receiving Holy Communion",
    questions: [
      { n: 298, q: "What is required to receive Communion worthily?", a: "To receive Communion worthily we must be in the state of grace, have the right intention, be properly prepared, and observe the Eucharistic fast." },
      { n: 299, q: "What is the Eucharistic fast?", a: "The Eucharistic fast is the law which requires us to fast from all food and drink (except water) for at least three hours before receiving Communion." },
      { n: 300, q: "Why is the Eucharistic fast required?", a: "The Eucharistic fast is required to show reverence for the Blessed Sacrament and to prepare our bodies and souls for the reception of Our Lord." },
      { n: 301, q: "What is meant by being 'in the state of grace'?", a: "Being 'in the state of grace' means having no mortal sin on our soul and possessing sanctifying grace." },
      { n: 302, q: "What should we do if we have committed a mortal sin since our last Confession?", a: "If we have committed a mortal sin since our last Confession, we must make a good Confession before receiving Communion." },
      { n: 303, q: "What should we do before approaching the altar to receive Communion?", a: "Before approaching the altar we should think seriously on what we are about to do and make an act of deep respect and reverence to Our Lord." },
      { n: 304, q: "What should we do when we receive the Body of Christ from the priest?", a: "When we receive the Body of Christ we should open our mouth, receive it with reverence, and thank Our Lord in our hearts." },
      { n: 305, q: "Is it permitted to receive Communion every day?", a: "Yes, the Church encourages frequent Communion, even daily reception, for those properly disposed." },
      { n: 306, q: "What are the effects of receiving Communion worthy?", a: "The effects of receiving Communion worthily are the increase of sanctifying grace, strength against temptation, the forgiveness of venial sins, and the preservation of our soul from mortal sin." },
      { n: 307, q: "Can venial sins be forgiven by receiving Communion?", a: "Yes, venial sins are forgiven by receiving Communion worthily, though Confession is the ordinary way of being forgiven from sin." },
      { n: 308, q: "What should we do if we accidentally drop a particle of the Consecrated Host?", a: "We should pick it up with great reverence and with the utmost care, and consume it with respect." },
      { n: 309, q: "What time of day should we receive Communion?", a: "Communion should ordinarily be received in the morning, at the time of the Sunday or weekday Mass." },
      { n: 310, q: "Is it necessary to receive Communion very frequently?", a: "The Church recommends frequent Communion at least once a week, and especially on Sundays; but those in the state of grace should receive it as often as their circumstances allow." },
    ],
  },
  {
    lesson: 27,
    title: "On Penance",
    questions: [
      { n: 311, q: "What is the Sacrament of Penance?", a: "The Sacrament of Penance is the Sacrament by which the sins committed after Baptism are forgiven." },
      { n: 312, q: "Why is the Sacrament of Penance necessary?", a: "The Sacrament of Penance is necessary because even after Baptism we may commit sins, and God has ordained this Sacrament as the ordinary means of obtaining forgiveness." },
      { n: 313, q: "What are the parts of the Sacrament of Penance?", a: "The parts of the Sacrament of Penance are Contrition, Confession, and Satisfaction." },
      { n: 314, q: "What is Contrition?", a: "Contrition is sorrow for our sins joined with a firm purpose of amendment." },
      { n: 315, q: "How many kinds of Contrition are there?", a: "There are two kinds of Contrition: Perfect Contrition, which is sorrow for sin because it offends God; and Imperfect Contrition, which is sorrow for sin because of fear of punishment." },
      { n: 316, q: "Is Imperfect Contrition sufficient for the reception of the Sacrament of Penance?", a: "Yes, Imperfect Contrition is sufficient for the reception of the Sacrament of Penance." },
      { n: 317, q: "What is Confession?", a: "Confession is the telling of our sins to a priest who has the power to absolve them." },
      { n: 318, q: "Why must we confess our sins?", a: "We must confess our sins because Christ gave to His priests the power to forgive sins, and the Church requires the confession of mortal sins." },
      { n: 319, q: "What sins should we confess?", a: "We should confess all mortal sins, as to kind and number, that we can remember after a diligent examination of conscience." },
      { n: 320, q: "Is it necessary to confess venial sins?", a: "No, it is not necessary to confess venial sins, though it is very helpful to do so." },
      { n: 321, q: "Should we accuse ourselves of our faults?", a: "Yes, we should accuse ourselves of our faults in Confession, making no excuses for our sins." },
      { n: 322, q: "What is Satisfaction?", a: "Satisfaction is the doing of a penance appointed by the priest to make amends for the temporal punishment due to sin." },
      { n: 323, q: "Why is Satisfaction necessary?", a: "Satisfaction is necessary because God requires temporal punishment as a satisfaction for sin, to teach us the evil of sin and to prevent us from sinning again." },
      { n: 324, q: "What should we do to make a good Confession?", a: "To make a good Confession we should examine our conscience, conceive true sorrow for our sins, confess all mortal sins, listen to the priest's advice, and do the penance given." },
      { n: 325, q: "How often should we go to Confession?", a: "We should go to Confession at least once a year, and especially before great festivals and after we have committed mortal sin." },
      { n: 326, q: "How often should we go to Confession if we have committed no mortal sin?", a: "Even if we have committed no mortal sin, we should go to Confession about once a month, or at least several times a year, to obtain grace and to grow in virtue." },
      { n: 327, q: "Can we receive absolution for a sin we have not confessed?", a: "No, we cannot receive absolution for a mortal sin we have not confessed, unless it is impossible for us to confess it." },
      { n: 328, q: "Is there any sin too great to be forgiven in the Sacrament of Penance?", a: "No, there is no sin too great to be forgiven in the Sacrament of Penance if we are truly sorry." },
      { n: 329, q: "What sins are hardest to confess?", a: "The sins that are hardest to confess are generally those of which we are most ashamed, but these especially need to be confessed." },
      { n: 330, q: "What should we do after making a good Confession?", a: "After making a good Confession we should perform the penance given by the priest, thank God for His pardon, and strive earnestly to avoid sin in the future." },
    ],
  },
  {
    lesson: 28,
    title: "On Extreme Unction",
    questions: [
      { n: 331, q: "What is Extreme Unction?", a: "Extreme Unction is the Sacrament by which the sick and dying are anointed with blessed oil to prepare them for death and eternal life." },
      { n: 332, q: "Why is Extreme Unction called 'Extreme' Unction?", a: "It is called 'Extreme' Unction because it is the last Unction, or anointing, given in the Sacraments of Anointing." },
      { n: 333, q: "Who can receive Extreme Unction?", a: "Only those who are seriously ill or dying can receive Extreme Unction." },
      { n: 334, q: "What are the effects of Extreme Unction?", a: "The effects of Extreme Unction are the remission of venial sins and the temporal punishment due to sin, comfort in suffering, and preparation for death." },
      { n: 335, q: "Should Extreme Unction be received as soon as the danger of death begins?", a: "Yes, Extreme Unction should be received as soon as there is danger of death, while the sick person is still able to receive it." },
      { n: 336, q: "Can Extreme Unction be repeated?", a: "Yes, if the sick person recovers and later becomes ill again with danger of death, he can again receive Extreme Unction." },
      { n: 337, q: "Who administers Extreme Unction?", a: "The proper minister of Extreme Unction is a priest." },
      { n: 338, q: "What is the matter of Extreme Unction?", a: "The matter of Extreme Unction is oil blessed by the Bishop." },
      { n: 339, q: "How many times should a priest anoint the sick?", a: "A priest should anoint the sick person on the forehead and on the hands, and in some cases on other parts of the body." },
      { n: 340, q: "What should we do for those in danger of death?", a: "We should pray for those in danger of death, especially that they may make a good Confession and receive Extreme Unction before they die." },
    ],
  },
  {
    lesson: 29,
    title: "On Holy Orders",
    questions: [
      { n: 341, q: "What is the Sacrament of Holy Orders?", a: "The Sacrament of Holy Orders is the Sacrament by which men are ordained to serve God and the Church as priests and deacons." },
      { n: 342, q: "Who can receive Holy Orders?", a: "Only baptized men who are free from impediments can receive Holy Orders." },
      { n: 343, q: "What are the chief Orders?", a: "The chief Orders are those of Bishop, Priest, and Deacon." },
      { n: 344, q: "What is the power of a priest?", a: "The power of a priest is to offer the Holy Sacrifice of the Mass and to administer the Sacraments." },
      { n: 345, q: "Can a priest forgive all sins?", a: "A priest can forgive all sins except those reserved to the Bishop or the Pope, in cases where the Bishop or Pope have reserved the forgiveness to themselves." },
      { n: 346, q: "What is meant by 'reserved sins'?", a: "Reserved sins are those for which the power of forgiving them has been reserved to a Bishop or the Pope." },
      { n: 347, q: "Why are some sins reserved?", a: "Some sins are reserved to impress upon the faithful the gravity of certain sins and to discourage them from committing such sins." },
      { n: 348, q: "What should we do if we are in need of receiving the Sacrament from a priest not our own?", a: "We can and should approach any priest in good standing, even if he is not our own priest, to receive the Sacraments in time of need." },
      { n: 349, q: "What is the meaning of 'stole fees'?", a: "Stole fees are voluntary offerings made to the priest for administering certain Sacraments, but they are not to be demanded or their absence should not prevent the administration of the Sacrament." },
      { n: 350, q: "Can a married man receive Holy Orders?", a: "Generally, only unmarried men can receive Holy Orders in the Roman Catholic Church, according to the law of celibacy." },
      { n: 351, q: "What is the purpose of the celibacy of priests?", a: "The purpose of the celibacy of priests is to free them from the cares of family life so that they may give themselves entirely to the service of God and souls." },
    ],
  },
  {
    lesson: 30,
    title: "On Matrimony",
    questions: [
      { n: 352, q: "What is the Sacrament of Matrimony?", a: "The Sacrament of Matrimony is the Sacrament by which a man and a woman are united in marriage before God and the Church." },
      { n: 353, q: "What is the object of Matrimony?", a: "The object of Matrimony is the mutual love of husband and wife and the procreation and education of children." },
      { n: 354, q: "What are the chief duties of married people?", a: "The chief duties of married people are to love one another, to be faithful to one another, and to educate their children in the faith and virtue." },
      { n: 355, q: "Can a divorced person marry again in the Church?", a: "Generally, a divorced person cannot marry again in the Church while the first husband or wife is still living, unless the first marriage is annulled." },
      { n: 356, q: "What is the form of marriage?", a: "The form of marriage consists of the exchange of consent between the parties before the priest and two witnesses." },
      { n: 357, q: "What consent is necessary for a valid marriage?", a: "For a valid marriage there must be the free, serious consent of both parties to take each other as husband and wife." },
      { n: 358, q: "Who must be present at a marriage?", a: "The priest (or his delegate) and at least two witnesses must be present at a Catholic marriage." },
      { n: 359, q: "Can mixed marriages take place?", a: "Mixed marriages (between a Catholic and non-Catholic) can take place only with special permission from the bishop." },
      { n: 360, q: "What should parents teach their children about marriage?", a: "Parents should teach their children that marriage is a holy and sacred bond, and that it demands mutual love, fidelity, and the willingness to accept children." },
      { n: 361, q: "What should we do to prepare for marriage?", a: "To prepare for marriage we should go to Confession, receive Communion, live chastely, and pray for God's blessing on the marriage." },
    ],
  },
  {
    lesson: 31,
    title: "On the Commandments of God in General",
    questions: [
      { n: 362, q: "What are the Commandments of God?", a: "The Commandments of God are the rules which God has given us to follow in order to be saved." },
      { n: 363, q: "How many Commandments of God are there?", a: "There are ten Commandments of God." },
      { n: 364, q: "Why did God give us the Commandments?", a: "God gave us the Commandments because He loves us and wants us to be happy and to be saved." },
      { n: 365, q: "What does it mean to keep the Commandments?", a: "To keep the Commandments means to obey them, to do what they command, and to avoid what they forbid." },
      { n: 366, q: "Is it difficult to keep the Commandments?", a: "It is not impossible to keep the Commandments with the help of God's grace; and by doing so we become holy and happy." },
      { n: 367, q: "What is the summary of all the Commandments?", a: "The summary of all the Commandments is to love God with our whole heart and our neighbor as ourselves." },
      { n: 368, q: "What do the first three Commandments teach us?", a: "The first three Commandments teach us our duties toward God; the last seven teach us our duties toward ourselves and our neighbor." },
    ],
  },
  {
    lesson: 32,
    title: "On the First Three Commandments",
    questions: [
      { n: 369, q: "What is the First Commandment?", a: "The First Commandment is: Thou shalt have no other gods before Me." },
      { n: 370, q: "What does the First Commandment forbid?", a: "The First Commandment forbids us to worship any false god and to practice idolatry, superstition, and blasphemy." },
      { n: 371, q: "What is blasphemy?", a: "Blasphemy is speaking irreverently of God, the Saints, or sacred things." },
      { n: 372, q: "Is it a sin to swear by God falsely?", a: "Yes, it is a mortal sin to swear by God falsely or to take a false oath in the name of God." },
      { n: 373, q: "Is it a sin to swear by the Saints?", a: "It is not a sin to swear by the Saints, but it is better to swear only by God." },
      { n: 374, q: "What is the Second Commandment?", a: "The Second Commandment is: Thou shalt not take the name of the Lord thy God in vain." },
      { n: 375, q: "What does the Second Commandment forbid?", a: "The Second Commandment forbids us to use God's name irreverently, to swear falsely, and to curse." },
      { n: 376, q: "What is the Third Commandment?", a: "The Third Commandment is: Remember to keep holy the Sabbath day." },
      { n: 377, q: "What does the Third Commandment require?", a: "The Third Commandment requires us to keep Sunday holy as the Lord's day by hearing Mass and resting from servile works." },
      { n: 378, q: "Is it a sin to miss Mass on Sunday?", a: "Yes, it is a mortal sin to miss Mass on Sunday without a just cause, such as sickness or necessity." },
      { n: 379, q: "What are 'servile works'?", a: "Servile works are bodily labors, such as buying and selling, working in fields or shops, and other forms of manual labor." },
      { n: 380, q: "Can we do works of mercy on Sunday?", a: "Yes, we can and should do works of mercy on Sunday, such as visiting the sick and helping those in need." },
      { n: 381, q: "What should we do on Saturday, the vigil of Sunday?", a: "On Saturday we should prepare ourselves to keep Sunday holy by going to Confession and receiving Communion." },
    ],
  },
  {
    lesson: 33,
    title: "On the Fourth Commandment",
    questions: [
      { n: 382, q: "What is the Fourth Commandment?", a: "The Fourth Commandment is: Honor thy father and thy mother." },
      { n: 383, q: "What does the Fourth Commandment require?", a: "The Fourth Commandment requires us to love, respect, and obey our parents." },
      { n: 384, q: "Are we bound to obey our parents in all things?", a: "We are bound to obey our parents except in matters contrary to the law of God." },
      { n: 385, q: "What do we owe to our parents when they are old?", a: "When our parents are old and poor, we are bound to help and support them." },
      { n: 386, q: "What are the duties of parents toward their children?", a: "The duties of parents toward their children are to feed them, clothe them, educate them, and train them in the fear and love of God." },
      { n: 387, q: "Are parents bound to educate their children in the faith?", a: "Yes, parents are strictly bound to educate their children in the faith and to see that they know and practice their religion." },
      { n: 388, q: "What should parents do to keep their children from sin?", a: "Parents should keep their children from sin by watching over them, teaching them virtue, and correcting them when they do wrong." },
      { n: 389, q: "What respect do we owe to lawful superiors?", a: "We owe to lawful superiors the same respect, obedience, and support that we owe to our parents, as far as their authority extends." },
      { n: 390, q: "What do we understand by 'lawful superiors'?", a: "By 'lawful superiors' we understand those placed over us by God to direct and govern us, such as rulers, teachers, and religious superiors." },
    ],
  },
  {
    lesson: 34,
    title: "On the Fifth Commandment",
    questions: [
      { n: 391, q: "What is the Fifth Commandment?", a: "The Fifth Commandment is: Thou shalt not kill." },
      { n: 392, q: "What does the Fifth Commandment forbid?", a: "The Fifth Commandment forbids us to murder, to kill ourselves, to harm others, and to be angry without cause." },
      { n: 393, q: "Is it always sinful to kill a person?", a: "It is not always sinful to kill a person; for instance, a soldier may justly kill the enemy in a just war, and a lawful judge may execute a criminal." },
      { n: 394, q: "Is suicide a great sin?", a: "Yes, suicide is a great mortal sin, because we take the life which God has given us, and because it shows despair of God's mercy." },
      { n: 395, q: "What does it mean to hate our neighbor?", a: "To hate our neighbor means to wish him evil and to do him harm in word or deed." },
      { n: 396, q: "Is it sinful to be angry?", a: "It is not sinful to be angry at an injustice; but it is sinful to be angry without just cause or to let anger lead us to revenge." },
      { n: 397, q: "What should we do to overcome anger?", a: "To overcome anger we should be patient, humble, and quick to forgive those who offend us." },
      { n: 398, q: "What does the Fifth Commandment require?", a: "The Fifth Commandment requires us to take care of our health, to avoid intemperance, and to practice patience and gentleness toward all." },
    ],
  },
  {
    lesson: 35,
    title: "On the Sixth and Ninth Commandments",
    questions: [
      { n: 399, q: "What is the Sixth Commandment?", a: "The Sixth Commandment is: Thou shalt not commit adultery." },
      { n: 400, q: "What does the Sixth Commandment forbid?", a: "The Sixth Commandment forbids all unlawful carnal thoughts, words, and deeds." },
      { n: 401, q: "Is impurity a grave sin?", a: "Yes, impurity is always a grave sin, and especially when committed by those bound by the vow of chastity." },
      { n: 402, q: "What means should we use to preserve chastity?", a: "We should preserve chastity by avoiding bad thoughts, by guarding our senses, by prayer, and by receiving the Sacraments frequently." },
      { n: 403, q: "Is it wrong to think about unlawful things?", a: "Yes, if we deliberately keep unlawful thoughts in our mind, it is sinful; but casual thoughts that we at once reject are not sinful." },
      { n: 404, q: "What is the Ninth Commandment?", a: "The Ninth Commandment is: Thou shalt not covet thy neighbor's wife." },
      { n: 405, q: "What does the Ninth Commandment forbid?", a: "The Ninth Commandment forbids us to desire or covet what belongs to another, especially unlawful desires and sinful thoughts." },
      { n: 406, q: "How does the Sixth Commandment differ from the Ninth?", a: "The Sixth Commandment forbids unlawful deeds; the Ninth forbids the unlawful desires and thoughts that lead to such deeds." },
      { n: 407, q: "Is there any difference in guilt between committing an unlawful deed and merely thinking about it?", a: "Yes, there is a great difference; for merely thinking about it without consenting to it is usually not sinful, or at most a venial sin." },
      { n: 408, q: "What does the Ninth Commandment require?", a: "The Ninth Commandment requires us to control our desires and thoughts and to keep our hearts pure and innocent." },
      { n: 409, q: "Is it permitted to read certain kinds of literature?", a: "It is not permitted to read literature that is designed to arouse sinful passions, or books that are forbidden by the Church." },
      { n: 410, q: "What causes impure thoughts?", a: "Impure thoughts are often caused by the reading of bad books, by association with bad companions, and by the neglect of prayer and the Sacraments." },
      { n: 411, q: "What should we do when we find ourselves troubled by impure thoughts?", a: "When troubled by impure thoughts, we should at once direct our minds to something good, say a short prayer, and make an act of will to reject the temptation." },
      { n: 412, q: "How is a boy to learn what is right and wrong in these matters?", a: "A boy should learn these things from his parents, from his confessor, or from a good Catholic book; but he should be careful not to satisfy a sinful curiosity." },
      { n: 413, q: "Is there anything shameful about learning these matters?", a: "There is nothing shameful about learning these matters in the right way from proper sources; but there is everything shameful in trying to learn them in a bad way." },
    ],
  },
  {
    lesson: 36,
    title: "On the Seventh and Tenth Commandments",
    questions: [
      { n: 414, q: "What is the Seventh Commandment?", a: "The Seventh Commandment is: Thou shalt not steal." },
      { n: 415, q: "What does the Seventh Commandment forbid?", a: "The Seventh Commandment forbids us to steal, to cheat, to defraud, and to take what belongs to another." },
      { n: 416, q: "What is theft?", a: "Theft is the unlawful taking of what belongs to another, whether great or small." },
      { n: 417, q: "Is it sinful to take a small thing?", a: "Yes, even taking a small thing is sinful; but the sin is greater or less according to the value of the thing taken and the circumstances." },
      { n: 418, q: "Are we bound to restore what we have stolen?", a: "Yes, we are strictly bound to restore what we have stolen, and if we cannot restore the actual thing, we must make restitution in money." },
      { n: 419, q: "Can we keep money that we find?", a: "No, we cannot keep money that we find; we should try to find the owner and return it to him." },
      { n: 420, q: "What does the Seventh Commandment require?", a: "The Seventh Commandment requires us to be honest in our dealings, to work faithfully, to pay our debts, and to respect the property of others." },
      { n: 421, q: "What is the Tenth Commandment?", a: "The Tenth Commandment is: Thou shalt not covet thy neighbor's goods." },
    ],
  },
  {
    lesson: 37,
    title: "On the Eighth Commandment",
    questions: [
      { n: 422, q: "What is the Eighth Commandment?", a: "The Eighth Commandment is: Thou shalt not bear false witness against thy neighbor." },
      { n: 423, q: "What does the Eighth Commandment forbid?", a: "The Eighth Commandment forbids all manner of falsehood, such as lying, slander, detraction, and rash judgment." },
      { n: 424, q: "What is a lie?", a: "A lie is a statement of something which is false, with the intention to deceive." },
      { n: 425, q: "Is it a sin to tell a lie?", a: "Yes, every lie is a sin, and the sin is greater or less according to the nature of the lie and the harm it does." },
      { n: 426, q: "What is slander?", a: "Slander is making false statements about a person's character or conduct with the intent to harm that person's reputation." },
      { n: 427, q: "What is detraction?", a: "Detraction is the telling of truthful things about a person for the purpose of harming that person's reputation." },
      { n: 428, q: "What is rash judgment?", a: "Rash judgment is believing evil of a person without sufficient cause." },
      { n: 429, q: "What does the Eighth Commandment require?", a: "The Eighth Commandment requires us to speak the truth, to respect the good name of others, and to defend them when they are unjustly attacked." },
    ],
  },
];
