// LOE Essentials C — transcribed/condensed from RCA's official master lesson plan doc, pulled 2026-08-09.
// 6th Grade language arts (Logic of English). 33 weeks spanning Aug 2026 – May 2027. Paced M/T/W and Th/F instruction.
// RCA tutor teaches on Mon & Thu only. Each week covers one unit with multiple parts: phonograms → spelling rules → grammar → vocabulary.
// Focus: phonemic awareness, spelling analysis, grammar (parts of speech, verbs, etc.), vocabulary building (morphemes/roots), dictation practice.

import type { SubjectContent } from "./types";

export const loeEssentialsCContent: SubjectContent = {
  overview:
    "Logic of English Essentials C: 33-week 6th grade language arts curriculum (Aug 2026–May 2027). Core subjects: phonograms (A-Z and advanced), spelling rules (26 rules across the year), grammar (nouns, plurals, verbs, adjectives, adverbs, parts of speech), vocabulary (morphemes/roots, prefixes, suffixes). Paced across five instructional days per week (M/T/W then Th/F), with RCA tutoring on Monday and Thursday only. Each week typically covers one unit with 4-5 parts: Part 1 introduces phonograms/sounds, Part 2 covers spelling rules/analysis, Part 3 addresses grammar, Part 4 teaches vocabulary, Part 5 assessment. Essentials Reader (odd units only) integrated for fluency. Workbook and LOE Notebook practice daily.",
  lessons: [
    { n: 1, sections: [{ label: "Unit", text: "Unit 1: Phonograms A-Z, Consonants & Vowels, Spelling Rule 11 (QU), Grammar (Nouns), Introduction to Spelling Analysis" }, { label: "Monday focus", text: "Teach phonograms A-Z, exploring consonants and vowels, introduce Spelling Rule 11 (QU)" }, { label: "Thursday focus", text: "Spelling Analysis introduction, teach nouns and plurals, dictation practice, vocabulary (Level C: prefix/suffix/morpheme study)" }] },
    { n: 2, sections: [{ label: "Unit", text: "Unit 1 Part 5 (Assessment 1), Unit 2: New Phonograms (ck, ee, ng, th), Short/Long Vowels, Rule 26 (When to Use CK)" }, { label: "Monday focus", text: "Unit 1 Check Your Understanding, proctor Unit 1 Assessment, begin Unit 2 with new phonograms and vowel sounds" }, { label: "Thursday focus", text: "Grammar Review (adjectives), Unit 2 Part 3 dictation, spelling analysis Level C, essentials reader Unit 1 (Ten Quips) pre-reading" }] },
    { n: 3, sections: [{ label: "Unit", text: "Unit 2 Part 4, Unit 3 beginning" }, { label: "Monday focus", text: "Note: Labor Day (RCA closed Mon). Tue/Wed: Unit 2 vocabulary (Level C), Unit 2 Part 4 dictation" }, { label: "Thursday focus", text: "Essentials Reader Unit 1 continued (handwriting & composition), Unit 2 Part 4 dictation follow-up" }] },
    { n: 4, sections: [{ label: "Unit", text: "Unit 2 Part 5 (Assessment 2), Unit 3: New Phonograms (ai, ay, oy, ow, or)" }, { label: "Monday focus", text: "Unit 2 Check Your Understanding, proctor Unit 2 Assessment, begin Unit 3 phonograms and sounds" }, { label: "Thursday focus", text: "Unit 3 spelling rules and grammar, dictation, essentials reader Unit 1 continued" }] },
    { n: 5, sections: [{ label: "Unit", text: "Unit 3 Part 2–3: Spelling Analysis, Grammar (Verbs, Past Tense)" }, { label: "Monday focus", text: "Spelling rules (Unit 3), grammar verb tenses, spelling journal" }, { label: "Thursday focus", text: "Verb tenses (past/present), spelling list exercises, dictation, essentials reader handwriting" }] },
    { n: 6, sections: [{ label: "Unit", text: "Unit 3 Part 4–5: Vocabulary, Assessment 3" }, { label: "Monday focus", text: "Vocabulary (morphemes, roots), spelling review, Unit 3 Check Your Understanding" }, { label: "Thursday focus", text: "Unit 3 Assessment, vocabulary building (Level C morpheme study)" }] },
    { n: 7, sections: [{ label: "Unit", text: "Unit 4: New Phonograms (ea, -igh, aw, ou, ew), Exploring Sounds" }, { label: "Monday focus", text: "Unit 4 phonograms, exploring long vowel sounds and consonant pairs" }, { label: "Thursday focus", text: "Spelling rules Unit 4, grammar review, dictation" }] },
    { n: 8, sections: [{ label: "Unit", text: "Unit 4 Part 3–4: Grammar (Adverbs), Vocabulary" }, { label: "Monday focus", text: "Grammar: adverbs (how, when, where), spelling analysis Unit 4" }, { label: "Thursday focus", text: "Vocabulary Unit 4, dictation, Unit 4 Part 4 assessment introduction" }] },
    { n: 9, sections: [{ label: "Unit", text: "Unit 4 Part 5 (Assessment 4), Unit 5 introduction" }, { label: "Monday focus", text: "Unit 4 spelling journal review, Check Your Understanding, proctor Unit 4 Assessment, begin Unit 5" }, { label: "Thursday focus", text: "Unit 5 phonograms and sounds introduction, spelling rules foundation" }] },
    { n: 10, sections: [{ label: "Unit", text: "Unit 5: Exploring Sounds, Spelling Rules, Grammar introduction" }, { label: "Monday focus", text: "Unit 5 phonograms, vowel sound review, spelling journal" }, { label: "Thursday focus", text: "Spelling analysis Unit 5, grammar (sentence structure), dictation" }] },
    { n: 11, sections: [{ label: "Unit", text: "Unit 5 Part 3–4: Grammar (Sentences, Clauses), Vocabulary" }, { label: "Monday focus", text: "Grammar: sentences, simple sentences, compound sentences, independent/dependent clauses" }, { label: "Thursday focus", text: "Vocabulary Unit 5, spelling list exercises, dictation practice" }] },
    { n: 12, sections: [{ label: "Unit", text: "Unit 5 Part 5 (Assessment 5), Unit 6 beginning" }, { label: "Monday focus", text: "Unit 5 spelling/grammar review, Check Your Understanding, Unit 5 Assessment" }, { label: "Thursday focus", text: "Unit 6 introduction, new phonograms and sounds" }] },
    { n: 13, sections: [{ label: "Unit", text: "Unit 6: Phonograms, Spelling Rules, Grammar continuation" }, { label: "Monday focus", text: "Unit 6 phonograms and exploring sounds, spelling rules" }, { label: "Thursday focus", text: "Spelling analysis Unit 6, grammar review (parts of speech summary), dictation" }] },
    { n: 14, sections: [{ label: "Unit", text: "Unit 6 Part 3–4: Grammar (Articles, Pronouns), Vocabulary" }, { label: "Monday focus", text: "Grammar: articles (a, an, the), pronouns (he, she, it, they, etc.)" }, { label: "Thursday focus", text: "Vocabulary Unit 6, pronoun antecedent agreement, dictation" }] },
    { n: 15, sections: [{ label: "Unit", text: "Unit 6 Part 5 (Assessment 6), Unit 7 start" }, { label: "Monday focus", text: "Unit 6 Check Your Understanding, Assessment 6, Unit 7 phonograms introduction" }, { label: "Thursday focus", text: "Unit 7 sounds and spelling rules, grammar reinforcement" }] },
    { n: 16, sections: [{ label: "Unit", text: "Unit 7: Advanced Phonograms, Spelling Rules, Grammar practice" }, { label: "Monday focus", text: "Unit 7 phonograms and vowel sounds, spelling rules and analysis" }, { label: "Thursday focus", text: "Grammar review and practice (combining sentences), dictation, vocabulary introduction" }] },
    { n: 17, sections: [{ label: "Unit", text: "Unit 7 Part 3–4: Grammar (Sentence Combining), Vocabulary" }, { label: "Monday focus", text: "Grammar: combining sentences with conjunctions and dependent clauses" }, { label: "Thursday focus", text: "Vocabulary Unit 7, spelling list completion, dictation practice" }] },
    { n: 18, sections: [{ label: "Unit", text: "Unit 7 Part 5 (Assessment 7), Unit 8 introduction" }, { label: "Monday focus", text: "Unit 7 spelling and grammar review, Check Your Understanding, Unit 7 Assessment" }, { label: "Thursday focus", text: "Unit 8 phonograms, exploring sounds, grammar continuation" }] },
    { n: 19, sections: [{ label: "Unit", text: "Unit 8: Phonograms, Spelling Rules, Grammar and Vocabulary focus" }, { label: "Monday focus", text: "Unit 8 phonograms and sounds, spelling rules and journal" }, { label: "Thursday focus", text: "Spelling analysis Unit 8, grammar (prepositions), vocabulary building" }] },
    { n: 20, sections: [{ label: "Unit", text: "Unit 8 Part 3–4: Grammar (Prepositions), Vocabulary practice" }, { label: "Monday focus", text: "Grammar: prepositions and prepositional phrases, spelling list exercises" }, { label: "Thursday focus", text: "Vocabulary Unit 8, grammar review, dictation" }] },
    { n: 21, sections: [{ label: "Unit", text: "Unit 8 Part 5 (Assessment 8), Unit 9 start" }, { label: "Monday focus", text: "Unit 8 Check Your Understanding, Assessment 8, Begin Unit 9" }, { label: "Thursday focus", text: "Unit 9 phonograms and sounds, spelling rules introduction" }] },
    { n: 22, sections: [{ label: "Unit", text: "Unit 9: Phonograms, Spelling Rules, Grammar and Vocabulary" }, { label: "Monday focus", text: "Unit 9 phonograms, exploring sounds, spelling rules and analysis" }, { label: "Thursday focus", text: "Grammar (conjunctions), vocabulary Unit 9, dictation" }] },
    { n: 23, sections: [{ label: "Unit", text: "Unit 9 Part 3–4: Grammar (Conjunctions), Vocabulary" }, { label: "Monday focus", text: "Grammar: coordinating and subordinating conjunctions, sentence combining" }, { label: "Thursday focus", text: "Vocabulary Unit 9, spelling list exercises, grammar review" }] },
    { n: 24, sections: [{ label: "Unit", text: "Unit 9 Part 5 (Assessment 9), Unit 10 introduction" }, { label: "Monday focus", text: "Unit 9 Check Your Understanding, Assessment 9, Unit 10 phonograms start" }, { label: "Thursday focus", text: "Unit 10 sounds and spelling rules, grammar review" }] },
    { n: 25, sections: [{ label: "Unit", text: "Unit 10: Phonograms, Spelling Analysis, Grammar and Vocabulary" }, { label: "Monday focus", text: "Unit 10 phonograms and vowel sounds, spelling journal" }, { label: "Thursday focus", text: "Spelling analysis Unit 10, grammar (review all parts of speech), vocabulary" }] },
    { n: 26, sections: [{ label: "Unit", text: "Unit 10 Part 3–4: Grammar and Vocabulary" }, { label: "Monday focus", text: "Grammar review (all parts of speech), spelling list exercises" }, { label: "Thursday focus", text: "Vocabulary Unit 10, dictation, grammar reinforcement" }] },
    { n: 27, sections: [{ label: "Unit", text: "Unit 10 Part 5 (Assessment 10), Spring break preparation" }, { label: "Monday focus", text: "Unit 10 Check Your Understanding, Assessment 10" }, { label: "Thursday focus", text: "Easter break (no work): Mar 30 – Apr 10. Spring semester review and consolidation" }] },
    { n: 28, sections: [{ label: "Unit", text: "Easter break continuation" }, { label: "Monday focus", text: "No instruction during Easter break" }, { label: "Thursday focus", text: "No instruction during Easter break" }] },
    { n: 29, sections: [{ label: "Unit", text: "Unit 25 Part 5 (Assessment moved to Thu), Unit 26 Part 3–4" }, { label: "Monday focus", text: "CLT Practice Day, Unit 25 Part 5 review, grammar flash card review" }, { label: "Thursday focus", text: "Unit 25 Assessment, Unit 26 grammar and vocabulary practice" }] },
    { n: 30, sections: [{ label: "Unit", text: "Unit 26–27: Spring semester core review and practice" }, { label: "Monday focus", text: "Unit 26 review (phonograms, spelling, grammar), vocabulary building" }, { label: "Thursday focus", text: "Unit 27 introduction, grammar (interjections), assessment preparation" }] },
    { n: 31, sections: [{ label: "Unit", text: "Unit 27–28: Advanced grammar and vocabulary" }, { label: "Monday focus", text: "Unit 27–28 phonograms and sounds, spelling rules and analysis" }, { label: "Thursday focus", text: "Grammar (interjections, review all parts of speech), vocabulary and dictation" }] },
    { n: 32, sections: [{ label: "Unit", text: "Unit 28–29: End of year review and consolidation" }, { label: "Monday focus", text: "Unit 28–29 comprehensive review (all phonograms, spelling rules, grammar)" }, { label: "Thursday focus", text: "Vocabulary and spelling practice, dictation, final assessments preparation" }] },
    { n: 33, sections: [{ label: "Unit", text: "Unit 29 Part 5 (Assessment), Unit 30 (Optional summer start)" }, { label: "Monday focus", text: "End of spring semester (parent home grade due, all spring work due), Unit 29 Assessment" }, { label: "Thursday focus", text: "Unit 30 introduction (optional summer review), final grammar flash card review" }] },
  ],
};
