// LOE Essentials C — digest notes from RCA's real 2026-2027 lesson-plan doc ("LOE
// Essentials A, B, and C Lesson Plan- 2026-2027 Cascone", shared 2026-08-12),
// paraphrased in the tutor's own words rather than transcribed verbatim — RCA's
// curriculum is explicitly copyrighted, so these are personal pacing/reference notes,
// not a copy of the source text. 6th grade language arts (Logic of English), 30 units
// over ~30 teaching weeks, each following a five-day rhythm (Mon: two new core
// segments; Tue: spelling/phonogram/handwriting review; Wed: grammar; Thu: remaining
// segments + dictation assessment; Fri: corrections/catch-up) — RCA's own Mon/Thu
// center days cover the Monday-intro and Thursday-dictation halves of that rhythm.
// Real 2026-2027 breaks are reflected in the week dates below.

import type { SubjectContent } from "./types";

export const loeEssentialsCContent: SubjectContent = {
  totalWeeks: 30,
  overview:
    "Logic of English Essentials C, 2026-2027 — 30 units over ~30 teaching weeks, integrating phonogram " +
    "mastery, spelling application, grammar fundamentals, vocabulary development, reading comprehension, " +
    "and concurrent cursive handwriting practice. Each unit follows a five-day rhythm: Monday introduces " +
    "two core lesson segments, Tuesday reviews spelling/phonograms/handwriting, Wednesday covers grammar, " +
    "Thursday finishes core segments and runs a dictation assessment (tutors review phonograms first, " +
    "grade on dictation accuracy only), Friday is corrections/catch-up. Dictation is the primary grading " +
    "tool; Essentials C allows 75% credit recovery on timely corrections (within two weeks). Units 13, 14, " +
    "28, and 29 offer optional bonus credit. Pacing note: content below is paraphrased from RCA's real " +
    "2026-2027 doc (pulled 2026-08-12), not last year's placeholder.",

  lessons: [
    { n: 1, sections: [{ label: "Unit 1 — Week 1 (Aug 17-21)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 2, sections: [{ label: "Unit 2 — Week 2 (Aug 24-28)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 3, sections: [{ label: "Unit 3 — Week 3 (Aug 31-4)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 4, sections: [{ label: "Unit 4 — Week 4 (Sep 7-11)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Tuesday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 5, sections: [{ label: "Unit 5 — Week 5 (Sep 14-18)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 6, sections: [{ label: "Unit 6 — Week 6 (Sep 21-25)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 7, sections: [{ label: "Unit 7 — Week 7 (Sep 28-2)", text: "Foundation-building: early phonogram recognition, basic handwriting strokes, spelling and grammar fundamentals introduced." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 8, sections: [{ label: "Unit 8 — Week 8 (Oct 5-9)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Fall Break follows." },
    { n: 9, sections: [{ label: "Unit 9 — Week 9 (Oct 19-23)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Resume after Fall Break." },
    { n: 10, sections: [{ label: "Unit 10 — Week 10 (Oct 26-30)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 11, sections: [{ label: "Unit 11 — Week 11 (Nov 2-6)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 12, sections: [{ label: "Unit 12 — Week 12 (Nov 9-13)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 13, sections: [{ label: "Unit 13 — Week 13 (Nov 16-20)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Thanksgiving Break follows. Optional bonus-credit opportunity available." },
    { n: 14, sections: [{ label: "Unit 14 — Week 14 (Nov 30-4)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Resume after Thanksgiving Break. Optional bonus-credit opportunity available." },
    { n: 15, sections: [{ label: "Unit 15 — Week 15 (Dec 7-11)", text: "Continued phonogram/spelling mastery, advancing grammar concepts; handwriting review through new letter formations." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 16, sections: [{ label: "Unit 16 — Week 16 (Dec 14-18)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "End of fall semester (grades due); Christmas Break follows." },
    { n: 17, sections: [{ label: "Unit 17 — Week 17 (Jan 4-8)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Resume after Christmas Break; spring semester begins." },
    { n: 18, sections: [{ label: "Unit 18 — Week 18 (Jan 11-15)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 19, sections: [{ label: "Unit 19 — Week 19 (Jan 18-22)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 20, sections: [{ label: "Unit 20 — Week 20 (Jan 25-29)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 21, sections: [{ label: "Unit 21 — Week 21 (Feb 1-5)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 22, sections: [{ label: "Unit 22 — Week 22 (Feb 8-12)", text: "Mid-year push on spelling application and sentence-level grammar; handwriting maintenance (no new formal instruction)." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Mid-Winter Break follows." },
    { n: 23, sections: [{ label: "Unit 23 — Week 23 (Feb 22-26)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Resume after Mid-Winter Break." },
    { n: 24, sections: [{ label: "Unit 24 — Week 24 (Mar 1-5)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 25, sections: [{ label: "Unit 25 — Week 25 (Mar 8-12)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 26, sections: [{ label: "Unit 26 — Week 26 (Mar 15-19)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }] },
    { n: 27, sections: [{ label: "Unit 27 — Week 27 (Mar 22-26)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Easter Break follows." },
    { n: 28, sections: [{ label: "Unit 28 — Week 28 (Apr 12-16)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Resume after Easter Break. Optional bonus-credit opportunity available." },
    { n: 29, sections: [{ label: "Unit 29 — Week 29 (Apr 19-23)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Optional bonus-credit opportunity available." },
    { n: 30, sections: [{ label: "Unit 30 — Week 30 (Apr 26-30)", text: "Culminating units: cumulative review, targeted skill reinforcement, optional bonus assessments." }, { label: "Monday", text: "New phonograms/spelling rule + grammar segment introduced; spelling and handwriting practice begins." }, { label: "Thursday", text: "Remaining core segment taught; dictation assessment on this unit's material (tutors review phonograms first, then grade on dictation accuracy)." }], note: "Final dictation of the year; spring grades finalize." },
  ],
};
