// Music 3-4 Year A — real 2026-2027 content from RCA's actual "Music 3-4 Year A" doc
// (docs.google.com/document/d/1U3hmOg3CsUP3ZucsOulB0k6Eodiw5ski8pyffJgPucA), sent by Dr. Jennings
// 2026-08-20 ("Music A lesson plan and music folder" email) and pulled 2026-08-21. This REPLACES
// the previous content here, which was transcribed from a Year B doc (rounds + recorder,
// Essential Elements Recorder Method) pulled 2026-08-09 before "this year is Music A" was known —
// that was the wrong curriculum-year entirely, not just stale. Year A has NO recorder component;
// it's singing (rounds + Latin hymns/Mass chants) plus a composer-study unit (Chopin, Handel,
// Beethoven, Mozart in sequence). The source doc interleaves Year A and Year B composer tracks
// side-by-side every week (so one center doc serves both cohorts) — only the Year A branch is
// kept here.

export type MusicLesson = {
  n: number;
  warmup: string;
  hymnsChants: string;
  composer: string;
  note?: string;
};

export const music34Overview =
  "Music 3-4 Year A: singing (rounds + Latin hymns/Mass chants) and a composer-study unit (Chopin, Handel, Beethoven, Mozart, in that order), one lesson/week, 31 lessons. No recorder in this year (that's Year B). " +
  "Every class follows the same shape — Opening Prayer (Sign of the Cross) -> Choral Warm-up (round) -> Hymns and Chants -> Composer Study -> Closing Prayer. " +
  "Seat boys and girls separately in a chorale arrangement; assign seats with a seating chart.";

export const music34Lessons: MusicLesson[] = [
  { n: 1, warmup: "Teach the round “For Health and Strength.” Sing (or play) it a few times, then encourage students to sing along several times.", hymnsChants: "Introduce “Regina Caeli” This is one of four hymns to Mary that are traditionally assigned to different times of the year. They are sung at the very end of the day, after Compline (Night Prayer). The “Regina Caeli” is sung from Easter until Pentecost. It is a song in which we rejoice with Mary at the Resurrection of her Son and ask for her prayers. Regina Caeli m4a * First, play the song and have the students listen. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? * Give a translation for each line. * Listen to the recording again while the students follow along on their music sheets.", composer: "Listen to The Story of Chopin - Tracks 1-8 (If you don’t have time for all the tracks, continue next week.) Print copies of the picture of Frederic Chopin, found in the Music Resource Folder, for students to color. Have them keep it in their Music Folder." },
  { n: 2, warmup: "Sing “For Health and Strength” several times. Direct students to sing softly or strongly. NOTE on dynamics: It is crucial to help students distinguish loud and soft as controlled volumes of their singing voices. It is helpful to let them know that forte means “strong” in Italian and not loud. They should always be using their singing voice when they sing strongly and you should immediately stop the class if they begin to yell when you sing forte. Using the phrase “make your voice sound like mine” and modeling is very helpful.", hymnsChants: "Continue learning “Regina Caeli.” Regina Caeli m4a * First, play the song and have the students listen. * Then, say the Latin words line-by-line for pronunciation. * Ask the students to echo you and copy your pronunciation. * Listen to the recording again while the students follow along on their music sheets, and sing quietly.", composer: "Listen to The Story of Chopin. Finish tracks 1-8 Have students add a fact about the composer on the back of the picture." },
  { n: 3, warmup: "Sing “For Health and Strength” several times. If the students are confident in singing it, try singing it as around. Have all the students start together and then the tutor softly sings the second part, beginning when the students get to the “2.”", hymnsChants: "Sing “Regina Caeli.” Regina Caeli m4a", composer: "Listen to The Story of Chopin - Tracks 9-15 Have students add a fact about the composer on the back of the picture." },
  { n: 4, warmup: "Sing “For Health and Strength” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Introduce and play the recording of “Kyrie VIII.” This is part of the “Missa de Angelis” (the Mass of the Angels.) Hand out the sheet with Gregorian chant notation and encourage students to follow along with their fingers! Discuss the translation: “Lord, have mercy. Christ, have mercy. Lord, have mercy.” Explain that this chant is Greek, not Latin, because in the early Church, the Mass was said in Greek. Print out a coloring page of St. Gregory the Great. The students may color him as they listen to the Kyrie. Explain that as pope, he made an official collection the chants of the Church which is why they are called “Gregorian.” These chants have been a part of the Catholic Mass at least since the 500’s! Let them know that most of the saints they know and love have sung these chants. Kyrie VIII m4a", composer: "Listen to The Story of Chopin - Finish Tracks 9-15 Have students add a fact about the composer on the back of the picture." },
  { n: 5, warmup: "Sing “For Health and Strength” several times. Then sing it as a round in 2 parts. If the class feels ready, divide into three groups and sing the round in 3 parts!", hymnsChants: "Take out the sheet with Kyrie VIII and ask students what they notice about the music notation. * There are square and diamond notes - both indicate one beat. * Some notes are followed by a dot - this means hold it for two beats. * There are often many notes connected together for one syllable. * The Latin word “bis” means twice. We sing each line twice in the Ordinary Form of the Mass. Traditionally (in the Extraordinary Form) each line is sung tree times. Play the recording of the Kyrie. Encourage students to follow along the music sheet with their finger and sing quietly! Kyrie VIII m4a", composer: "Listen to The Story of Chopin, Tracks 16-24 Have students add a fact about the composer on the back of the picture." },
  { n: 6, warmup: "Introduce the round “Ah, Poor Bird.”", hymnsChants: "Play the recording of the Kyrie. Encourage students to follow along the music sheet with their finger and sing quietly! Kyrie VIII m4a", composer: "Listen to The Story of Chopin - Finish Tracks 16-24 Have students add a fact about the composer on the back of the picture." },
  { n: 7, warmup: "Sing “Ah Poor Bird” several times. Direct the students to sing softly or strongly.", hymnsChants: "Sing “Kyrie VIII.” Kyrie VIII m4a Introduce “Christus Vincit.” The words mean “Christ conquers, Christ reigns, Christ rules.” This is a good song for the Feast of Christ the King! Christus Vincit m4a * First, play the song and have the students listen. * Say the Latin words line-by-line and have them echo you, copying your pronunciation. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. * Listen to the recording again while the students follow along on their music sheets.", composer: "Listen to The Story of Handel, tracks 1-6 Color picture of George Fredric Handel, found in the Music Resource Folder." },
  { n: 8, warmup: "Sing “Ah Poor Bird” several times.", hymnsChants: "Sing “Kyrie VIII” and “Christus Vincit.” Kyrie VIII m4a Christus Vincit m4a", composer: "Listen to The Story of Handel, Finish tracks 1-6 Have students add a fact about the composer on the back of the picture." },
  { n: 9, warmup: "Sing “Ah, Poor Bird” several times. If the students are confident in singing it, try singing it as a round. Have all the students start together and then the tutor softly sings the second part, beginning when the students get to the “2.”", hymnsChants: "Sing “Kyrie VIII” and “Christus Vincit.” Kyrie VIII m4a Christus Vincit m4a", composer: "Listen to The Story of Handel, Tracks 7-13 Have students add a fact about the composer on the back of the picture." },
  { n: 10, warmup: "Sing “Ah, Poor Bird” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Sing “Kyrie VIII.” Christus Vincit m4a Introduce “Resonet in Laudibus.” * First, play the song and have the students listen. * Teach the words of the first two verses of the song: Say the Latin words line-by-line and have them echo you, copying your pronunciation. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. (See next page.) * Listen to the recording again while the students follow along on their music sheets. Resonet in Laudibus m4a", composer: "Listen to The Story of Handel, Finish tracks 7-13 Have students add a fact about the composer on the back of the picture." },
  { n: 11, warmup: "Sing “Ah, Poor Bird” several times. Then sing it as a round in 2 parts.", hymnsChants: "Sing “Christus Vincit.” Christus Vincit m4a Introduce “Resonet in Laudibus.” * First, play the song and have the students listen. * Teach the words of the second two verses of the song: Say the Latin words line-by-line and have them echo you, copying your pronunciation. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. (See previous page.) * Listen to the recording again while the students follow along on their music sheets. Resonet in Laudibus m4a", composer: "Listen to The Story of Handel, Tracks 14-22 Have students add a fact about the composer on the back of the picture." },
  { n: 12, warmup: "Sing “Ah, Poor Bird” several times. Then sing it as a round in 2 parts. If the class feels ready, divide into three groups and sing the round in 3 parts!", hymnsChants: "Sing “Christus Vincit” and “Resonet in Laudibus.” Christus Vincit m4a Resonet in Laudibus m4a", composer: "Listen to The Story of Handel, Tracks 14-22 Have students add a fact about the composer on the back of the picture." },
  { n: 13, warmup: "Teach the round “Jubilate Deo.” Sing (or play) it a few times, then encourage students to sing along several times. Translation: Rejoice in God or Shout with joy to God!", hymnsChants: "Sing “Resonet in Laudibus.” Resonet in Laudibus m4a Introduce “Puer Natus.” First, play the song and have the students listen. Can the students recognize what this song is about? Listen to the recording again while the students follow along on their music sheets. Puer Natus mp3", composer: "Listen to The Story of Handel, Tracks 23-29 Have students add a fact about the composer on the back of the picture." },
  { n: 14, warmup: "Sing “Jubilate Deo” several times. Direct students to sing softly or strongly.", hymnsChants: "Sing “Resonet in Laudibus.” Resonet in Laudibus m4a Continue introducing “Puer Natus.” Puer Natus mp3 * First, play the song and have the students listen. * Teach the words of several verses of the song: Say the Latin words line-by-line and have them echo you, copying your pronunciation. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. ( * Play the song again and have the students sing along.", composer: "Listen to The Story of Handel, Finish tracks 23-29 Have students add a fact about the composer on the back of the picture." },
  { n: 15, warmup: "Sing “Jubilate Deo” several times. If the students are confident in singing it, try singing it as around. Have all the students start together and then the tutor softly sings the second part, beginning when the students get to the “2.”", hymnsChants: "Sing “Resonet in Laudibus” and “Puer Natus.” Resonet in Laudibus m4a Puer Natus mp3", composer: "Guess the Composer - Play songs from both composers and see if they can guess who wrote it, Chopin or Handel?" },
  { n: 16, warmup: "Sing “Jubilate Deo” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Sing “Puer Natus.” Puer Natus mp3 Introduce and play the recording of the “Sanctus VIII.” Hand out the sheet with Gregorian chant notation and encourage students to follow along with their fingers. Talk about the translation: “Holy, holy, holy, Lord, God of hosts! Heaven and earth are full of your glory! Hosanna in the Highest! Blessed is He Who comes in the name of the Lord! Hosanna in the Highest!” Sanctus VIII m4a", composer: "Guess the Composer - Play songs from both composers and see if they can guess who wrote it, Chopin or Handel?" },
  { n: 17, warmup: "Sing “Jubilate Deo” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Sing “Puer Natus” and “Sanctus VIII.” Puer Natus mp3 Sanctus VIII m4a", composer: "Listen to The Story of Beethoven, tracks 1-3 Have students color the picture of Beethoven, found in the Music Resource Folder." },
  { n: 18, warmup: "Sing “Jubilate Deo” several times. Then sing it as a round in 2 parts. If the class feels ready, divide into three groups and sing the round in 3 parts!", hymnsChants: "Sing “Puer Natus” and “Sanctus VIII.” Puer Natus mp3 Sanctus VIII m4a", composer: "Listen to The Story of Beethoven, tracks 4-6 Have students add a fact about the composer on the back of the picture." },
  { n: 19, warmup: "Introduce the round “Row, Row, Row Your Boat.”", hymnsChants: "Sing “Sanctus VIII.” Sanctus VIII m4a Introduce “Stabat Mater.” This hymn is used during the Stations of the Cross and helps us share the sorrow of Mary as she stood at the foot of the Cross. First, play the song and have the students listen. Then listen to the recording again while the students follow along on their music sheets. Stabat Mater m4a", composer: "Listen to The Story of Beethoven, tracks 7-9 Have students add a fact about the composer on the back of the picture." },
  { n: 20, warmup: "Sing “Row, Row, Row Your Boat” several times. If you like, encourage students to come up with hand motions to go with the song.", hymnsChants: "Sing “Sanctus VIII.” Sanctus VIII m4a Continue introducing “Stabat Mater.” Stabat Mater m4a * First, play the song and have the students listen. * Teach the words of several verses of the song: Say the Latin words line-by-line and have them echo you, copying your pronunciation. (Don’t worry about learning all the verses!) * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. * Listen to the recording again while the students follow along on their music sheets.", composer: "Listen to The Story of Beethoven, tracks 10-12 Have students add a fact about the composer on the back of the picture." },
  { n: 21, warmup: "Sing “Row, Row, Row Your Boat” several times. If the students are confident in singing it, try singing it as a round. Have all the students start together and then the tutor softly sings the second part, beginning when the students get to the “2.”", hymnsChants: "Sing “Sanctus VIII” and “Stabat Mater.” Sanctus VIII m4a Stabat Mater m4a", composer: "Listen to The Story of Beethoven, tracks 13-15 Have students add a fact about the composer on the back of the picture." },
  { n: 22, warmup: "Sing “Row, Row, Row Your Boat” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Sing “Stabat Mater.” Stabat Mater m4a introduce the “Agnus Dei” from the Missa de Angelis. Agnus Dei VIII m4a Review the words and pronunciation of the chant and encourage students to listen as they follow on their song sheets.", composer: "Listen to The Story of Beethoven, tracks 16-19 Have students add a fact about the composer on the back of the picture." },
  { n: 23, warmup: "Sing “Row, Row, Row Your Boat” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Sing “Agnus Dei” Agnus Dei VIII m4a", composer: "Listen to The Story of Mozart - Tracks 1-3 Have students color the picture of Mozart, found in the Music Resource Folder." },
  { n: 24, warmup: "Sing “Row, Row, Row Your Boat” several times. Then sing it as a round in 2 parts. If the class feels ready, divide into three groups and sing the round in 3 parts!", hymnsChants: "Sing “Agnus Dei” Agnus Dei VIII m4a", composer: "Listen to The Story of Mozart - Tracks 4-6 Have students add a fact about the composer on the back of the picture." },
  { n: 25, warmup: "Teach the new round. Walking, Walking", hymnsChants: "Sing “Agnus Dei” Agnus Dei VIII m4a Introduce “Tantum Ergo.” This hymn is sung when the Blessed Sacrament is exposed in church. It was written by St. Thomas Aquinas. First, play the song and have the students listen. Then listen to the recording again while the students follow along on their music sheets. Tantum Ergo m4a", composer: "Listen to The Story of Mozart - Tracks 7-9 Have students add a fact about the composer on the back of the picture." },
  { n: 26, warmup: "Sing “Walking, Walking” several times. If you like, have students act out the actions of the song as they sing.", hymnsChants: "Sing “Agnus Dei” Agnus Dei VIII m4a Continue introducing “Tantum Ergo.” Tantum Ergo m4a * First, play the song and have the students listen. * Teach the words of the song: Say the Latin words line-by-line and have them echo you, copying your pronunciation. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. * Listen to the recording again while the students follow along on their music sheets. Tantum Ergo Tantum ergo Sacramentum veneremur cernui: et antiquum documentum novo cedat ritui: praestet fides supplementum sensuum defectui. Down in adoration falling, Lo! the sacred Host we hail; Lo! o'er ancient forms departing, newer rites of grace prevail; faith for all defects supplying, where the feeble senses fail. Genitori, Genitoque laus et iubilatio, salus, honor, virtus quoque sit et benedictio: procedenti ab utroque compar sit laudatio. Amen. To the everlasting Father, and the Son who reigns on high, with the Holy Ghost proceeding forth from Each eternally, be salvation, honor, blessing, might and endless majesty. Amen.", composer: "Listen to The Story of Mozart - Tracks 10-12 Have students add a fact about the composer to the back of the coloring page." },
  { n: 27, warmup: "Sing “Walking, Walking” several times. If the students are confident in singing it, try singing it as a round. Have all the students start together and then the tutor softly sings the second part, beginning when the students get to the “2.”", hymnsChants: "Sing “Agnus Dei” and “Tantum Ergo.” Agnus Dei VIII m4a Tantum Ergo m4a", composer: "Listen to The Story of Mozart - Tracks 13-15 Have students add a fact about the composer to the back of the coloring page." },
  { n: 28, warmup: "Sing “Sweetly Sings the Donkey” several times. If the students are confident in singing it, try singing it as a round. Have all the students start together and then the tutor softly sings the second part, beginning when the students get to the “2.”", hymnsChants: "Sing “Tantum Ergo.” Tantum Ergo m4a Introduce “Ave Maria.” This is the “Hail Mary” prayer. Ave Maria m4a * First, play the song and have the students listen. * Teach the words of the song: Say the Latin words line-by-line and have them echo you, copying your pronunciation. * Ask students: Do you see any words similar to our English words? Do you recognize any words from your Latin class? Give a translation for each line. * Listen to the recording again while the students follow along on their music sheets.", composer: "Listen to The Story of Mozart - Tracks 16-18 Have students add a fact about the composer to the back of coloring page.", note: "Coordinate a Marian hymn with Music 5-6 / Music 1-2 for the May Crowning ceremony on Field Day." },
  { n: 29, warmup: "Sing “Walking, Walking” several times. Try singing it as a round in 2 parts. Divide the class into two groups (perhaps placing less confident singers with the tutor) and have the second group start when the first group gets to the “2.”", hymnsChants: "Sing “Tantum Ergo” and “Ave Maria.” Tantum Ergo m4a Ave Maria m4a", composer: "Listen to The Story of Mozart - Tracks 19-21 Have students add a fact about the composer to the back of the coloring page." },
  { n: 30, warmup: "Sing “Walking, Walking” several times. Then sing it as a round in 2 parts. If the class feels ready, divide into three groups and sing the round in 3 parts!", hymnsChants: "Sing “Tantum Ergo” and “Ave Maria.” Tantum Ergo m4a Ave Maria m", composer: "Listen to The Story of Mozart - Tracks 22-24 Have students add a fact about the composer to the back of the coloring page." },
  { n: 31, warmup: "Sing “Walking, Walking” several times. Then sing it as a round in 2 parts. If the class feels ready, divide into three groups and sing the round in 3 parts!", hymnsChants: "Sing “Tantum Ergo” and “Ave Maria.” Tantum Ergo m4a Ave Maria m", composer: "Listen to The Story of Mozart - Tracks 22-24 Have students add a fact about the composer to the back of the coloring page." },
];

// Adapter into the generic SubjectContent schema used by LessonViewer/rca-chat — kept
// as a thin wrapper rather than retyping all 31 lessons in the generic shape by hand.
import type { SubjectContent } from "./types";

export const music34Content: SubjectContent = {
  overview: music34Overview,
  lessons: music34Lessons.map((l) => ({
    n: l.n,
    sections: [
      { label: "Choral Warm-up", text: l.warmup },
      { label: "Hymns and Chants", text: l.hymnsChants },
      { label: "Composer Study", text: l.composer },
    ],
    note: l.note,
  })),
};
