// PE 5-6 — original curriculum, not RCA's (RCA has never sent one for this class, either
// year — flagged as a real gap in earlier sessions). Jacob leads this one solo (unlike PE
// 1-2, where he's Harmon's assistant — deliberately not building that one; not his to plan).
// Built per his own spec: basic games + stretches + running, minimal equipment (a handful
// of playground/kickball balls, maybe cones/jump ropes — nothing that needs a real gym).
// Room is "Cafe" per the schedule (not "Gym," which is PE 1-2's room) — written assuming a
// cafeteria/multipurpose space, cleared of tables, with SOME outdoor or adjacent open-space
// option for the bigger games (kickball, soccer). If there's truly no outdoor access on
// Thursdays, the kickball/soccer weeks need a real look — flagged, not guessed past.
//
// One lesson per real teaching week, Thursday only (33-week RCA calendar, same weeks/dates
// as the other 6th-grade classes — closure weeks match history-6.ts). Themed multi-week
// units so skills actually build week to week instead of a new random game every time:
// kickball (hand-eye kicking/catching + teamwork) opens and closes the year as the anchor
// unit per Jacob's own example; between are tag games, relay/agility, four square, jump
// rope, basic soccer, basic basketball-with-a-playground-ball, and a fitness-circuit block.
// Every entry: warm-up, main activity (with real rules, not just a name), cool-down,
// equipment. Draft — Jacob asked to look through and get back before this is "live."

import type { SubjectContent } from "./types";

export const pe56Content: SubjectContent = {
  overview:
    "PE 5-6, original curriculum (RCA has not provided one). 33 Thursday sessions, 1:00-1:45pm, " +
    "Cafe. Equipment stays minimal on purpose — a few playground/kickball balls, jump ropes, and " +
    "cones if available; nothing that needs a real gym. Every session: dynamic warm-up + a short " +
    "run, a main game with real teamwork/skill goals, a cool-down stretch. Units build across " +
    "several weeks instead of a new random game every time: Kickball (hand-eye kicking & " +
    "catching + teamwork) opens and closes the year; between are tag/agility games, four square, " +
    "jump rope, basic soccer, basic basketball with a playground ball, and a fitness-circuit " +
    "block. DRAFT — Jacob asked to review before treating this as final.",
  totalWeeks: 33,
  lessons: [
    { n: 1, sections: [{ label: "Week 1 (Aug 17-21) — Thursday", text: "Kickball Unit, Day 1 — Hand-eye kicking & catching + teamwork. Warm-up: arm circles, leg swings, toe touches (3 min), then one lap (or 2 lengths of the room/space) at a jog. Main: teach kickball basics from scratch — pitching (rolled, not thrown), kicking a moving ball, the base path, and fielding a grounder with two hands. Split into two teams of even size; play 3 short innings, everyone rotates position each inning so nobody's stuck in one spot. Emphasize catching as a TEAM skill — cheer teammates on, no blaming missed catches. Cool-down: standing quad stretch + hamstring stretch, 30 sec each side. Equipment: 1 kickball, 4 bases (or cones/beanbags as base markers)." }] },
    { n: 2, sections: [{ label: "Week 2 (Aug 24-28) — Thursday", text: "Kickball Unit, Day 2 — Fielding & throwing to a base. Warm-up: jumping jacks x20, high knees across the room, arm circles. Main: 10-min skill station rotation in pairs — (1) roll-and-field grounders, (2) underhand toss-and-catch at increasing distance, (3) throwing to a 'base' target (a cone or hoop) from 15 feet. Then a full kickball game, same teams as last week, now scoring outs by throwing to first base instead of just tagging. Cool-down: seated forward fold + side stretches. Equipment: 1-2 kickballs, cones/bases." }] },
    { n: 3, sections: [{ label: "Week 3 (Aug 31-4) — Thursday", text: "Kickball Unit, Day 3 — Strategy & positions. Warm-up: dynamic stretch circuit (butt kicks, high knees, side shuffles) + one lap. Main: assign real positions (pitcher, catcher, 1st/2nd/3rd, outfield) and briefly explain each one's job before playing a full game. Between innings, huddle each team for 30 seconds on 'what's our plan on defense' — the actual teamwork goal for this unit. Cool-down: calf stretch against a wall + deep breathing, 1 min. Equipment: 1 kickball, bases." }] },
    { n: 4, sections: [{ label: "Week 4 (Sep 7-11) — Thursday", text: "Relay Races & Agility, Day 1. Warm-up: high knees, butt kicks, lateral shuffles down and back. Main: set up 2-3 relay lanes with cones (10-15 feet apart). Run a rotation of relay types — straight sprint relay, backward-walk relay, bear-crawl relay, and a balance relay (carry a beanbag on a hand/book without dropping it). Teams of 4-5, everyone goes at least twice. Cool-down: standing stretches, focus on calves and quads after all the running. Equipment: cones, 1-2 beanbags or small books." }] },
    { n: 5, sections: [{ label: "Week 5 (Sep 14-18) — Thursday", text: "Relay Races & Agility, Day 2 — Ladder/cone footwork. Warm-up: jog + ankle circles + walking lunges across the room. Main: lay out cones in a zigzag and a straight line 'ladder' pattern (feet just have to hit between cones, no real agility ladder needed). Kids run each pattern a few times for speed, then run it as a relay in teams. Finish with one all-class tag-relay game — team relay where each runner has to tag the next before they can go. Cool-down: partner stretch — seated back-to-back, gentle twist. Equipment: 8-10 cones." }] },
    { n: 6, sections: [{ label: "Week 6 (Sep 21-25) — Thursday", text: "Tag Games, Day 1 — Freeze Tag & Blob Tag. Warm-up: jog a lap, then dynamic stretches (leg swings, arm crosses). Main: Freeze Tag first (2 taggers, tagged players freeze with arms out until a teammate crawls under their arms to unfreeze them — keeps everyone moving and cooperating). Then Blob Tag — one tagger starts, every kid they tag joins hands with them and the 'blob' grows until only the blob is left; only the two kids on the ends of the blob can tag. Cool-down: stretch circle, everyone leads one stretch. Equipment: none." }] },
    { n: 7, sections: [{ label: "Week 7 (Sep 28-2) — Thursday", text: "Tag Games, Day 2 — Sharks & Minnows. Warm-up: high knees, butt kicks, a lap. Main: mark two end lines with cones. 2-3 'sharks' start in the middle; everyone else ('minnows') lines up on one end line and has to sprint across to the other side without getting tagged. Anyone tagged becomes a shark for the next round. Play until only 1-2 minnows are left, then reset. Great for straight-line sprinting and reaction speed. Cool-down: standing hamstring + quad stretch, slow breathing. Equipment: 4 cones for end lines." }] },
    { n: 8, sections: [{ label: "Week 8 (Oct 5-9) — Thursday", text: "Four Square / Wall Ball, Day 1. Warm-up: arm circles, wrist circles (hands do the work today), one lap. Main: if space allows, chalk or tape a 4-square grid (or use existing lines) and run a rotation so every kid gets real square time — teach the basic rules (serve underhand and low, ball must bounce once in the square, out-of-bounds/holding/carrying = you're out and rotate to the back of the line). If no floor space for a grid, run 'wall ball' instead against a clear wall — bounce/catch rally, add a rule (clap before catching, one-bounce only) each round. Cool-down: shoulder + wrist stretches. Equipment: 1-2 playground balls, tape/chalk if available." }], note: "Fall Break follows." },
    { n: 9, sections: [{ label: "Week 9 (Oct 19-23) — Thursday", text: "Four Square / Wall Ball, Day 2 — House rules & tournament. Warm-up: jog, dynamic stretch. Main: quick class vote on 1-2 'house rules' (no-catch, cherry bomb, etc.) to add, then run a bracket-style mini tournament in groups of 4-6 so everyone plays multiple rounds instead of standing in one long line. Cool-down: partner stretch, seated straddle reach. Equipment: 1-2 playground balls." }], note: "Resume after Fall Break." },
    { n: 10, sections: [{ label: "Week 10 (Oct 26-30) — Thursday", text: "Jump Rope & Coordination, Day 1. Warm-up: light jog, ankle bounces, arm swings. Main: teach/review basic jump rope form (individual ropes) — two-foot jump, alternate-foot jump, then try a slow long-rope 'ocean waves' as a group activity (one big rope swung low, kids step over it, working up to jumping it). Station rotation between individual ropes and the group long-rope if only 1-2 long ropes available. Cool-down: calf stretches (a lot of jumping today), ankle rolls. Equipment: individual jump ropes (as many as available), 1 long rope if possible." }] },
    { n: 11, sections: [{ label: "Week 11 (Nov 2-6) — Thursday", text: "Jump Rope & Coordination, Day 2 — Challenges & Double Dutch intro. Warm-up: jog + jumping jacks. Main: individual jump-rope challenges (most jumps in 30 sec, jump-and-clap, criss-cross for kids who are ready) run as friendly personal-best stations, not a competition against each other. If two long ropes are available, introduce a very basic Double Dutch entry attempt (walk-in first, no jumping required yet). Cool-down: seated calf/ankle stretch, deep breaths. Equipment: individual jump ropes, 2 long ropes if available (optional)." }] },
    { n: 12, sections: [{ label: "Week 12 (Nov 9-13) — Thursday", text: "Basic Soccer Skills, Day 1 — Dribbling & control. Warm-up: jog with the ball at feet (loosely, just getting a feel for it), leg swings. Main: teach basic dribbling (inside/outside of foot, keep the ball close). Cone dribbling course — weave through 6-8 cones, one kid at a time, others cheer/count. Finish with a simple 'keep it in the square' game — everyone dribbles their own ball inside a marked area without letting it leave. Cool-down: quad + hip flexor stretch. Equipment: 1 soccer ball per 2-3 kids if possible (or rotate on 1-2 balls), cones." }] },
    { n: 13, sections: [{ label: "Week 13 (Nov 16-20) — Thursday", text: "Basic Soccer Skills, Day 2 — Passing & small-sided games. Warm-up: jog + dynamic leg stretches. Main: partner passing drill (inside-of-foot pass, stop-and-control the return) for 10 min, then split into small teams (3v3 or 4v4 depending on numbers/space) for short-sided games with small goals (cones) — everyone touches the ball more in a small game than an 11-a-side one. Cool-down: standing quad/calf stretch. Equipment: 1-2 soccer balls, cones for goals." }] },
    { n: 14, sections: [{ label: "Week 14 (Nov 30-4) — Thursday", text: "Fitness Circuit, Day 1. Warm-up: jog + jumping jacks + arm circles. Main: 5-6 stations, 90 seconds each, short rest between — jumping jacks, wall sit, standing long jump (measure/mark, not a max-effort competition), sit-ups or crunches on a mat/towel, high-knee jog in place, plank hold (modified/knees OK). Rotate in small groups so nobody's idle long. Frame it as 'how do you feel after' not a fitness test. Cool-down: full-body stretch — hamstrings, quads, shoulders, 45 sec each. Equipment: mats/towels if available (optional), a stopwatch/phone timer." }] },
    { n: 15, sections: [{ label: "Week 15 (Dec 7-11) — Thursday", text: "Team Games Mix, Day 1 — Capture the Flag (indoor-scaled) or Steal the Bacon. Warm-up: jog, dynamic stretch. Main: if space allows two 'territories,' play a scaled-down Capture the Flag (a beanbag or cone as the 'flag,' freeze-and-rescue tag rule instead of jail for safety in a smaller space). If space is tight, play Steal the Bacon instead — two teams numbered off, call a number, that pair races to grab the object in the middle and get it back to their line without being tagged. Cool-down: partner stretch. Equipment: 1-2 beanbags/cones as flags/objects." }] },
    { n: 16, sections: [{ label: "Week 16 (Dec 14-18) — Thursday", text: "Kickball Unit, Review Game — fall-semester wrap-up. Warm-up: full dynamic stretch routine (by now the kids should be able to lead pieces of it). Main: full kickball game using everything from Weeks 1-3 (real positions, throwing to bases, team defense huddles). Let the kids pick captains and pick teams as a small leadership/fairness exercise. Cool-down: stretch circle + quick 'what was your favorite game this semester' share-around. Equipment: 1 kickball, bases." }], note: "End of fall semester. Christmas Break follows." },
    { n: 17, sections: [{ label: "Week 17 (Jan 4-8) — Thursday", text: "Basic Basketball, Day 1 — Dribbling with a playground ball. Warm-up: jog + wrist/arm circles. Main: no real basketball hoop assumed — teach dribbling control (one hand, then switching hands, walking-while-dribbling) with a playground ball, cone-weave dribble course, and a 'dribble tag' game (everyone dribbles their own ball while trying to knock away others' — last ball still bouncing wins the round). Cool-down: shoulder + forearm stretch. Equipment: 1 ball per 2-3 kids if possible, cones." }] },
    { n: 18, sections: [{ label: "Week 18 (Jan 11-15) — Thursday", text: "Basic Basketball, Day 2 — Passing & a simple target game. Warm-up: jog + arm circles. Main: chest-pass and bounce-pass partner drill, then a target-toss game — stack cones or set out hoops/boxes at different distances, teams take turns tossing/rolling a ball to land in the highest-value target, closest to real basket-shooting practice without needing a hoop. Cool-down: standing stretch, shoulders and calves. Equipment: 1-2 balls, cones/boxes as targets." }] },
    { n: 19, sections: [{ label: "Week 19 (Jan 18-22) — Thursday", text: "Team Games Mix, Day 2 — Sharks & Minnows variation + relay refresher. Warm-up: jog, dynamic stretch. Main: replay Sharks & Minnows with a twist (minnows must skip or hop instead of run one round, sharks can only tag with a foam ball toss instead of a hand-tag another round) to keep a familiar game fresh. Finish with a quick relay-race refresher from Weeks 4-5. Cool-down: partner stretch. Equipment: cones, 1 soft ball (optional twist)." }] },
    { n: 20, sections: [{ label: "Week 20 (Jan 25-29) — Thursday", text: "Jump Rope, Day 3 — Personal-best day. Warm-up: light jog, ankle bounces. Main: revisit individual jump rope skills from Weeks 10-11, track personal-best 30-second counts on a simple chart (effort/improvement, not a leaderboard), try any new tricks kids want to attempt (criss-cross, high-step). Long-rope group jumping if ropes are available. Cool-down: calf stretch, ankle circles, deep breathing. Equipment: individual jump ropes, paper/chart to log personal bests." }] },
    { n: 21, sections: [{ label: "Week 21 (Feb 1-5) — Thursday", text: "Fitness Circuit, Day 2 — new stations. Warm-up: jog + jumping jacks. Main: fresh circuit — mountain climbers, standing broad jump, sit-and-reach flexibility check, shuttle run between two cones, plank hold, and a partner wheelbarrow-walk relay if space allows. Rotate stations in small groups. Cool-down: full stretch routine. Equipment: cones, mats/towels if available." }], note: "Mid-Winter Break follows." },
    { n: 22, sections: [{ label: "Week 22 (Feb 8-12) — Thursday", text: "Basic Soccer, Day 3 — Shooting fundamentals. Warm-up: jog with light ball touches, dynamic stretch. Main: teach a simple instep shot on a stationary ball at a cone-marked target, everyone gets repeated shooting reps in pairs/small groups (one shoots, one retrieves/resets, switch). Close with a quick shoot-and-count game — most targets hit in 5 tries. Cool-down: quad + hip stretch." }], note: "Resume after Mid-Winter Break." },
    { n: 23, sections: [{ label: "Week 23 (Feb 22-26) — Thursday", text: "Basic Soccer, Day 4 — Small-sided games. Warm-up: jog, dynamic stretch. Main: set up two small goals (cones) and split into 3v3/4v4 games, emphasizing passing before shooting (a goal only counts if it followed at least one pass) — puts Weeks 12-13 and 22's skills together in real play. Cool-down: quad + hip stretch. Equipment: 1-2 soccer balls, cones for goals." }] },
    { n: 24, sections: [{ label: "Week 24 (Mar 1-5) — Thursday", text: "Team Games Mix, Day 3 — Team-choice day. Warm-up: jog, dynamic stretch led by student volunteers. Main: let the class vote between 2-3 games already learned this year (kickball, four square, sharks & minnows, capture-the-flag-style) — real ownership/teamwork-building exercise, and a good gauge of what's actually landing well before planning the rest of spring. Cool-down: stretch circle. Equipment: whatever the chosen game needs (already on hand)." }] },
    { n: 25, sections: [{ label: "Week 25 (Mar 8-12) — Thursday", text: "Relay Races & Agility, Day 3 — Obstacle course. Warm-up: jog, dynamic stretch. Main: build a simple obstacle course with cones/existing furniture-safe layout — weave through cones, hop over a line, crawl under a table edge (if safe/available), balance-carry a beanbag across, sprint the last stretch. Run it as a relay in teams, then let kids try to beat their own time solo. Cool-down: full-body stretch, extra time on legs. Equipment: cones, 1-2 beanbags, stopwatch/phone timer." }], note: "Easter Break follows (two weeks)." },
    { n: 26, sections: [{ label: "Week 26 (Mar 15-19) — Thursday", text: "Kickball Unit, Advanced Day — new positions & rules wrinkle. Warm-up: full dynamic stretch routine + a lap. Main: full kickball game, but rotate EVERY player through every position across innings (not just fixed positions) so nobody specializes — real cross-skill teamwork goal. Add one new rule this week (e.g. bunts count, or a 'ghost runner' rule) to keep it fresh for kids who've played all year. Cool-down: stretch circle. Equipment: 1 kickball, bases." }], note: "Resume after Easter Break." },
    { n: 27, sections: [{ label: "Week 27 (Mar 22-26) — Thursday", text: "Tag Games, Day 3 — Team tag / Capture-style hybrid. Warm-up: jog, dynamic stretch. Main: 'Team Tag' — split into two teams, each with a home zone; players from opposing teams can tag each other in neutral territory (tagged = frozen until rescued by a teammate's touch, same safety rule as Week 6's freeze tag). Adds a team-strategy layer on top of a game they already know well. Cool-down: partner stretch. Equipment: cones to mark zones." }] },
    { n: 28, sections: [{ label: "Week 28 (Apr 12-16) — Thursday", text: "Basic Basketball, Day 3 — Mini tournament. Warm-up: jog + arm circles. Main: dribble/pass warm-up drills from Weeks 17-18, then a short small-group 'mini tournament' using the target-toss scoring game from Week 18 — teams rotate through, best total score wins the round, everyone plays multiple short rounds. Cool-down: shoulder/arm stretch. Equipment: 1-2 balls, cones/boxes as targets." }] },
    { n: 29, sections: [{ label: "Week 29 (Apr 19-23) — Thursday", text: "Fitness Circuit, Day 3 — Field Day prep. Warm-up: jog + jumping jacks. Main: run circuit stations that double as Field Day event practice — standing broad jump, shuttle run, relay hand-off practice, a simple tug-of-war (if a rope is available) in small groups. Cool-down: full stretch routine. Equipment: cones, rope (optional, for tug-of-war), stopwatch/phone timer." }] },
    { n: 30, sections: [{ label: "Week 30 (Apr 26-30)", text: "No PE session this week — Feast of the Ascension falls on Thursday, RCA closed." }] },
    { n: 31, sections: [{ label: "Week 31 (May 3-7) — Thursday", text: "Relay Races & Agility, Day 4 — Field Day practice. Warm-up: jog, dynamic stretch. Main: run actual Field Day relay formats (sack-hop-style single-leg hop if no sacks, three-legged pairs, egg-and-spoon substitute with a beanbag on a book) so kids know the events going in. Cool-down: legs-focused full stretch. Equipment: cones, beanbags/books, whatever Field Day equipment is available to borrow early." }] },
    { n: 32, sections: [{ label: "Week 32 (May 10-14) — Thursday", text: "Team Games Mix, Day 4 — Class-favorite rematch. Warm-up: jog, student-led dynamic stretch. Main: replay the class's single favorite game from the whole year (poll quickly at the start) as a proper full-length game, not a rushed round. Cool-down: stretch circle, brief reflection on favorite moments from the year. Equipment: whatever the chosen game needs." }] },
    { n: 33, sections: [{ label: "Week 33 (May 17-21) — Thursday", text: "Last PE session of the year — student-choice review day / informal awards. Warm-up: light jog, full stretch. Main: let the class choose 2-3 short favorite games to replay one last time; close with simple, kind shout-outs (most improved, best teamwork, etc.) rather than a competitive award — keep it positive and low-stakes to end the year. No new content. Equipment: whatever the chosen games need." }] },
  ],
};
