// Teaching/refresher notes for Saxon 7/6 — built for JACOB's own understanding and
// teaching prep, same motivation as latin-teacher-guide.ts (Jacob, 2026-09-09: "did u
// use those resources to give me better learning and teaching and personal growth in
// those areas, particularly latin?" — this is the Saxon half of that answer).
//
// IMPORTANT SOURCING NOTE — different from latin-teacher-guide.ts: the photographed
// Saxon material (~/Desktop/MT;RCAmaterial) was ONLY the book's table of contents and
// front matter, not a teacher's-guide-with-scripts the way First Form Latin's Teacher
// Guide was. So this file does NOT claim to transcribe or paraphrase any real Saxon
// pedagogy — it's original explanations of the underlying math concepts (standard,
// widely-taught material, same "nobody owns how cross-multiplication works" status as
// latin-core.ts's standard grammar facts) plus common, well-established student
// mistakes for each concept, written to help Jacob refresh his own understanding
// before teaching it. Deliberately NOT exhaustive across all 120 lessons — skips the
// straightforward arithmetic/review lessons an adult doesn't need a refresher on, and
// covers only the topics genuinely worth a personal refresher (geometry formulas,
// proportions/ratios, exponents, probability, algebra, etc.). Cross-referenced against
// saxon-76.ts's own lesson-topic annotations for which lesson numbers actually exist
// and what they're really called.

export type SaxonTeacherNote = {
  /** Lesson number, or e.g. "Investigation 6" for investigations. */
  key: string;
  title: string;
  concept: string;
  watchFor: string;
};

export const saxonTeacherGuide: SaxonTeacherNote[] = [
  { key: "19", title: "Factors, Prime Numbers", concept: "A factor of a number divides it evenly with no remainder. A prime number has exactly two factors (1 and itself) — 1 is NOT prime (it only has one factor), and 2 is the only even prime.", watchFor: "Students often forget to check both 1 and the number itself when listing factors, or mistakenly call 1 prime." },
  { key: "20", title: "Greatest Common Factor (GCF)", concept: "The GCF of two numbers is the largest number that divides both evenly — found by listing factors of each and picking the largest shared one, or by comparing prime factorizations.", watchFor: "Students confuse GCF with LCM (Lesson 30) — GCF is always ≤ both numbers, LCM is always ≥ both numbers; that size check alone catches most mix-ups." },
  { key: "Investigation 2", title: "Investigating Fractions with Manipulatives", concept: "Hands-on fraction bars/circles building physical intuition for equivalent fractions and comparing fraction size before the abstract common-denominator rules take over.", watchFor: "Don't skip the physical modeling even if it feels slow — students who never build this intuition tend to make sign/size errors on fraction comparison later that pure algorithm practice doesn't fix." },
  { key: "23", title: "Ratio", concept: "A ratio compares two quantities (3:4, or 3/4) — order matters, and a ratio is NOT the same as a fraction of a whole unless the two quantities are literally part and whole.", watchFor: "Students flip ratio order (writing 4:3 for \"3 cats to 4 dogs\") — always ask \"which number came first in the sentence.\"" },
  { key: "27", title: "Measures of a Circle", concept: "Radius, diameter (2× radius), and circumference are the three measurements to keep straight before Pi is introduced formally at Lesson 47.", watchFor: "Students mix up radius and diameter constantly — a quick \"radius reaches the center, diameter crosses all the way through\" phrase helps." },
  { key: "Investigation 3", title: "Measuring and Drawing Angles with a Protractor", concept: "Physical protractor skills: aligning the base line, reading the correct scale (inner vs. outer numbers), and estimating before measuring to catch a wrong-scale reading.", watchFor: "The single most common protractor error is reading the wrong number scale (e.g. reading 120° as 60°) — teach \"estimate first\" as the built-in error check." },
  { key: "30", title: "Least Common Multiple (LCM), Reciprocals", concept: "LCM is the smallest number that's a multiple of both given numbers (used to find common denominators). A reciprocal flips a fraction (3/4 → 4/3); multiplying a number by its reciprocal always gives 1.", watchFor: "Students find A common multiple instead of the LEAST one (e.g. using 24 as the LCM of 4 and 6 instead of 12) — remind them to check if a smaller shared multiple exists." },
  { key: "33", title: "Writing Percents as Fractions, Part 1", concept: "Percent literally means \"per hundred\" — 45% = 45/100, which then simplifies like any fraction.", watchFor: "Students forget to simplify after converting, or misplace the decimal point when going percent → decimal → fraction." },
  { key: "38", title: "Squares and Square Roots", concept: "Squaring a number multiplies it by itself; square root asks \"what number times itself gives this?\" They're inverse operations, and most square roots (beyond perfect squares like 4, 9, 16, 25) aren't whole numbers.", watchFor: "Students confuse √9 (=3) with 9² (=81) purely from mixing up which direction the operation goes — anchor it with \"root undoes square.\"" },
  { key: "47", title: "Circumference, Pi", concept: "Pi (≈3.14) is the fixed ratio of any circle's circumference to its diameter — circumference = π × diameter (or 2πr). It's the same for every circle regardless of size, which is the actually surprising fact worth stating explicitly.", watchFor: "Students plug the radius into the diameter formula (or vice versa) — always confirm which one a given problem provides before applying C = πd." },
  { key: "Investigation 6", title: "Attributes of Geometric Solids", concept: "Faces (flat surfaces), edges (where two faces meet), and vertices (corners) — Euler's formula (faces + vertices − edges = 2) holds for any convex solid, a nice \"why does this always work\" moment if students notice the pattern.", watchFor: "Students miscount hidden faces/edges/vertices on a 3D drawing — physical models (or even a real box) beat a flat sketch for this lesson." },
  { key: "58", title: "Probability and Chance", concept: "Probability = favorable outcomes / total possible outcomes, always between 0 (impossible) and 1 (certain), often expressed as a fraction, decimal, or percent.", watchFor: "Students think a fair coin \"owes\" them a result after a streak (the gambler's fallacy) — each flip is independent regardless of prior flips, worth addressing directly since it's a genuinely common misconception, not just a careless error." },
  { key: "60", title: "Polygons", concept: "A polygon is any closed shape made of straight line segments; \"regular\" means all sides and angles are equal. Naming follows side count (pentagon=5, hexagon=6, octagon=8, etc.).", watchFor: "Students assume any 5-sided shape is automatically \"regular\" — regularity is about equal sides AND angles, not just the side count." },
  { key: "64", title: "Classifying Quadrilaterals", concept: "The quadrilateral family tree matters: a square is a rectangle (all angles 90°) AND a rhombus (all sides equal); a rectangle and rhombus are both parallelograms; not every parallelogram is a rectangle or rhombus.", watchFor: "Students treat these as separate, unrelated categories instead of a nested hierarchy — a Venn diagram on the board fixes this faster than a definition list." },
  { key: "65", title: "Prime Factorization, Division by Primes, Factor Trees", concept: "Every whole number > 1 breaks down into a unique product of prime numbers (the Fundamental Theorem of Arithmetic) — a factor tree is just a visual way to find that breakdown by repeatedly dividing by primes.", watchFor: "Students stop a factor tree branch too early on a composite number (e.g. leaving 4 as a \"final\" branch instead of continuing to 2×2) — the rule is: keep splitting until every branch ends in a prime." },
  { key: "69", title: "Complementary and Supplementary Angles", concept: "Complementary angles sum to 90°; supplementary angles sum to 180°. (\"C comes before S in the alphabet, 90 comes before 180\" is a real memory hook if a mnemonic helps.)", watchFor: "Students swap the two definitions constantly — tie \"complementary\" to a right angle (90°, like the corner of a square) and \"supplementary\" to a straight line (180°) as visual anchors." },
  { key: "71", title: "Parallelograms", concept: "Opposite sides are parallel AND equal in length; opposite angles are equal; consecutive angles are supplementary (add to 180°). Area = base × height (NOT base × slant side).", watchFor: "The #1 error: using the slanted side length instead of the perpendicular height when calculating area — always confirm which measurement is actually perpendicular to the base." },
  { key: "Investigation 7", title: "The Coordinate Plane", concept: "Ordered pairs (x, y) locate points relative to two perpendicular number lines (axes) meeting at the origin (0,0). The four quadrants each have a distinct sign pattern for (x,y).", watchFor: "Students plot (x,y) backwards, moving up/down first instead of left/right first — \"over then up\" (x before y) as a fixed verbal habit prevents most of these errors." },
  { key: "73", title: "Exponents, Writing Decimal Numbers as Fractions Part 2", concept: "An exponent tells you how many times to multiply the base by itself (2³ = 2×2×2 = 8, NOT 2×3=6) — the most common exponent misconception is treating it as multiplication by the exponent instead of repeated multiplication.", watchFor: "Explicitly correct \"2³ = 6\" if it comes up — it's an extremely common first-encounter mistake, not a sign of weak math ability." },
  { key: "80", title: "Using Scale Factor to Solve Ratio Problems", concept: "A scale factor multiplies every dimension of a figure by the same ratio to create a similar (same-shape, different-size) figure — used in maps, models, and blueprints.", watchFor: "Students apply the scale factor to only one dimension (e.g. scaling length but not width) — stress that EVERY linear measurement scales by the same factor, but area scales by the factor SQUARED." },
  { key: "Investigation 8", title: "Geometric Construction of Bisectors", concept: "A perpendicular bisector uses compass-and-straightedge construction (not a protractor) to find the exact midpoint and 90° angle of a segment — an angle bisector splits an angle into two equal halves the same way.", watchFor: "Students want to \"eyeball\" the construction instead of trusting the compass-arc method — the whole point of the lesson is that the geometric method is exact, not estimated." },
  { key: "82", title: "Volume of a Rectangular Prism", concept: "Volume = length × width × height (or base area × height) — measures the 3D space inside a solid, in cubic units.", watchFor: "Students confuse volume's cubic units (in³, cm³) with area's square units — always check the unit label matches the dimension count of the calculation." },
  { key: "83", title: "Proportions", concept: "A proportion states two ratios are equal (a/b = c/d) — the backbone of scale, unit conversion, and percent problems for the rest of the year.", watchFor: "Students set up the ratio with mismatched units on top/bottom (e.g. miles/hours = hours/miles instead of miles/hours = miles/hours) — always label units when setting up the proportion, not just numbers." },
  { key: "85", title: "Using Cross Products to Solve Proportions", concept: "In a/b = c/d, cross-multiplying gives a×d = b×c — this works because multiplying both sides of the equation by both denominators cancels them out; it's not a magic trick, it's algebra.", watchFor: "Students cross-multiply an expression that ISN'T actually a proportion (e.g. a fraction being added, not set equal to another fraction) — the technique only applies to two fractions set equal to each other." },
  { key: "86", title: "Area of a Circle", concept: "Area = πr² — note it's the RADIUS squared, not the diameter, which is the most common formula mix-up in this lesson.", watchFor: "Students plug the diameter into r² directly — always confirm radius vs. diameter before squaring, same trap as Lesson 47's circumference formula." },
  { key: "89", title: "Estimating Square Roots", concept: "For a non-perfect-square, find the two perfect squares it falls between (√50 is between √49=7 and √64=8, so ≈7.1) — a genuinely useful mental-math skill, not just test prep.", watchFor: "Students guess wildly instead of anchoring to the nearest perfect squares — always name the two bracketing perfect squares first." },
  { key: "90", title: "Measuring Turns", concept: "A full turn = 360°, half turn = 180°, quarter turn = 90° — connects angle measure to real rotational movement (clock hands, compass directions).", watchFor: "Students confuse clockwise/counterclockwise direction when a problem specifies it — physically miming the turn with a hand often resolves this faster than explaining it verbally." },
  { key: "Investigation 9", title: "Experimental Probability", concept: "Experimental probability (from actually running trials and counting results) can differ from theoretical probability (calculated from possible outcomes) — especially with few trials; they converge as trial count grows (the Law of Large Numbers, informally).", watchFor: "Students expect experimental results to exactly match theoretical predictions every time — a small number of trials SHOULD show variance; that's not an error in the experiment." },
  { key: "91", title: "Geometric Formulas", concept: "A consolidation lesson pulling together area/perimeter/volume formulas learned so far — worth Jacob's own quick self-check that he has all of them (rectangle, triangle, circle, parallelogram, rectangular prism) fluent before teaching a review lesson built entirely around recall.", watchFor: "Since this is a formula-recall lesson, the actual teaching risk is presenting it as \"just memorize a list\" instead of re-deriving a couple formulas live (e.g. triangle area as half a parallelogram) so the formulas feel connected, not arbitrary." },
  { key: "92", title: "Expanded Notation with Exponents; Order of Operations with Exponents; Powers of Fractions", concept: "Order of operations (PEMDAS) places exponents before multiplication/division — a fraction raised to a power applies the exponent to BOTH numerator and denominator: (2/3)² = 4/9, not 2/9 or 4/3.", watchFor: "Students apply the exponent only to the numerator of a fraction — explicitly show (2/3)² as (2/3)×(2/3), not 2²/3." },
  { key: "96", title: "Functions, Graphing Functions", concept: "A function assigns exactly one output to each input — a table of (x,y) pairs or a rule like y = 2x + 1. Graphing plots those pairs to visualize the relationship.", watchFor: "Students think any table of numbers is automatically a function — the actual test is whether any input maps to MORE than one output (if so, it's not a function)." },
  { key: "97", title: "Transversals", concept: "A transversal is a line crossing two (often parallel) lines, creating 8 angles with specific relationships: corresponding angles are equal, alternate interior angles are equal, co-interior (same-side interior) angles are supplementary.", watchFor: "Students guess at angle relationships instead of using the parallel-lines-cut-by-a-transversal rules — worth drilling the vocabulary (corresponding/alternate/co-interior) explicitly since the rules are useless without knowing which pair you're looking at." },
  { key: "98", title: "Sum of the Angle Measures of Triangles and Quadrilaterals", concept: "Every triangle's interior angles sum to 180°; every quadrilateral's sum to 360° (provable by splitting any quadrilateral into two triangles).", watchFor: "A great moment to actually show the quadrilateral-splits-into-two-triangles proof live rather than just stating 360° as a fact — it's one of the more satisfying \"why is that true\" moments available at this level." },
  { key: "100", title: "Algebraic Addition of Integers", concept: "Adding integers with different signs: find the difference of their absolute values, keep the sign of the larger absolute value (e.g. -7 + 3 = -4, since 7>3 and the 7 was negative).", watchFor: "Students default to just adding the numbers and guessing the sign — the reliable rule is \"same signs, add and keep the sign; different signs, subtract and keep the sign of the bigger number.\"" },
  { key: "Investigation 10", title: "Compound Experiments", concept: "The probability of two independent events BOTH happening is the product of their individual probabilities (e.g. two coin flips both heads = 1/2 × 1/2 = 1/4) — a tree diagram or table makes all outcomes visible.", watchFor: "Students add probabilities instead of multiplying them for \"and\" (both happening) scenarios — multiplication is for \"and,\" addition is for \"or\" (mutually exclusive events)." },
  { key: "106", title: "Two-Step Equations", concept: "Solving requires undoing operations in reverse order of how they were applied — e.g. for 3x + 5 = 20, subtract 5 first, THEN divide by 3 (undo addition before undoing multiplication).", watchFor: "Students try to divide by 3 first, before isolating the term with the variable — reinforce \"undo in reverse PEMDAS order\" as the general strategy for any multi-step equation." },
  { key: "108", title: "Transformations", concept: "Translations (slide), reflections (flip), and rotations (turn) all preserve a shape's size and form — only its position/orientation changes. Dilation (a scale-factor resize) is the one transformation that DOES change size.", watchFor: "Students conflate reflection and rotation (both can look similar for simple shapes) — always ask \"did it flip across a line, or spin around a point?\"" },
  { key: "109", title: "Corresponding Parts, Similar Triangles", concept: "Similar triangles have the same shape (equal corresponding angles) but not necessarily the same size — corresponding sides are all in the same ratio (the scale factor).", watchFor: "Students match up sides/angles in the wrong order between two similar triangles — always match corresponding parts by their position in the similarity statement (e.g. △ABC ~ △DEF means A↔D, B↔E, C↔F, not by eyeballing which sides \"look similar\")." },
  { key: "112", title: "Multiplying and Dividing Integers", concept: "Same-sign integers multiply/divide to a positive result; different-sign integers give a negative result — this is a fixed rule, not something that varies by the specific numbers involved.", watchFor: "Students apply the addition/subtraction sign rules (Lesson 100) to multiplication/division by mistake — these are genuinely different rule sets and worth explicitly contrasting side by side." },
  { key: "114", title: "Unit Multipliers", concept: "A unit multiplier is a fraction equal to 1 (like 12 in/1 ft) used to convert units by multiplying — since it equals 1, multiplying by it changes the units without changing the actual quantity.", watchFor: "Students set up the unit multiplier upside down (canceling the wrong unit) — the unit you want to CANCEL should be in the position (top or bottom) opposite where it appears in the original quantity." },
  { key: "116", title: "Compound Interest", concept: "Compound interest earns interest on both the original principal AND on previously earned interest — unlike simple interest, the amount grows faster over time because each period's interest is calculated on a larger base.", watchFor: "A genuinely good moment for a real personal-finance tie-in (savings accounts, loans) — students retain this concept far better with a real dollar example than with the formula alone." },
  { key: "120", title: "Volume of a Cylinder", concept: "Volume = πr²h — literally \"circle area (πr²) × height,\" the same base-times-height logic as a rectangular prism, just with a circular base.", watchFor: "Students forget to square the radius (using πrh instead of πr²h) — tie it back explicitly to the circle-area formula from Lesson 86 so it's recognized as the same base area, not a brand-new formula." },
  { key: "Investigation 12", title: "Platonic Solids", concept: "There are exactly five: tetrahedron, cube, octahedron, dodecahedron, icosahedron — each made of one type of regular polygon, with the same number of faces meeting at every vertex. A nice closing-of-the-year fact: geometers proved 2,000+ years ago that exactly five (no more, no fewer) can exist.", watchFor: "A good place to let curiosity lead rather than drilling facts — the \"why only five\" proof (based on angle sums around a vertex) is genuinely elegant and worth mentioning even if not required material." },
];

// Lesson numbers match as a whole word (so "11" doesn't false-match inside "111");
// investigations match their exact phrase.
export function getSaxonNotesForWeekText(weekText: string): SaxonTeacherNote[] {
  const found: SaxonTeacherNote[] = [];
  for (const note of saxonTeacherGuide) {
    if (note.key.startsWith("Investigation")) {
      if (weekText.includes(note.key)) found.push(note);
    } else {
      const re = new RegExp(`\\b${note.key}\\b`);
      if (re.test(weekText)) found.push(note);
    }
  }
  return found;
}
