// Saxon 7/6 — digest notes from RCA's real 2026-2027 lesson-plan doc ("Saxon 76 lesson
// plan- 2026-2027 Cascone", shared 2026-08-12), paraphrased in the tutor's own words
// rather than transcribed verbatim — RCA's curriculum is explicitly copyrighted, so
// these are personal pacing/reference notes, not a copy of the source text.
// 120 lessons over ~33 teaching weeks (Aug 17, 2026 - late May 2027), alternating
// center-taught days (concept intro + speed drills) with home-practice days. Ten
// cumulative Math Tests, twelve Investigations (hands-on/exploratory), and roughly a
// dozen Homework Checks are spread across the year. Each lesson opens with a short
// faith-reflection tie-in per the source doc. Real 2026-2027 breaks are reflected in
// the week dates below (Labor Day, Fall Break, Thanksgiving, Christmas, Mid-Winter,
// Easter) plus late-April CLT testing and a year-end field day.

import type { SubjectContent } from "./types";

export const saxon76Content: SubjectContent = {
  totalWeeks: 33,
  overview:
    "Saxon Math 7/6, 2026-2027 — 120 lessons over ~33 teaching weeks. Daily structure: teach new " +
    "concepts, problem sets, mixed practice; each lesson opens with a brief faith-based reflection tied " +
    "to the math content. Ten cumulative Math Tests (20 questions/100 points, corrections allowed within " +
    "two weeks for up to 75% credit, one retake permitted), twelve Investigations (hands-on exploratory " +
    "activities), and homework checks (parent-initialed packets) are spread through the year. CLT " +
    "practice/testing lands in late April; the year wraps with a field day. Pacing note: content below " +
    "is paraphrased from RCA's real 2026-2027 doc (pulled 2026-08-12), not last year's placeholder.",

  lessons: [
    { n: 1, sections: [{ label: "Week 1 (Aug 17-21)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 2, sections: [{ label: "Week 1 (Aug 17-21)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 3, sections: [{ label: "Week 1 (Aug 17-21)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 4, sections: [{ label: "Week 1 (Aug 17-21)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Investigation 1 (hands-on exploratory activity)" },
    { n: 5, sections: [{ label: "Week 2 (Aug 24-28)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 6, sections: [{ label: "Week 2 (Aug 24-28)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 7, sections: [{ label: "Week 2 (Aug 24-28)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 8, sections: [{ label: "Week 2 (Aug 24-28)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Homework Check 1" },
    { n: 9, sections: [{ label: "Week 3 (Aug 31-4)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 10, sections: [{ label: "Week 3 (Aug 31-4)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 11, sections: [{ label: "Week 3 (Aug 31-4)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 1 (cumulative material to date)" },
    { n: 12, sections: [{ label: "Week 4 (Sep 7-11)", text: "Tuesday — teach new concepts, daily problem set." }] },
    { n: 13, sections: [{ label: "Week 4 (Sep 7-11)", text: "Wednesday — teach new concepts, mixed practice." }] },
    { n: 14, sections: [{ label: "Week 4 (Sep 7-11)", text: "Thursday — continue lesson, problem set." }] },
    { n: 15, sections: [{ label: "Week 4 (Sep 7-11)", text: "Friday — complete lesson, problem set; prepare homework packet." }], note: "Investigation 2 (hands-on exploratory activity)" },
    { n: 16, sections: [{ label: "Week 5 (Sep 14-18)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 17, sections: [{ label: "Week 5 (Sep 14-18)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 18, sections: [{ label: "Week 5 (Sep 14-18)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 19, sections: [{ label: "Week 5 (Sep 14-18)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Homework Check 2" },
    { n: 20, sections: [{ label: "Week 6 (Sep 21-25)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 21, sections: [{ label: "Week 6 (Sep 21-25)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 22, sections: [{ label: "Week 6 (Sep 21-25)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 2 (cumulative material to date)" },
    { n: 23, sections: [{ label: "Week 7 (Sep 28-2)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 24, sections: [{ label: "Week 7 (Sep 28-2)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 25, sections: [{ label: "Week 7 (Sep 28-2)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 26, sections: [{ label: "Week 7 (Sep 28-2)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Investigation 3 (hands-on exploratory activity)" },
    { n: 27, sections: [{ label: "Week 8 (Oct 5-9)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 28, sections: [{ label: "Week 8 (Oct 5-9)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 29, sections: [{ label: "Week 8 (Oct 5-9)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 30, sections: [{ label: "Week 8 (Oct 5-9)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Fall Break follows. Homework Check 3" },
    { n: 31, sections: [{ label: "Week 9 (Oct 19-23)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 32, sections: [{ label: "Week 9 (Oct 19-23)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 33, sections: [{ label: "Week 9 (Oct 19-23)", text: "Wednesday — continue lesson, problem set." }], note: "Resume after Fall Break. Math Test 3 (cumulative material to date)" },
    { n: 34, sections: [{ label: "Week 10 (Oct 26-30)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 35, sections: [{ label: "Week 10 (Oct 26-30)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 36, sections: [{ label: "Week 10 (Oct 26-30)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 37, sections: [{ label: "Week 10 (Oct 26-30)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Investigation 4 (hands-on exploratory activity)" },
    { n: 38, sections: [{ label: "Week 11 (Nov 2-6)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 39, sections: [{ label: "Week 11 (Nov 2-6)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 40, sections: [{ label: "Week 11 (Nov 2-6)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 41, sections: [{ label: "Week 11 (Nov 2-6)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Homework Check 4" },
    { n: 42, sections: [{ label: "Week 12 (Nov 9-13)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 43, sections: [{ label: "Week 12 (Nov 9-13)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 44, sections: [{ label: "Week 12 (Nov 9-13)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 4 (cumulative material to date)" },
    { n: 45, sections: [{ label: "Week 13 (Nov 16-20)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 46, sections: [{ label: "Week 13 (Nov 16-20)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 47, sections: [{ label: "Week 13 (Nov 16-20)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 48, sections: [{ label: "Week 13 (Nov 16-20)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Thanksgiving Break follows. Investigation 5 (hands-on exploratory activity)" },
    { n: 49, sections: [{ label: "Week 14 (Nov 30-4)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 50, sections: [{ label: "Week 14 (Nov 30-4)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 51, sections: [{ label: "Week 14 (Nov 30-4)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 52, sections: [{ label: "Week 14 (Nov 30-4)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Resume after Thanksgiving Break. Homework Check 5" },
    { n: 53, sections: [{ label: "Week 15 (Dec 7-11)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 54, sections: [{ label: "Week 15 (Dec 7-11)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 55, sections: [{ label: "Week 15 (Dec 7-11)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 5 (cumulative material to date)" },
    { n: 56, sections: [{ label: "Week 16 (Dec 14-18)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 57, sections: [{ label: "Week 16 (Dec 14-18)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 58, sections: [{ label: "Week 16 (Dec 14-18)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 59, sections: [{ label: "Week 16 (Dec 14-18)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "End of fall semester; Christmas Break follows. Investigation 6 (hands-on exploratory activity)" },
    { n: 60, sections: [{ label: "Week 17 (Jan 4-8)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 61, sections: [{ label: "Week 17 (Jan 4-8)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 62, sections: [{ label: "Week 17 (Jan 4-8)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 63, sections: [{ label: "Week 17 (Jan 4-8)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Resume after Christmas Break; spring semester begins. Homework Check 6" },
    { n: 64, sections: [{ label: "Week 18 (Jan 11-15)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 65, sections: [{ label: "Week 18 (Jan 11-15)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 66, sections: [{ label: "Week 18 (Jan 11-15)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 6 (cumulative material to date)" },
    { n: 67, sections: [{ label: "Week 19 (Jan 18-22)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 68, sections: [{ label: "Week 19 (Jan 18-22)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 69, sections: [{ label: "Week 19 (Jan 18-22)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 70, sections: [{ label: "Week 19 (Jan 18-22)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Investigation 7 (hands-on exploratory activity)" },
    { n: 71, sections: [{ label: "Week 20 (Jan 25-29)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 72, sections: [{ label: "Week 20 (Jan 25-29)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 73, sections: [{ label: "Week 20 (Jan 25-29)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 74, sections: [{ label: "Week 20 (Jan 25-29)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Homework Check 7" },
    { n: 75, sections: [{ label: "Week 21 (Feb 1-5)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 76, sections: [{ label: "Week 21 (Feb 1-5)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 77, sections: [{ label: "Week 21 (Feb 1-5)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 7 (cumulative material to date)" },
    { n: 78, sections: [{ label: "Week 22 (Feb 8-12)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 79, sections: [{ label: "Week 22 (Feb 8-12)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 80, sections: [{ label: "Week 22 (Feb 8-12)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 81, sections: [{ label: "Week 22 (Feb 8-12)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Mid-Winter Break follows. Investigation 8 (hands-on exploratory activity)" },
    { n: 82, sections: [{ label: "Week 23 (Feb 22-26)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 83, sections: [{ label: "Week 23 (Feb 22-26)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 84, sections: [{ label: "Week 23 (Feb 22-26)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 85, sections: [{ label: "Week 23 (Feb 22-26)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Resume after Mid-Winter Break. Homework Check 8" },
    { n: 86, sections: [{ label: "Week 24 (Mar 1-5)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 87, sections: [{ label: "Week 24 (Mar 1-5)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 88, sections: [{ label: "Week 24 (Mar 1-5)", text: "Wednesday — continue lesson, problem set." }], note: "Math Test 8 (cumulative material to date)" },
    { n: 89, sections: [{ label: "Week 25 (Mar 8-12)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 90, sections: [{ label: "Week 25 (Mar 8-12)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 91, sections: [{ label: "Week 25 (Mar 8-12)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 92, sections: [{ label: "Week 25 (Mar 8-12)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Investigation 9 (hands-on exploratory activity)" },
    { n: 93, sections: [{ label: "Week 26 (Mar 15-19)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 94, sections: [{ label: "Week 26 (Mar 15-19)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 95, sections: [{ label: "Week 26 (Mar 15-19)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 96, sections: [{ label: "Week 26 (Mar 15-19)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Homework Check 9" },
    { n: 97, sections: [{ label: "Week 27 (Mar 22-26)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 98, sections: [{ label: "Week 27 (Mar 22-26)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 99, sections: [{ label: "Week 27 (Mar 22-26)", text: "Wednesday — continue lesson, problem set." }], note: "Easter Break follows. Math Test 9 (cumulative material to date)" },
    { n: 100, sections: [{ label: "Week 28 (Apr 12-16)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 101, sections: [{ label: "Week 28 (Apr 12-16)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 102, sections: [{ label: "Week 28 (Apr 12-16)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 103, sections: [{ label: "Week 28 (Apr 12-16)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Resume after Easter Break. Investigation 10 (hands-on exploratory activity)" },
    { n: 104, sections: [{ label: "Week 29 (Apr 19-23)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 105, sections: [{ label: "Week 29 (Apr 19-23)", text: "Tuesday — teach new concepts, mixed practice." }], note: "CLT testing (3rd-6th grade & 7th-10th grade); no new lesson beyond the two below." },
    { n: 106, sections: [{ label: "Week 30 (Apr 26-30)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 107, sections: [{ label: "Week 30 (Apr 26-30)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 108, sections: [{ label: "Week 30 (Apr 26-30)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 109, sections: [{ label: "Week 30 (Apr 26-30)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Math Test 10 (cumulative material to date)" },
    { n: 110, sections: [{ label: "Week 31 (May 3-7)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 111, sections: [{ label: "Week 31 (May 3-7)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 112, sections: [{ label: "Week 31 (May 3-7)", text: "Wednesday — continue lesson, problem set." }], note: "Investigation 11 (hands-on exploratory activity)" },
    { n: 113, sections: [{ label: "Week 32 (May 10-14)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 114, sections: [{ label: "Week 32 (May 10-14)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 115, sections: [{ label: "Week 32 (May 10-14)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 116, sections: [{ label: "Week 32 (May 10-14)", text: "Thursday — complete lesson, problem set; prepare homework packet." }], note: "Homework Check 10" },
    { n: 117, sections: [{ label: "Week 33 (May 17-21)", text: "Monday — teach new concepts, daily problem set." }] },
    { n: 118, sections: [{ label: "Week 33 (May 17-21)", text: "Tuesday — teach new concepts, mixed practice." }] },
    { n: 119, sections: [{ label: "Week 33 (May 17-21)", text: "Wednesday — continue lesson, problem set." }] },
    { n: 120, sections: [{ label: "Week 33 (May 17-21)", text: "Thursday — complete lesson, problem set; prepare homework packet." }] },
  ],
};
