// AUTO-GENERATED by scripts/gen-ff-vocab.py from Jacob's real First Form Latin quiz
// doc. Vocab locked to Lessons 1-12 (verified range). Do not hand-edit.

export type QuizVocab = {
  lessons: number[];
  vocab: { english: string; latin: string }[];
  sayingLatin: string | null;
};

export const FF_QUIZ_VOCAB: QuizVocab[] = [
  { lessons: [30, 31], vocab: [], sayingLatin: null },
  { lessons: [1], vocab: [{english:"I call", latin:"voco"}, {english:"I carry", latin:"porto"}, {english:"I give", latin:"do"}, {english:"I guard, keep", latin:"servo"}, {english:"I love, like", latin:"amo"}, {english:"I prepare", latin:"paro"}, {english:"I beg, pray", latin:"oro"}, {english:"I stand", latin:"sto"}, {english:"I swim", latin:"nato"}, {english:"I wash", latin:"lavo"}], sayingLatin: "in choro recitemus" },
  { lessons: [2, 3], vocab: [{english:"I walk", latin:"ambulo"}, {english:"I err, wander", latin:"erro"}, {english:"I fight", latin:"pugno"}, {english:"I help", latin:"juvo"}, {english:"I set free", latin:"libero"}, {english:"I seize", latin:"occupo"}, {english:"I praise", latin:"laudo"}, {english:"I shout", latin:"clamo"}, {english:"I live in, dwell", latin:"habito"}, {english:"I sail", latin:"navigo"}], sayingLatin: null },
  { lessons: [4, 5], vocab: [{english:"to err, wander", latin:"errare"}, {english:"to fight", latin:"pugnare"}, {english:"to give", latin:"dare"}, {english:"to guard, keep", latin:"servare"}, {english:"to praise", latin:"laudare"}, {english:"to sail", latin:"navigare"}, {english:"to swim", latin:"natare"}, {english:"to tell", latin:"narrare"}, {english:"to work", latin:"laborare"}], sayingLatin: null },
  { lessons: [6], vocab: [{english:"to adore", latin:"adorare"}, {english:"to overcome, surpass", latin:"superare"}, {english:"to call", latin:"vocare"}, {english:"to plow", latin:"arare"}, {english:"to carry", latin:"portare"}, {english:"to prepare", latin:"parare"}, {english:"to greet", latin:"salutare"}, {english:"to set free", latin:"liberare"}, {english:"to help", latin:"juvare"}, {english:"to stand", latin:"stare"}, {english:"to love, like", latin:"amare"}, {english:"to wash", latin:"lavare"}], sayingLatin: null },
  { lessons: [7, 8], vocab: [{english:"always", latin:"semper"}, {english:"never", latin:"numquam"}, {english:"often", latin:"saepe"}, {english:"today", latin:"hodie"}, {english:"tomorrow", latin:"cras"}, {english:"yesterday", latin:"heri"}], sayingLatin: "Errare est humanum." },
  { lessons: [9, 10], vocab: [{english:"to change", latin:"mutare"}, {english:"to deny", latin:"negare"}, {english:"to accuse", latin:"accusare"}, {english:"to hope", latin:"sperare"}, {english:"to think", latin:"putare"}, {english:"to fly", latin:"volare"}, {english:"to doubt", latin:"dubitare"}, {english:"to report", latin:"nuntiare"}, {english:"to blame", latin:"culpare"}, {english:"to create", latin:"creare"}, {english:"to show, point out", latin:"demonstrare"}, {english:"to attack", latin:"oppugnare"}, {english:"to explore", latin:"explorare"}, {english:"to wound", latin:"vulnerare"}], sayingLatin: "Semper fidelis." },
  { lessons: [11, 12], vocab: [{english:"often", latin:"saepe"}, {english:"never", latin:"numquam"}, {english:"tomorrow", latin:"cras"}, {english:"now", latin:"nunc"}, {english:"to ask", latin:"rogare"}, {english:"to doubt", latin:"dubitare"}, {english:"to hide", latin:"celare"}, {english:"to delight, please", latin:"delectare"}], sayingLatin: "Ora et labora." },
  { lessons: [14, 15], vocab: [], sayingLatin: "Roma Aeterna." },
  { lessons: [16, 17], vocab: [], sayingLatin: "ante bellum" },
  { lessons: [18, 19], vocab: [], sayingLatin: "Mater Italiae, Roma" },
  { lessons: [20], vocab: [], sayingLatin: "Anno Domini (A.D.)" },
  { lessons: [21, 22], vocab: [], sayingLatin: "alma mater" },
  { lessons: [23, 24], vocab: [], sayingLatin: "Caput Mundi" },
  { lessons: [25, 26], vocab: [], sayingLatin: "Carpe diem." },
  { lessons: [27, 29], vocab: [], sayingLatin: "Video et taceo." },
  { lessons: [30, 31], vocab: [], sayingLatin: "Cave canem." },
];
