#!/usr/bin/env python3
"""Convert existing Praxis diagnostic banks + the verified seed set into a
typed TS module for Meta Tutor. Idempotent; safe to re-run."""
import json, os, re

BANKS = "/Users/scones/classpilot/exam-prep/praxis-7001/diagnostic/banks"
SEED = "/Users/scones/projects/meta-tutor/scripts/praxis-seed.json"
OUT = "/Users/scones/projects/meta-tutor/src/lib/praxis/questions.ts"

# bank filename -> subtest key
FILE_SUB = {"reading": "reading", "math": "math", "social": "social", "science": "science"}

def esc(s):
    if s is None:
        return None
    return str(s).replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

out = []

# 1) existing diagnostic banks: {sub,q,opts,a,exp}
for fname, sub in FILE_SUB.items():
    path = os.path.join(BANKS, f"{fname}.json")
    if not os.path.exists(path):
        continue
    data = json.load(open(path))
    for i, item in enumerate(data, 1):
        out.append({
            "id": f"b-{sub}-{i}",
            "subtest": sub,
            "topic": item.get("topic"),
            "passage": item.get("passage"),
            "question": item["q"],
            "options": item["opts"],
            "answer": item["a"],
            "explanation": item.get("exp", ""),
            "verified": True,
        })

# 2) verified seed set: {id,subtest,topic,verified,passage?,q,choices,answer,explain}
if os.path.exists(SEED):
    seed = json.load(open(SEED)).get("questions", [])
    for item in seed:
        out.append({
            "id": f"s-{item['id']}",
            "subtest": item["subtest"],
            "topic": item.get("topic"),
            "passage": item.get("passage"),
            "question": item["q"],
            "options": item["choices"],
            "answer": item["answer"],
            "explanation": item.get("explain", ""),
            "verified": bool(item.get("verified", True)),
        })

# sanity: answer index in range
bad = [q for q in out if not (0 <= q["answer"] < len(q["options"]))]
assert not bad, f"answer index out of range: {[q['id'] for q in bad]}"

def ts_obj(q):
    parts = [f'id:"{q["id"]}"', f'subtest:"{q["subtest"]}"']
    if q.get("topic"):
        parts.append(f'topic:`{esc(q["topic"])}`')
    if q.get("passage"):
        parts.append(f'passage:`{esc(q["passage"])}`')
    parts.append(f'question:`{esc(q["question"])}`')
    opts = ",".join(f'`{esc(o)}`' for o in q["options"])
    parts.append(f'options:[{opts}]')
    parts.append(f'answer:{q["answer"]}')
    parts.append(f'explanation:`{esc(q["explanation"])}`')
    parts.append(f'verified:{"true" if q["verified"] else "false"}')
    return "  { " + ", ".join(parts) + " }"

header = (
    "// AUTO-GENERATED by ~/projects/praxis-grinder/gen_questions_ts.py\n"
    "// Source: existing diagnostic banks (classpilot/exam-prep/praxis-7001)\n"
    "// + verified seed set. Re-run the generator to regenerate; do not hand-edit.\n"
    'import { PraxisQuestion } from "./types";\n\n'
    "export const PRAXIS_QUESTIONS: PraxisQuestion[] = [\n"
)
body = ",\n".join(ts_obj(q) for q in out)
open(OUT, "w").write(header + body + "\n];\n")

counts = {}
for q in out:
    counts[q["subtest"]] = counts.get(q["subtest"], 0) + 1
print(f"wrote {len(out)} questions -> {OUT}")
print("by subtest:", counts)
