#!/usr/bin/env python3
# Regenerate src/lib/ff-latin/vocab-data.ts from Jacob's real First Form Latin quiz doc.
# Source: ~/Desktop/MT_RCAmaterial/first-form-latin-quizzes.txt (plain-text export of the
# Google Doc of RCA-adapted quizzes + answer keys). Vocab is parsed from the KEY sections;
# it is locked to Lessons 1-12 where the source format parses cleanly and was hand-verified
# against the keys — the declension-heavy later lessons need a further verified pass.
# Paradigm drills do NOT come from here (they come from latin-grammar-charts.ts).
#
# Usage: python3 scripts/gen-ff-vocab.py
import re, json, os

SRC = os.path.expanduser("~/Desktop/MT_RCAmaterial/first-form-latin-quizzes.txt")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "ff-latin", "vocab-data.ts")
LAT = r"[a-zāēīōūăĕĭŏŭjv]"
BLOCK = {"perf", "pres", "pre", "present", "stem"}

def key_sections(lines):
    segs, cur = [], None
    for ln in lines:
        s = ln.strip().lstrip("\t").strip()
        if re.match(r"^Lessons?\s+([\d &]+?)\s+Quiz\b.*-\s*KEY\s*$", s, re.I):
            if cur: segs.append(cur)
            nums = [int(x) for x in re.findall(r"\d+", re.match(r"^Lessons?\s+([\d &]+?)\s+Quiz", s, re.I).group(1))]
            cur = {"lessons": nums, "lines": []}
        elif re.match(r"^Lessons?\s+[\d &]+?\s+Quiz\b", s, re.I) and "KEY" not in s.upper() and cur:
            segs.append(cur); cur = None
        elif cur is not None:
            cur["lines"].append(ln)
    if cur: segs.append(cur)
    return [x for x in segs if len(x["lines"]) > 5]

def parse_vocab(block):
    out, seen = [], set()
    for ln in block:
        for m in re.finditer(rf"([A-Za-z][A-Za-z,&\-\s]*?[A-Za-z\)])\s*_{{2,}}\s*({LAT}+(?:\s{LAT}+)?)_*", ln):
            eng = re.sub(r"^\s*\d+\.\s*", "", m.group(1)).strip()
            lat = m.group(2).strip()
            if "recite" in lat.lower() or not re.match(rf"^{LAT}+$", lat) or lat in BLOCK:
                continue
            if "," in eng and re.search(r"(are|ere|ire|us|vi)\b", eng):
                continue
            if not (1 <= len(lat) <= 20 and 2 <= len(eng) <= 40):
                continue
            k = (eng.lower(), lat.lower())
            if k in seen: continue
            seen.add(k); out.append({"english": eng, "latin": lat})
    return out

def parse_saying(block):
    t = "\n".join(block)
    m = re.search(r"(?:Let us[^_\n]*?|Saying[^_\n]*?|Latin Saying[^_\n]*?)_{3,}\s*([^\n_]+)", t)
    return re.sub(r"[_\s]+$", "", m.group(1)).strip() if m and m.group(1).strip() else None

def main():
    lines = open(SRC, encoding="utf-8").read().replace("\r", "").split("\n")
    quizzes = []
    for s in key_sections(lines):
        L = max(s["lessons"])
        quizzes.append({
            "lessons": s["lessons"],
            "vocab": parse_vocab(s["lines"]) if L <= 12 else [],  # verified range
            "sayingLatin": parse_saying(s["lines"]),
        })
    rows = []
    for q in quizzes:
        v = ", ".join("{english:%s, latin:%s}" % (json.dumps(x["english"]), json.dumps(x["latin"])) for x in q["vocab"])
        say = "null" if not q["sayingLatin"] else json.dumps(q["sayingLatin"])
        rows.append("  { lessons: %s, vocab: [%s], sayingLatin: %s }," % (json.dumps(q["lessons"]), v, say))
    header = ('// AUTO-GENERATED by scripts/gen-ff-vocab.py from Jacob\'s real First Form Latin quiz\n'
              '// doc. Vocab locked to Lessons 1-12 (verified range). Do not hand-edit.\n\n'
              'export type QuizVocab = {\n  lessons: number[];\n'
              '  vocab: { english: string; latin: string }[];\n  sayingLatin: string | null;\n};\n\n'
              'export const FF_QUIZ_VOCAB: QuizVocab[] = [\n')
    open(OUT, "w").write(header + "\n".join(rows) + "\n];\n")
    print("wrote", OUT, "-", sum(len(q["vocab"]) for q in quizzes), "vocab pairs")

if __name__ == "__main__":
    main()
