#!/usr/bin/env python3
# Regenerate the Lessons 1-12 rows of src/lib/ff-latin/vocab-data.ts from Jacob's real First
# Form Latin quiz doc. Source: ~/Desktop/MT_RCAmaterial/first-form-latin-quizzes.txt
# (plain-text export of the Google Doc of RCA-adapted quizzes + answer keys). Vocab is parsed
# from the KEY sections; regex parsing is locked to Lessons 1-12 where the source format is
# simple word-pairs and parses cleanly.
#
# Lessons 14-31 use a different source format (full dictionary entries with gender/declension,
# not simple word-pairs) that this regex doesn't handle, and were HAND-VERIFIED against the
# KEY text directly (2026-09-16) instead. This script PRESERVES those rows unchanged by reading
# them back out of the existing OUT file before rewriting — it only ever regenerates the L<=12
# rows. Do not remove this preserve step; without it, a rerun silently wipes the hand-verified
# Lessons 14-31 work back to empty vocab arrays.
#
# Usage: python3 scripts/gen-ff-vocab.py
import re, json, os

SRC = os.path.expanduser("~/Desktop/MT_RCAmaterial/first-form-latin-quizzes.txt")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "ff-latin", "vocab-data.ts")
LAT = r"[a-zāēīōūăĕĭŏŭjv]"
BLOCK = {"perf", "pres", "pre", "present", "stem"}

def key_sections(lines):
    segs, cur = [], None
    for ln in lines:
        s = ln.strip().lstrip("\t").strip()
        if re.match(r"^Lessons?\s+([\d &]+?)\s+Quiz\b.*-\s*KEY\s*$", s, re.I):
            if cur: segs.append(cur)
            nums = [int(x) for x in re.findall(r"\d+", re.match(r"^Lessons?\s+([\d &]+?)\s+Quiz", s, re.I).group(1))]
            cur = {"lessons": nums, "lines": []}
        elif re.match(r"^Lessons?\s+[\d &]+?\s+Quiz\b", s, re.I) and "KEY" not in s.upper() and cur:
            segs.append(cur); cur = None
        elif cur is not None:
            cur["lines"].append(ln)
    if cur: segs.append(cur)
    return [x for x in segs if len(x["lines"]) > 5]

def parse_vocab(block):
    out, seen = [], set()
    for ln in block:
        for m in re.finditer(rf"([A-Za-z][A-Za-z,&\-\s]*?[A-Za-z\)])\s*_{{2,}}\s*({LAT}+(?:\s{LAT}+)?)_*", ln):
            eng = re.sub(r"^\s*\d+\.\s*", "", m.group(1)).strip()
            lat = m.group(2).strip()
            if "recite" in lat.lower() or not re.match(rf"^{LAT}+$", lat) or lat in BLOCK:
                continue
            if "," in eng and re.search(r"(are|ere|ire|us|vi)\b", eng):
                continue
            if not (1 <= len(lat) <= 20 and 2 <= len(eng) <= 40):
                continue
            k = (eng.lower(), lat.lower())
            if k in seen: continue
            seen.add(k); out.append({"english": eng, "latin": lat})
    return out

def parse_saying(block):
    t = "\n".join(block)
    m = re.search(r"(?:Let us[^_\n]*?|Saying[^_\n]*?|Latin Saying[^_\n]*?)_{3,}\s*([^\n_]+)", t)
    return re.sub(r"[_\s]+$", "", m.group(1)).strip() if m and m.group(1).strip() else None

def existing_rows_above_12():
    """Read back the current OUT file's hand-verified rows for lessons > 12, verbatim."""
    if not os.path.exists(OUT):
        return []
    text = open(OUT, encoding="utf-8").read()
    rows = []
    for ln in text.split("\n"):
        m = re.match(r"\s*\{\s*lessons:\s*\[([\d,\s]+)\].*\},?\s*$", ln)
        if m and max(int(x) for x in m.group(1).split(",")) > 12:
            rows.append(ln.rstrip(","))
    return rows

def main():
    lines = open(SRC, encoding="utf-8").read().replace("\r", "").split("\n")
    quizzes = []
    for s in key_sections(lines):
        L = max(s["lessons"])
        if L > 12:
            continue  # hand-verified separately; preserved below, not regenerated
        quizzes.append({
            "lessons": s["lessons"],
            "vocab": parse_vocab(s["lines"]),
            "sayingLatin": parse_saying(s["lines"]),
        })
    rows = []
    for q in quizzes:
        v = ", ".join("{english:%s, latin:%s}" % (json.dumps(x["english"]), json.dumps(x["latin"])) for x in q["vocab"])
        say = "null" if not q["sayingLatin"] else json.dumps(q["sayingLatin"])
        rows.append("  { lessons: %s, vocab: [%s], sayingLatin: %s }," % (json.dumps(q["lessons"]), v, say))
    rows += [r + "," for r in existing_rows_above_12()]
    header = ('// Lessons 1-12: AUTO-GENERATED by scripts/gen-ff-vocab.py from Jacob\'s real First Form\n'
              '// Latin quiz doc, hand-verified against the KEY sections.\n'
              '// Lessons 14-31: HAND-VERIFIED 2026-09-16 directly against every KEY section in\n'
              '// ~/Desktop/MT_RCAmaterial/first-form-latin-quizzes.txt (not run through the regex parser —\n'
              '// the source format changes from simple word-pairs to full dictionary entries with gender/\n'
              '// declension starting at Lesson 14, which the parser isn\'t built to handle; a subagent\n'
              '// extraction attempt on this same doc previously hallucinated forms, so this pass was done\n'
              '// by reading every KEY line directly). `latin` is the headword as tested in the KEY\n'
              '// (nominative for nouns/adjectives, 1st principal part for verbs) — matches the existing\n'
              '// L1-12 convention. Preserved verbatim by this script (see existing_rows_above_12); do not\n'
              '// hand-edit without re-checking against the source KEY text.\n'
              '//\n'
              '// Two errors found IN RCA\'s own answer keys while doing this pass (not fixed here — they\n'
              '// don\'t affect this vocab table, just flagging for Jacob): Lesson 14 KEY lists "agricola"\n'
              '// as (m) [correct — 1st-decl. noun, masculine despite the -a ending]; the Lesson 20 review\n'
              '// KEY re-lists the same word as "(f)" — a typo in RCA\'s own material. Lesson 23-24 KEY\n'
              '// lists "mater, matris" as "(m)" — mater is feminine; another apparent typo in RCA\'s key.\n\n'
              'export type QuizVocab = {\n  lessons: number[];\n'
              '  vocab: { english: string; latin: string }[];\n  sayingLatin: string | null;\n};\n\n'
              'export const FF_QUIZ_VOCAB: QuizVocab[] = [\n')
    open(OUT, "w").write(header + "\n".join(rows) + "\n];\n")
    print("wrote", OUT, "-", sum(len(q["vocab"]) for q in quizzes), "regenerated L1-12 vocab pairs,",
          len(existing_rows_above_12()), "L14-31 rows preserved")

if __name__ == "__main__":
    main()
